import React from 'react';
import { SceneObject } from '../types';

export interface ButtonTemplate {
  id: string;
  name: string;
  category: 'Pills & CTAs' | 'Glassmorphic' | '3D Tactile' | 'Neon & Cyberpunk' | 'Minimal & Modern' | 'Circular (FAB)' | 'E-Commerce';
  buttonStyle: '3d_push' | 'glass_panel' | 'pill' | 'rounded' | 'circle' | 'outline' | 'chamfer' | 'gradient';
  shape: 'pill' | 'rounded' | 'sharp' | 'chamfer' | 'circle' | '3d_push';
  text: string;
  color: string;
  secondaryColor?: string;
  borderColor?: string;
  textColor: string;
  icon?: string;
  iconPosition?: 'left' | 'right' | 'only';
  borderRadius?: number;
  borderWidth?: number;
  fontSize?: number;
  fontFamily?: string;
  fontWeight?: string;
  letterSpacing?: number;
  glowEffect?: boolean;
  glowColor?: string;
  url?: string;
  description: string;
  previewBg: string;
}

export const BUTTON_TEMPLATES: ButtonTemplate[] = [
  // --- 1. PILLS & CTAs ---
  {
    id: 'btn-pill-cyan-glow',
    name: 'Cyan Neon Glow Pill',
    category: 'Pills & CTAs',
    buttonStyle: 'gradient',
    shape: 'pill',
    text: 'Explore AR',
    color: '#06b6d4',
    secondaryColor: '#3b82f6',
    borderColor: '#67e8f9',
    textColor: '#ffffff',
    icon: 'Sparkles',
    iconPosition: 'left',
    borderRadius: 9999,
    borderWidth: 1,
    fontSize: 0.18,
    fontFamily: 'Inter',
    fontWeight: '700',
    letterSpacing: 0.02,
    glowEffect: true,
    glowColor: 'rgba(6, 182, 212, 0.6)',
    description: 'Vibrant luminous cyan gradient pill button with sparkles icon',
    previewBg: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
  },
  {
    id: 'btn-pill-sunset-gradient',
    name: 'Sunset Flame Pill',
    category: 'Pills & CTAs',
    buttonStyle: 'gradient',
    shape: 'pill',
    text: 'Get Started',
    color: '#f97316',
    secondaryColor: '#ec4899',
    borderColor: '#fdba74',
    textColor: '#ffffff',
    icon: 'ArrowRight',
    iconPosition: 'right',
    borderRadius: 9999,
    borderWidth: 0,
    fontSize: 0.18,
    fontFamily: 'Inter',
    fontWeight: '700',
    glowEffect: true,
    glowColor: 'rgba(249, 115, 22, 0.5)',
    description: 'High-energy orange to magenta gradient pill with right arrow',
    previewBg: 'linear-gradient(135deg, #f97316, #ec4899)',
  },
  {
    id: 'btn-pill-emerald-success',
    name: 'Emerald Action Pill',
    category: 'Pills & CTAs',
    buttonStyle: 'pill',
    shape: 'pill',
    text: 'Confirm Action',
    color: '#10b981',
    secondaryColor: '#059669',
    borderColor: '#34d399',
    textColor: '#ffffff',
    icon: 'Check',
    iconPosition: 'left',
    borderRadius: 9999,
    borderWidth: 1.5,
    fontSize: 0.17,
    fontFamily: 'Inter',
    fontWeight: '600',
    description: 'Crisp emerald green confirmation button with checkmark',
    previewBg: '#10b981',
  },
  {
    id: 'btn-pill-violet-rocket',
    name: 'Cosmic Violet Launch',
    category: 'Pills & CTAs',
    buttonStyle: 'gradient',
    shape: 'pill',
    text: 'Launch Experience',
    color: '#8b5cf6',
    secondaryColor: '#6366f1',
    borderColor: '#c4b5fd',
    textColor: '#ffffff',
    icon: 'Rocket',
    iconPosition: 'left',
    borderRadius: 9999,
    borderWidth: 1,
    fontSize: 0.18,
    fontFamily: 'Inter',
    fontWeight: '700',
    glowEffect: true,
    glowColor: 'rgba(139, 92, 246, 0.6)',
    description: 'Cyber violet pill with rocket icon and subtle purple glow',
    previewBg: 'linear-gradient(135deg, #8b5cf6, #6366f1)',
  },
  {
    id: 'btn-pill-frosted-ice',
    name: 'Frosted Ice Pill',
    category: 'Pills & CTAs',
    buttonStyle: 'pill',
    shape: 'pill',
    text: 'Learn More',
    color: 'rgba(255, 255, 255, 0.15)',
    borderColor: 'rgba(255, 255, 255, 0.4)',
    textColor: '#ffffff',
    icon: 'ArrowRight',
    iconPosition: 'right',
    borderRadius: 9999,
    borderWidth: 1.5,
    fontSize: 0.16,
    fontFamily: 'Inter',
    fontWeight: '500',
    description: 'Translucent frosted glass pill with subtle white border',
    previewBg: 'rgba(255, 255, 255, 0.12)',
  },

  // --- 2. GLASSMORPHIC PANELS & BUTTONS ---
  {
    id: 'btn-glass-floating-hud',
    name: 'Spatial Vision Glass Panel',
    category: 'Glassmorphic',
    buttonStyle: 'glass_panel',
    shape: 'rounded',
    text: 'Interactive System HUD',
    color: '#3b82f6',
    secondaryColor: 'rgba(255, 255, 255, 0.2)',
    borderColor: 'rgba(255, 255, 255, 0.25)',
    textColor: '#ffffff',
    icon: 'Sparkles',
    iconPosition: 'left',
    borderRadius: 16,
    borderWidth: 1,
    fontSize: 0.16,
    fontFamily: 'Inter',
    fontWeight: '600',
    description: 'VisionOS styled frosted glass interactive UI card with action button',
    previewBg: 'linear-gradient(135deg, rgba(255,255,255,0.1), rgba(255,255,255,0.02))',
  },
  {
    id: 'btn-glass-rounded-dark',
    name: 'Dark Obsidian Glass',
    category: 'Glassmorphic',
    buttonStyle: 'rounded',
    shape: 'rounded',
    text: 'Open Control Panel',
    color: '#18181b',
    borderColor: 'rgba(255, 255, 255, 0.15)',
    textColor: '#f4f4f5',
    icon: 'Settings',
    iconPosition: 'left',
    borderRadius: 12,
    borderWidth: 1,
    fontSize: 0.17,
    fontFamily: 'Inter',
    fontWeight: '600',
    description: 'Deep obsidian dark glass card button with crisp settings icon',
    previewBg: '#18181b',
  },
  {
    id: 'btn-glass-neon-border',
    name: 'Cyber Glass Neon',
    category: 'Glassmorphic',
    buttonStyle: 'rounded',
    shape: 'rounded',
    text: 'Initiate Link',
    color: 'rgba(15, 23, 42, 0.75)',
    borderColor: '#38bdf8',
    textColor: '#38bdf8',
    icon: 'Zap',
    iconPosition: 'left',
    borderRadius: 14,
    borderWidth: 1.5,
    fontSize: 0.17,
    fontFamily: 'Inter',
    fontWeight: '700',
    glowEffect: true,
    glowColor: 'rgba(56, 189, 248, 0.4)',
    description: 'Translucent glass with cyber cyan illuminated outline',
    previewBg: 'rgba(15, 23, 42, 0.8)',
  },

  // --- 3. 3D TACTILE PUSH BUTTONS ---
  {
    id: 'btn-3d-arcade-red',
    name: 'Arcade Physical Push Plunger',
    category: '3D Tactile',
    buttonStyle: '3d_push',
    shape: '3d_push',
    text: 'PUSH START',
    color: '#dc2626',
    secondaryColor: '#1c1917',
    textColor: '#ffffff',
    icon: 'Play',
    iconPosition: 'left',
    borderRadius: 8,
    borderWidth: 0,
    fontSize: 0.16,
    fontFamily: 'Inter',
    fontWeight: '900',
    description: 'Heavy tactile 3D mechanical push switch with bevel bezel and depression',
    previewBg: 'linear-gradient(180deg, #ef4444 0%, #991b1b 100%)',
  },
  {
    id: 'btn-3d-cyber-blue',
    name: 'Sci-Fi Tactile Key',
    category: '3D Tactile',
    buttonStyle: '3d_push',
    shape: '3d_push',
    text: 'ACTIVATE',
    color: '#2563eb',
    secondaryColor: '#0f172a',
    textColor: '#60a5fa',
    icon: 'Zap',
    iconPosition: 'left',
    borderRadius: 6,
    borderWidth: 0,
    fontSize: 0.16,
    fontFamily: 'JetBrains Mono',
    fontWeight: '800',
    description: 'Futuristic mechanical tactile trigger switch with glowing blue plunger',
    previewBg: 'linear-gradient(180deg, #3b82f6 0%, #1e3a8a 100%)',
  },
  {
    id: 'btn-3d-gold-luxury',
    name: '24K Gold Tactile Ingot',
    category: '3D Tactile',
    buttonStyle: '3d_push',
    shape: '3d_push',
    text: 'CLAIM REWARD',
    color: '#eab308',
    secondaryColor: '#451a03',
    textColor: '#451a03',
    icon: 'Sparkles',
    iconPosition: 'right',
    borderRadius: 10,
    borderWidth: 0,
    fontSize: 0.16,
    fontFamily: 'Inter',
    fontWeight: '800',
    description: 'Polished gold metallic physical button with rich specular shine',
    previewBg: 'linear-gradient(180deg, #fde047 0%, #ca8a04 100%)',
  },

  // --- 4. NEON & CYBERPUNK ---
  {
    id: 'btn-cyber-chamfer-yellow',
    name: 'Cyberpunk Chamfer 2077',
    category: 'Neon & Cyberpunk',
    buttonStyle: 'chamfer',
    shape: 'chamfer',
    text: 'EXECUTE // PROTOCOL',
    color: '#facc15',
    borderColor: '#eab308',
    textColor: '#000000',
    icon: 'Zap',
    iconPosition: 'left',
    borderRadius: 0,
    borderWidth: 2,
    fontSize: 0.16,
    fontFamily: 'JetBrains Mono',
    fontWeight: '900',
    letterSpacing: 0.05,
    description: 'Cut diagonal corner cyberpunk hazard yellow high-contrast button',
    previewBg: '#facc15',
  },
  {
    id: 'btn-cyber-matrix-green',
    name: 'Matrix Terminal Outline',
    category: 'Neon & Cyberpunk',
    buttonStyle: 'outline',
    shape: 'sharp',
    text: 'ROOT_ACCESS >',
    color: '#052e16',
    borderColor: '#22c55e',
    textColor: '#4ade80',
    icon: 'Shield',
    iconPosition: 'left',
    borderRadius: 0,
    borderWidth: 2,
    fontSize: 0.16,
    fontFamily: 'JetBrains Mono',
    fontWeight: '700',
    glowEffect: true,
    glowColor: 'rgba(34, 197, 94, 0.6)',
    description: 'Sci-Fi terminal green outline button with dark core and glowing border',
    previewBg: '#052e16',
  },
  {
    id: 'btn-cyber-crimson-danger',
    name: 'Crimson Breach Alert',
    category: 'Neon & Cyberpunk',
    buttonStyle: 'chamfer',
    shape: 'chamfer',
    text: 'EMERGENCY OVERRIDE',
    color: '#dc2626',
    borderColor: '#f87171',
    textColor: '#ffffff',
    icon: 'Shield',
    iconPosition: 'left',
    borderRadius: 0,
    borderWidth: 2,
    fontSize: 0.16,
    fontFamily: 'Inter',
    fontWeight: '800',
    glowEffect: true,
    glowColor: 'rgba(220, 38, 38, 0.6)',
    description: 'High-priority critical alert button with angular cut corners and red glow',
    previewBg: '#dc2626',
  },
  {
    id: 'btn-outline-cyan-laser',
    name: 'Neon Cyan Laser Wire',
    category: 'Neon & Cyberpunk',
    buttonStyle: 'outline',
    shape: 'rounded',
    text: 'CONNECT AR',
    color: 'transparent',
    borderColor: '#06b6d4',
    textColor: '#22d3ee',
    icon: 'Sparkles',
    iconPosition: 'right',
    borderRadius: 12,
    borderWidth: 2,
    fontSize: 0.17,
    fontFamily: 'Inter',
    fontWeight: '700',
    glowEffect: true,
    glowColor: 'rgba(6, 182, 212, 0.5)',
    description: 'Hollow laser wireframe outline button with neon cyan perimeter glow',
    previewBg: 'transparent',
  },

  // --- 5. MINIMAL & MODERN ---
  {
    id: 'btn-rounded-indigo-cta',
    name: 'Royal Indigo Modern CTA',
    category: 'Minimal & Modern',
    buttonStyle: 'rounded',
    shape: 'rounded',
    text: 'Continue with Scene',
    color: '#4f46e5',
    borderColor: '#818cf8',
    textColor: '#ffffff',
    icon: 'ArrowRight',
    iconPosition: 'right',
    borderRadius: 12,
    borderWidth: 0,
    fontSize: 0.18,
    fontFamily: 'Inter',
    fontWeight: '600',
    description: 'Sleek royal indigo rounded rectangle with smooth corner curves',
    previewBg: '#4f46e5',
  },
  {
    id: 'btn-rounded-slate-tool',
    name: 'Slate Precision Tool',
    category: 'Minimal & Modern',
    buttonStyle: 'rounded',
    shape: 'rounded',
    text: 'Inspect Geometry',
    color: '#334155',
    borderColor: '#64748b',
    textColor: '#f8fafc',
    icon: 'Settings',
    iconPosition: 'left',
    borderRadius: 10,
    borderWidth: 1,
    fontSize: 0.16,
    fontFamily: 'Inter',
    fontWeight: '500',
    description: 'Clean slate professional tool button with subtle gray border',
    previewBg: '#334155',
  },
  {
    id: 'btn-sharp-monochrome',
    name: 'Brutalist Monochrome',
    category: 'Minimal & Modern',
    buttonStyle: 'rounded',
    shape: 'sharp',
    text: 'DISCOVER MORE',
    color: '#ffffff',
    borderColor: '#000000',
    textColor: '#000000',
    icon: 'ArrowRight',
    iconPosition: 'right',
    borderRadius: 0,
    borderWidth: 2,
    fontSize: 0.16,
    fontFamily: 'Inter',
    fontWeight: '800',
    description: 'High-contrast stark brutalist white button with solid black text and 0px radius',
    previewBg: '#ffffff',
  },
  {
    id: 'btn-rounded-pink-heart',
    name: 'Vivid Magenta Delight',
    category: 'Minimal & Modern',
    buttonStyle: 'gradient',
    shape: 'rounded',
    text: 'Add to Favorites',
    color: '#ec4899',
    secondaryColor: '#db2777',
    borderColor: '#f472b6',
    textColor: '#ffffff',
    icon: 'Heart',
    iconPosition: 'left',
    borderRadius: 14,
    borderWidth: 1,
    fontSize: 0.17,
    fontFamily: 'Inter',
    fontWeight: '600',
    description: 'Bright magenta rounded button with glowing heart icon',
    previewBg: 'linear-gradient(135deg, #ec4899, #db2777)',
  },

  // --- 6. CIRCULAR (FAB) & ROUND BUTTONS ---
  {
    id: 'btn-circle-fab-plus',
    name: 'Circular Quick-Add FAB',
    category: 'Circular (FAB)',
    buttonStyle: 'circle',
    shape: 'circle',
    text: '+',
    color: '#3b82f6',
    secondaryColor: '#2563eb',
    borderColor: '#93c5fd',
    textColor: '#ffffff',
    icon: 'Plus',
    iconPosition: 'only',
    borderRadius: 9999,
    borderWidth: 2,
    fontSize: 0.28,
    fontFamily: 'Inter',
    fontWeight: '700',
    glowEffect: true,
    glowColor: 'rgba(59, 130, 246, 0.6)',
    description: 'Round floating action button (FAB) for instant additions and spawns',
    previewBg: '#3b82f6',
  },
  {
    id: 'btn-circle-play-pulse',
    name: 'Glowing Media Play Ring',
    category: 'Circular (FAB)',
    buttonStyle: 'circle',
    shape: 'circle',
    text: 'Play',
    color: '#ec4899',
    secondaryColor: '#8b5cf6',
    borderColor: '#f472b6',
    textColor: '#ffffff',
    icon: 'Play',
    iconPosition: 'only',
    borderRadius: 9999,
    borderWidth: 2,
    fontSize: 0.22,
    fontFamily: 'Inter',
    fontWeight: '700',
    glowEffect: true,
    glowColor: 'rgba(236, 72, 153, 0.6)',
    description: 'Circular media player play button with pulse ring and pink glow',
    previewBg: 'linear-gradient(135deg, #ec4899, #8b5cf6)',
  },
  {
    id: 'btn-circle-compass-ar',
    name: 'AR Compass Navigation',
    category: 'Circular (FAB)',
    buttonStyle: 'circle',
    shape: 'circle',
    text: 'Nav',
    color: '#06b6d4',
    secondaryColor: '#0284c7',
    borderColor: '#67e8f9',
    textColor: '#ffffff',
    icon: 'Compass',
    iconPosition: 'only',
    borderRadius: 9999,
    borderWidth: 1.5,
    fontSize: 0.22,
    fontFamily: 'Inter',
    fontWeight: '700',
    description: 'Circular AR orientation compass action button',
    previewBg: '#06b6d4',
  },
  {
    id: 'btn-circle-like-heart',
    name: 'Glow Heart Favorite',
    category: 'Circular (FAB)',
    buttonStyle: 'circle',
    shape: 'circle',
    text: 'Like',
    color: '#ef4444',
    secondaryColor: '#b91c1c',
    borderColor: '#fca5a5',
    textColor: '#ffffff',
    icon: 'Heart',
    iconPosition: 'only',
    borderRadius: 9999,
    borderWidth: 1.5,
    fontSize: 0.22,
    fontFamily: 'Inter',
    fontWeight: '700',
    glowEffect: true,
    glowColor: 'rgba(239, 68, 68, 0.6)',
    description: 'Circular like / bookmark button with crimson red glow',
    previewBg: '#ef4444',
  },

  // --- 7. E-COMMERCE & ACTIONS ---
  {
    id: 'btn-ecom-add-to-cart',
    name: 'Add to Cart CTA',
    category: 'E-Commerce',
    buttonStyle: 'rounded',
    shape: 'rounded',
    text: 'Add to Cart — $49',
    color: '#10b981',
    secondaryColor: '#059669',
    borderColor: '#6ee7b7',
    textColor: '#ffffff',
    icon: 'ShoppingCart',
    iconPosition: 'left',
    borderRadius: 12,
    borderWidth: 1,
    fontSize: 0.17,
    fontFamily: 'Inter',
    fontWeight: '700',
    description: 'High-converting e-commerce cart button with shopping cart icon and price tag',
    previewBg: 'linear-gradient(135deg, #10b981, #059669)',
  },
  {
    id: 'btn-ecom-buy-now',
    name: 'Instant Buy Sparkle',
    category: 'E-Commerce',
    buttonStyle: 'gradient',
    shape: 'pill',
    text: 'Buy Now with Apple Pay',
    color: '#f59e0b',
    secondaryColor: '#d97706',
    borderColor: '#fde68a',
    textColor: '#000000',
    icon: 'Sparkles',
    iconPosition: 'right',
    borderRadius: 9999,
    borderWidth: 1,
    fontSize: 0.17,
    fontFamily: 'Inter',
    fontWeight: '800',
    description: 'Amber gold checkout button with sparkling badge',
    previewBg: 'linear-gradient(135deg, #f59e0b, #d97706)',
  },
  {
    id: 'btn-ecom-download-app',
    name: 'Cloud Download Button',
    category: 'E-Commerce',
    buttonStyle: 'rounded',
    shape: 'rounded',
    text: 'Download AR Asset (.zip)',
    color: '#0284c7',
    borderColor: '#38bdf8',
    textColor: '#ffffff',
    icon: 'Download',
    iconPosition: 'left',
    borderRadius: 12,
    borderWidth: 1,
    fontSize: 0.16,
    fontFamily: 'Inter',
    fontWeight: '600',
    description: 'Clean digital download button with download icon and file format',
    previewBg: '#0284c7',
  }
];

export function createSceneObjectFromButtonTemplate(template: ButtonTemplate): Partial<SceneObject> {
  return {
    type: 'button',
    name: template.name,
    properties: {
      buttonStyle: template.buttonStyle,
      shape: template.shape,
      text: template.text,
      color: template.color,
      secondaryColor: template.secondaryColor || template.color,
      borderColor: template.borderColor || 'rgba(255,255,255,0.2)',
      textColor: template.textColor,
      icon: template.icon || '',
      iconPosition: template.iconPosition || 'left',
      borderRadius: template.borderRadius ?? (template.shape === 'pill' ? 9999 : template.shape === 'circle' ? 9999 : 12),
      borderWidth: template.borderWidth ?? 0,
      fontSize: template.fontSize ?? 0.18,
      fontFamily: template.fontFamily || 'Inter',
      fontWeight: template.fontWeight || '600',
      letterSpacing: template.letterSpacing ?? 0,
      glowEffect: template.glowEffect ?? false,
      glowColor: template.glowColor || 'rgba(59, 130, 246, 0.5)',
      url: template.url || '',
    },
    scale: [1, 1, 1],
    position: [0, 0, 0],
    rotation: [0, 0, 0],
  };
}
