import React from 'react';
import { SceneObject } from '../types';

export interface PrimitiveTemplate {
  id: string;
  name: string;
  category: 'Textured Shapes' | 'Basic Geometry' | 'Sci-Fi Primitives' | 'Organic & Metallic';
  type: 'circle' | 'box' | 'sphere' | 'cylinder' | 'plane' | 'cone' | 'torus' | 'pyramid' | 'capsule' | 'dodecahedron' | 'octahedron' | 'icosahedron' | 'knot' | 'empty';
  description: string;
  position?: [number, number, number];
  rotation?: [number, number, number];
  scale?: [number, number, number];
  properties: {
    color?: string;
    textureUrl?: string;
    normalMapUrl?: string;
    roughness?: number;
    metalness?: number;
    clearcoat?: number;
    clearcoatRoughness?: number;
    transmission?: number;
    opacity?: number;
    emissiveColor?: string;
    emissiveIntensity?: number;
    doubleSided?: boolean;
    textureRepeatX?: number;
    textureRepeatY?: number;
    wireframe?: boolean;
    radius?: number;
    segments?: number;
    behavior?: string;
    spinAxis?: 'x' | 'y' | 'z';
    behaviorSpeed?: number;
    behaviorIntensity?: number;
  };
  previewColor: string;
  previewGradient?: string;
  badge: string;
  badgeColor?: string;
  icon: string;
}

export const PRIMITIVE_TEMPLATES: PrimitiveTemplate[] = [
  // --- 0. STANDARD UNTEXTURED GEOMETRY ---
  {
    id: 'prim-empty-anchor',
    name: 'Empty Object Anchor',
    category: 'Basic Geometry',
    type: 'empty',
    description: 'Empty spatial transform node used as a parent container or pivot anchor',
    properties: {},
    previewColor: '#8b5cf6',
    previewGradient: 'radial-gradient(circle, #a855f7 0%, #6b21a8 100%)',
    badge: 'NULL NODE',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    icon: '🎯',
  },
  {
    id: 'prim-basic-cube',
    name: 'Standard 3D Cube',
    category: 'Basic Geometry',
    type: 'box',
    description: 'Uniform 6-sided 3D box geometry ready for transformation and texturing',
    properties: {
      color: '#3b82f6',
      roughness: 0.4,
      metalness: 0.1,
    },
    previewColor: '#3b82f6',
    previewGradient: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',
    badge: 'CUBE',
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    icon: '📦',
  },
  {
    id: 'prim-basic-sphere',
    name: 'Standard 3D Sphere',
    category: 'Basic Geometry',
    type: 'sphere',
    description: 'High-segment smooth 3D UV sphere geometry',
    properties: {
      color: '#ec4899',
      roughness: 0.3,
      metalness: 0.2,
    },
    previewColor: '#ec4899',
    previewGradient: 'radial-gradient(circle at 35% 35%, #f472b6, #db2777)',
    badge: 'SPHERE',
    badgeColor: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
    icon: '⚪',
  },
  {
    id: 'prim-basic-cylinder',
    name: 'Standard Cylinder',
    category: 'Basic Geometry',
    type: 'cylinder',
    description: 'Smooth vertical cylinder geometry with top and bottom caps',
    properties: {
      color: '#10b981',
      roughness: 0.35,
      metalness: 0.15,
    },
    previewColor: '#10b981',
    previewGradient: 'linear-gradient(180deg, #34d399 0%, #059669 100%)',
    badge: 'CYLINDER',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    icon: '🔋',
  },
  {
    id: 'prim-basic-cone',
    name: 'Standard Cone',
    category: 'Basic Geometry',
    type: 'cone',
    description: 'Radial tapered 3D cone geometry with circular base',
    properties: {
      color: '#f59e0b',
      roughness: 0.35,
      metalness: 0.15,
    },
    previewColor: '#f59e0b',
    previewGradient: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',
    badge: 'CONE',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    icon: '🗼',
  },
  {
    id: 'prim-basic-torus',
    name: 'Standard Torus Ring',
    category: 'Basic Geometry',
    type: 'torus',
    description: 'Circular donut ring torus geometry with gentle float behavior',
    properties: {
      color: '#8b5cf6',
      roughness: 0.25,
      metalness: 0.4,
      behavior: 'hover',
      behaviorSpeed: 1.0,
      behaviorIntensity: 1.0,
    },
    previewColor: '#8b5cf6',
    previewGradient: 'radial-gradient(circle, #a78bfa 0%, #7c3aed 100%)',
    badge: 'TORUS',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    icon: '🍩',
  },
  {
    id: 'prim-basic-plane',
    name: 'Standard 2D Plane',
    category: 'Basic Geometry',
    type: 'plane',
    description: 'Flat single-sided or double-sided planar surface for posters and ground meshes',
    properties: {
      color: '#64748b',
      roughness: 0.5,
      metalness: 0.0,
      doubleSided: true,
    },
    previewColor: '#64748b',
    previewGradient: 'linear-gradient(135deg, #94a3b8 0%, #475569 100%)',
    badge: 'PLANE',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    icon: '📄',
  },
  {
    id: 'prim-basic-circle',
    name: 'Standard Flat Disc',
    category: 'Basic Geometry',
    type: 'circle',
    description: 'Circular flat 2D disc with smooth radial segments',
    properties: {
      color: '#06b6d4',
      roughness: 0.4,
      metalness: 0.1,
      doubleSided: true,
      radius: 0.6,
      segments: 64,
    },
    previewColor: '#06b6d4',
    previewGradient: 'radial-gradient(circle, #67e8f9 0%, #0891b2 100%)',
    badge: 'DISC',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    icon: '🔘',
  },
  {
    id: 'prim-basic-knot',
    name: 'Torus Knot Polyhedron',
    category: 'Basic Geometry',
    type: 'knot',
    description: 'Complex intertwined 3D torus knot mathematical geometry with continuous spin',
    properties: {
      color: '#ec4899',
      roughness: 0.2,
      metalness: 0.8,
      clearcoat: 0.6,
      behavior: 'spin',
      spinAxis: 'y',
      behaviorSpeed: 1.0,
      behaviorIntensity: 1.0,
    },
    previewColor: '#ec4899',
    previewGradient: 'linear-gradient(135deg, #f472b6, #9333ea)',
    badge: 'TORUS KNOT',
    badgeColor: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
    icon: '🪢',
  },
  {
    id: 'prim-basic-icosahedron',
    name: 'Icosahedron Gem',
    category: 'Basic Geometry',
    type: 'icosahedron',
    description: '20-faced equilateral triangular polyhedron geometric mesh with pulse motion',
    properties: {
      color: '#14b8a6',
      roughness: 0.15,
      metalness: 0.7,
      clearcoat: 0.8,
      behavior: 'pulse',
      behaviorSpeed: 1.2,
      behaviorIntensity: 1.0,
    },
    previewColor: '#14b8a6',
    previewGradient: 'radial-gradient(circle, #5eead4, #0f766e)',
    badge: 'ICOSAHEDRON',
    badgeColor: 'bg-teal-500/20 text-teal-300 border-teal-500/30',
    icon: '💠',
  },
  {
    id: 'prim-basic-octahedron',
    name: 'Octahedron Polyhedron',
    category: 'Basic Geometry',
    type: 'octahedron',
    description: '8-sided dual triangular pyramid crystalline geometric shape',
    properties: {
      color: '#eab308',
      roughness: 0.1,
      metalness: 0.9,
      clearcoat: 0.9,
    },
    previewColor: '#eab308',
    previewGradient: 'linear-gradient(135deg, #fef08a, #ca8a04)',
    badge: 'OCTAHEDRON',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    icon: '🔶',
  },
  // --- 1. CIRCLES & DISCS (TEXTURED) ---
  {
    id: 'prim-circle-carbon',
    name: 'Carbon Fiber Disc',
    category: 'Textured Shapes',
    type: 'circle',
    description: 'Circular flat disc with weave carbon texture pattern and satin sheen',
    properties: {
      color: '#27272a',
      textureUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
      roughness: 0.35,
      metalness: 0.8,
      clearcoat: 0.6,
      doubleSided: true,
      radius: 0.6,
      segments: 64,
      textureRepeatX: 3,
      textureRepeatY: 3,
    },
    previewColor: '#18181b',
    previewGradient: 'radial-gradient(circle, #3f3f46 0%, #18181b 70%, #09090b 100%)',
    badge: 'TEXTURED DISC',
    badgeColor: 'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    icon: '🔘',
  },
  {
    id: 'prim-circle-hologram',
    name: 'Holographic Cyber Disc',
    category: 'Textured Shapes',
    type: 'circle',
    description: 'Iridescent glowing holographic portal disc with cyan/magenta shifts',
    properties: {
      color: '#06b6d4',
      textureUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
      roughness: 0.1,
      metalness: 0.9,
      emissiveColor: '#0891b2',
      emissiveIntensity: 0.4,
      clearcoat: 1.0,
      doubleSided: true,
      radius: 0.6,
      segments: 64,
      behavior: 'spin',
      spinAxis: 'z',
      behaviorSpeed: 1.0,
      behaviorIntensity: 1.0,
    },
    previewColor: '#06b6d4',
    previewGradient: 'radial-gradient(circle, #67e8f9 0%, #06b6d4 50%, #7c3aed 100%)',
    badge: 'HOLOGRAM DISC',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    icon: '💿',
  },
  {
    id: 'prim-circle-gold-foil',
    name: '24K Gold Leaf Disc',
    category: 'Organic & Metallic',
    type: 'circle',
    description: 'Circular metallic gold emblem with micro-roughness specular highlights',
    properties: {
      color: '#eab308',
      textureUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80',
      roughness: 0.25,
      metalness: 0.95,
      clearcoat: 0.4,
      doubleSided: true,
      radius: 0.6,
      segments: 64,
    },
    previewColor: '#eab308',
    previewGradient: 'radial-gradient(circle, #fef08a 0%, #eab308 60%, #854d0e 100%)',
    badge: 'GOLD DISC',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    icon: '🪙',
  },
  {
    id: 'prim-circle-marble',
    name: 'White Carrara Marble Disc',
    category: 'Organic & Metallic',
    type: 'circle',
    description: 'Polished white Italian marble circular pedestal disc',
    properties: {
      color: '#f8fafc',
      textureUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
      roughness: 0.2,
      metalness: 0.1,
      clearcoat: 0.8,
      doubleSided: true,
      radius: 0.6,
      segments: 64,
    },
    previewColor: '#f8fafc',
    previewGradient: 'radial-gradient(circle, #ffffff 0%, #e2e8f0 70%, #94a3b8 100%)',
    badge: 'MARBLE DISC',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    icon: '⚪',
  },

  // --- 2. TEXTURED CUBES & BOXES ---
  {
    id: 'prim-box-carbon',
    name: 'Carbon Fiber Cube',
    category: 'Textured Shapes',
    type: 'box',
    description: 'Solid cube draped in cross-weave composite carbon texture',
    properties: {
      color: '#27272a',
      textureUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
      roughness: 0.3,
      metalness: 0.85,
      clearcoat: 0.5,
      textureRepeatX: 2,
      textureRepeatY: 2,
    },
    previewColor: '#27272a',
    previewGradient: 'linear-gradient(135deg, #3f3f46, #18181b)',
    badge: 'TEXTURED CUBE',
    badgeColor: 'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    icon: '🧊',
  },
  {
    id: 'prim-box-circuit',
    name: 'Cyber Circuit Board Cube',
    category: 'Sci-Fi Primitives',
    type: 'box',
    description: 'Tech cube with microchip circuits and illuminated traces',
    properties: {
      color: '#064e3b',
      textureUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
      roughness: 0.4,
      metalness: 0.6,
      emissiveColor: '#10b981',
      emissiveIntensity: 0.25,
    },
    previewColor: '#064e3b',
    previewGradient: 'linear-gradient(135deg, #059669, #022c22)',
    badge: 'CIRCUIT CUBE',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    icon: '🎛️',
  },

  // --- 3. TEXTURED SPHERES ---
  {
    id: 'prim-sphere-hologram',
    name: 'Holographic Iridescent Orb',
    category: 'Sci-Fi Primitives',
    type: 'sphere',
    description: 'Glossy iridescent physical sphere with liquid chromatic reflections',
    properties: {
      color: '#ec4899',
      textureUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
      roughness: 0.05,
      metalness: 0.95,
      clearcoat: 1.0,
      emissiveColor: '#a855f7',
      emissiveIntensity: 0.3,
    },
    previewColor: '#ec4899',
    previewGradient: 'radial-gradient(circle at 35% 35%, #f472b6, #a855f7, #3b82f6)',
    badge: 'HOLO ORB',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    icon: '🔮',
  },
  {
    id: 'prim-sphere-magma',
    name: 'Molten Magma Sphere',
    category: 'Organic & Metallic',
    type: 'sphere',
    description: 'Volcanic glowing lava sphere with emissive fissures',
    properties: {
      color: '#ea580c',
      textureUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
      roughness: 0.7,
      metalness: 0.2,
      emissiveColor: '#ef4444',
      emissiveIntensity: 0.6,
    },
    previewColor: '#ea580c',
    previewGradient: 'radial-gradient(circle at 35% 35%, #fbbf24, #ea580c, #7f1d1d)',
    badge: 'MAGMA ORB',
    badgeColor: 'bg-orange-500/20 text-orange-300 border-orange-500/30',
    icon: '🌋',
  },

  // --- 4. CYLINDER & TORUS ---
  {
    id: 'prim-cylinder-energy',
    name: 'Sci-Fi Plasma Energy Core',
    category: 'Sci-Fi Primitives',
    type: 'cylinder',
    description: 'Luminous cylindrical energy conduit with neon plasma coil',
    properties: {
      color: '#38bdf8',
      textureUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
      roughness: 0.2,
      metalness: 0.8,
      emissiveColor: '#0284c7',
      emissiveIntensity: 0.5,
    },
    previewColor: '#38bdf8',
    previewGradient: 'linear-gradient(180deg, #7dd3fc, #0284c7, #082f49)',
    badge: 'ENERGY CORE',
    badgeColor: 'bg-sky-500/20 text-sky-300 border-sky-500/30',
    icon: '🔋',
  },
  {
    id: 'prim-torus-portal',
    name: 'Quantum Portal Torus Ring',
    category: 'Sci-Fi Primitives',
    type: 'torus',
    description: 'Circular quantum gateway ring with neon laser reflections',
    properties: {
      color: '#a855f7',
      textureUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
      roughness: 0.1,
      metalness: 0.9,
      emissiveColor: '#7e22ce',
      emissiveIntensity: 0.4,
    },
    previewColor: '#a855f7',
    previewGradient: 'radial-gradient(circle, #e9d5ff, #9333ea, #3b0764)',
    badge: 'PORTAL RING',
    badgeColor: 'bg-violet-500/20 text-violet-300 border-violet-500/30',
    icon: '🍩',
  },

  // --- 5. PLANES & PYRAMIDS ---
  {
    id: 'prim-plane-grid',
    name: 'Infinite Cyber Grid Floor',
    category: 'Textured Shapes',
    type: 'plane',
    description: 'Reflective horizontal plane with luminous 80s synthwave neon grid',
    position: [0, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [20, 20, 1],
    properties: {
      color: '#09090b',
      textureUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
      roughness: 0.1,
      metalness: 0.9,
      emissiveColor: '#a21caf',
      emissiveIntensity: 0.3,
      doubleSided: true,
      textureRepeatX: 8,
      textureRepeatY: 8,
    },
    previewColor: '#09090b',
    previewGradient: 'linear-gradient(135deg, #09090b, #3b0764, #1e1b4b)',
    badge: 'CYBER GRID',
    badgeColor: 'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-500/30',
    icon: '🏁',
  },
  {
    id: 'prim-pyramid-gold',
    name: 'Polished Gold Pyramid',
    category: 'Organic & Metallic',
    type: 'pyramid',
    description: 'Angular 4-sided pyramid with mirrored gold sides',
    properties: {
      color: '#eab308',
      roughness: 0.15,
      metalness: 0.95,
      clearcoat: 0.8,
    },
    previewColor: '#eab308',
    previewGradient: 'linear-gradient(135deg, #fef08a, #ca8a04)',
    badge: 'GOLD PYRAMID',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    icon: '🔺',
  },
  {
    id: 'prim-capsule-pill',
    name: 'Smooth Violet Capsule',
    category: 'Basic Geometry',
    type: 'capsule',
    description: 'Rounded pill-shaped 3D capsule with iridescent gradient',
    properties: {
      color: '#8b5cf6',
      roughness: 0.2,
      metalness: 0.6,
      clearcoat: 0.8,
    },
    previewColor: '#8b5cf6',
    previewGradient: 'linear-gradient(180deg, #c4b5fd, #7c3aed, #4c1d95)',
    badge: 'CAPSULE',
    badgeColor: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    icon: '💊',
  },
  {
    id: 'prim-dodecahedron-gem',
    name: '3D Faceted Diamond Dodecahedron',
    category: 'Basic Geometry',
    type: 'dodecahedron',
    description: '12-faced geometric gemstone with crystal facet reflections',
    properties: {
      color: '#06b6d4',
      roughness: 0.05,
      metalness: 0.9,
      clearcoat: 1.0,
    },
    previewColor: '#06b6d4',
    previewGradient: 'radial-gradient(circle at 30% 30%, #a5f3fc, #0891b2, #164e63)',
    badge: 'GEMSTONE',
    badgeColor: 'bg-teal-500/20 text-teal-300 border-teal-500/30',
    icon: '💎',
  }
];

export function createSceneObjectFromPrimitive(prim: PrimitiveTemplate): Partial<SceneObject> {
  return {
    type: prim.type as any,
    name: prim.name,
    properties: {
      ...prim.properties,
    },
    scale: [1, 1, 1],
    position: [0, 0, 0],
    rotation: [0, 0, 0],
  };
}
