import { SceneObject, Vector3Data } from '../types';

export type TextStyleCategory = 
  | 'Hero & Display'
  | 'Subtitle & Eyebrows'
  | 'Cyber & Neon'
  | 'Glass & Holographic'
  | 'CTA & Buttons'
  | 'AR Telemetry & Metrics'
  | 'Retro & Vintage'
  | 'Gradients & Metallic'
  | 'Badges & Labels';

export type TextSurfaceTarget = '2D HUD' | '3D Scene';

export interface TextStylePreset {
  id: string;
  name: string;
  category: TextStyleCategory;
  target: TextSurfaceTarget;
  sampleText: string;
  description: string;
  badge: string;
  objectType: 'hudText' | 'hudButton' | 'text' | 'button';
  tags: string[];
  previewStyle: {
    fontFamily?: string;
    fontSize?: string;
    fontWeight?: string;
    color?: string;
    background?: string;
    border?: string;
    borderRadius?: string;
    padding?: string;
    textShadow?: string;
    letterSpacing?: string;
    fontStyle?: 'italic' | 'normal';
    textTransform?: 'uppercase' | 'lowercase' | 'capitalize' | 'none';
    boxShadow?: string;
    backdropFilter?: string;
  };
  properties: Record<string, any>;
  scale?: Vector3Data;
  position?: Vector3Data;
  rotation?: Vector3Data;
}

export const TEXT_STYLE_PRESETS: TextStylePreset[] = [
  // ==========================================
  // 1. HERO & DISPLAY TITLES (10 PRESETS)
  // ==========================================
  {
    id: 'ts-hero-bold-vision',
    name: 'Vision Spatial Title',
    category: 'Hero & Display',
    target: '2D HUD',
    sampleText: 'SPATIAL VISION OS',
    description: 'Clean high-contrast bold display title with tight letter spacing for spatial headers.',
    badge: 'VISION OS',
    objectType: 'hudText',
    tags: ['hero', 'title', 'vision', 'bold'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '22px',
      fontWeight: '800',
      color: '#ffffff',
      letterSpacing: '-0.03em',
      textShadow: '0 4px 20px rgba(255,255,255,0.3)',
    },
    properties: {
      text: 'SPATIAL VISION OS',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 32,
      fontWeight: '800',
      color: '#ffffff',
      letterSpacing: '-0.03em',
      textShadow: '0 4px 20px rgba(255,255,255,0.3)',
      alignment: 'top-left',
      offsetX: 40,
      offsetY: 40,
    }
  },
  {
    id: 'ts-hero-glowing-cyan',
    name: 'Cyber Core Hero Header',
    category: 'Hero & Display',
    target: '2D HUD',
    sampleText: 'NEXUS AR MATRIX',
    description: 'Electric cyan glowing display title with intense shadow aura.',
    badge: 'CYBER',
    objectType: 'hudText',
    tags: ['hero', 'cyber', 'neon', 'cyan'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '20px',
      fontWeight: '800',
      color: '#22d3ee',
      letterSpacing: '0.05em',
      textShadow: '0 0 12px #06b6d4, 0 0 24px #0891b2',
    },
    properties: {
      text: 'NEXUS AR MATRIX',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 28,
      fontWeight: '800',
      color: '#22d3ee',
      letterSpacing: '0.05em',
      textShadow: '0 0 12px #06b6d4, 0 0 24px #0891b2',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 40,
    }
  },
  {
    id: 'ts-hero-glass-title',
    name: 'Frosted Glass Plaque Title',
    category: 'Hero & Display',
    target: '2D HUD',
    sampleText: 'AUGMENTED STUDIO',
    description: 'Frosted glass rounded plaque header with semi-transparent backdrop.',
    badge: 'GLASS',
    objectType: 'hudText',
    tags: ['hero', 'glass', 'panel', 'title'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '18px',
      fontWeight: '700',
      color: '#f8fafc',
      background: 'rgba(255,255,255,0.1)',
      border: '1px solid rgba(255,255,255,0.2)',
      borderRadius: '12px',
      padding: '8px 16px',
      backdropFilter: 'blur(12px)',
      boxShadow: '0 8px 32px rgba(0,0,0,0.3)',
    },
    properties: {
      text: 'AUGMENTED STUDIO',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 26,
      fontWeight: '700',
      color: '#f8fafc',
      backgroundColor: 'rgba(255,255,255,0.1)',
      border: '1px solid rgba(255,255,255,0.2)',
      borderRadius: '16px',
      padding: '12px 24px',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-hero-3d-glowing-gold',
    name: '3D Golden Luxury Title',
    category: 'Hero & Display',
    target: '3D Scene',
    sampleText: 'SOLARIS GOLD 3D',
    description: '3D floating title with gold metallic shine and outline depth.',
    badge: '3D GOLD',
    objectType: 'text',
    tags: ['3d', 'gold', 'title', 'luxury'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '20px',
      fontWeight: '800',
      color: '#f59e0b',
      textShadow: '2px 2px 0px #b45309, 4px 4px 10px rgba(245,158,11,0.5)',
    },
    properties: {
      text: 'SOLARIS GOLD 3D',
      color: '#f59e0b',
      fontSize: 0.25,
      outlineColor: '#78350f',
      outlineWidth: 0.02,
      textAlign: 'center',
    },
    position: [0, 1.2, 0]
  },
  {
    id: 'ts-hero-crimson-strike',
    name: 'Crimson Strike Header',
    category: 'Hero & Display',
    target: '2D HUD',
    sampleText: 'REDLINE OVERDRIVE',
    description: 'Aggressive uppercase italic title in vibrant crimson red.',
    badge: 'SPORT',
    objectType: 'hudText',
    tags: ['hero', 'red', 'bold', 'speed'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '20px',
      fontWeight: '900',
      color: '#f43f5e',
      textTransform: 'uppercase',
      letterSpacing: '0.08em',
      textShadow: '0 0 15px rgba(244,63,94,0.6)',
    },
    properties: {
      text: 'REDLINE OVERDRIVE',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 30,
      fontWeight: '900',
      color: '#f43f5e',
      letterSpacing: '0.08em',
      textShadow: '0 0 15px rgba(244,63,94,0.6)',
      alignment: 'top-left',
      offsetX: 40,
      offsetY: 40,
    }
  },
  {
    id: 'ts-hero-gradient-sunset',
    name: 'Sunset Gradient Title',
    category: 'Hero & Display',
    target: '2D HUD',
    sampleText: 'HORIZON SPECTRA',
    description: 'Vibrant sunset gradient text style with ultra-bold weight.',
    badge: 'GRADIENT',
    objectType: 'hudText',
    tags: ['hero', 'gradient', 'sunset', 'title'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '22px',
      fontWeight: '800',
      color: '#f43f5e',
      textShadow: '0 4px 15px rgba(236,72,153,0.4)',
      letterSpacing: '-0.02em',
    },
    properties: {
      text: 'HORIZON SPECTRA',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 32,
      fontWeight: '800',
      color: '#ec4899',
      textShadow: '0 4px 15px rgba(236,72,153,0.4)',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 40,
    }
  },
  {
    id: 'ts-hero-3d-magenta-neon',
    name: '3D Synthwave Neon Title',
    category: 'Hero & Display',
    target: '3D Scene',
    sampleText: 'NEON WAVE 1984',
    description: '3D spatial text with electric magenta glow.',
    badge: '3D NEON',
    objectType: 'text',
    tags: ['3d', 'neon', 'magenta', 'synthwave'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '20px',
      fontWeight: '800',
      color: '#ec4899',
      textShadow: '0 0 12px #f472b6, 0 0 24px #be185d',
    },
    properties: {
      text: 'NEON WAVE 1984',
      color: '#ec4899',
      fontSize: 0.22,
      outlineColor: '#831843',
      outlineWidth: 0.02,
      textAlign: 'center',
    },
    position: [0, 1.5, 0]
  },
  {
    id: 'ts-hero-minimal-white',
    name: 'Minimalist Studio Header',
    category: 'Hero & Display',
    target: '2D HUD',
    sampleText: 'ARCHITECTURAL AR',
    description: 'Ultra-clean, tracked-out white minimalist title.',
    badge: 'MINIMAL',
    objectType: 'hudText',
    tags: ['hero', 'minimal', 'clean', 'white'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '18px',
      fontWeight: '600',
      color: '#ffffff',
      letterSpacing: '0.25em',
      textTransform: 'uppercase',
    },
    properties: {
      text: 'ARCHITECTURAL AR',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 24,
      fontWeight: '600',
      color: '#ffffff',
      letterSpacing: '0.25em',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 40,
    }
  },
  {
    id: 'ts-hero-emerald-cyber',
    name: 'Matrix Emerald Title',
    category: 'Hero & Display',
    target: '2D HUD',
    sampleText: 'QUANTUM DATA ENGINE',
    description: 'Monospaced emerald green terminal header with sharp contrast.',
    badge: 'MATRIX',
    objectType: 'hudText',
    tags: ['hero', 'matrix', 'green', 'mono'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '18px',
      fontWeight: '700',
      color: '#10b981',
      textShadow: '0 0 10px #34d399',
      letterSpacing: '0.05em',
    },
    properties: {
      text: 'QUANTUM DATA ENGINE',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 26,
      fontWeight: '700',
      color: '#10b981',
      textShadow: '0 0 10px #34d399',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-hero-3d-crystal-white',
    name: '3D Crystal White Title',
    category: 'Hero & Display',
    target: '3D Scene',
    sampleText: 'HOLOGRAM 3D',
    description: 'High contrast 3D white text for floating spatial titles.',
    badge: '3D CRYSTAL',
    objectType: 'text',
    tags: ['3d', 'white', 'crystal', 'title'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '20px',
      fontWeight: '800',
      color: '#ffffff',
      textShadow: '0 0 10px rgba(255,255,255,0.8)',
    },
    properties: {
      text: 'HOLOGRAM 3D',
      color: '#ffffff',
      fontSize: 0.24,
      outlineColor: '#020617',
      outlineWidth: 0.018,
      textAlign: 'center',
    },
    position: [0, 1.0, 0]
  },

  // ==========================================
  // 2. SUBTITLE & EYEBROWS (10 PRESETS)
  // ==========================================
  {
    id: 'ts-sub-eyebrow-tracked',
    name: 'Tracked Monospace Eyebrow',
    category: 'Subtitle & Eyebrows',
    target: '2D HUD',
    sampleText: '/// SYSTEM TELEMETRY v4.2',
    description: 'Subtle tracked monospace eyebrow label above titles.',
    badge: 'EYEBROW',
    objectType: 'hudText',
    tags: ['subtitle', 'eyebrow', 'mono', 'small'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '12px',
      fontWeight: '600',
      color: '#38bdf8',
      letterSpacing: '0.18em',
      textTransform: 'uppercase',
    },
    properties: {
      text: '/// SYSTEM TELEMETRY v4.2',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 13,
      fontWeight: '600',
      color: '#38bdf8',
      letterSpacing: '0.18em',
      alignment: 'top-left',
      offsetX: 40,
      offsetY: 25,
    }
  },
  {
    id: 'ts-sub-muted-gray',
    name: 'Muted Slate Subtitle',
    category: 'Subtitle & Eyebrows',
    target: '2D HUD',
    sampleText: 'Real-time spatial tracking & object occlusion active',
    description: 'Clean slate gray descriptive body subtitle.',
    badge: 'SUBTITLE',
    objectType: 'hudText',
    tags: ['subtitle', 'slate', 'description', 'clean'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '13px',
      fontWeight: '500',
      color: '#94a3b8',
    },
    properties: {
      text: 'Real-time spatial tracking & object occlusion active',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 15,
      fontWeight: '500',
      color: '#94a3b8',
      alignment: 'top-left',
      offsetX: 40,
      offsetY: 80,
    }
  },
  {
    id: 'ts-sub-pill-badge',
    name: 'Pill Label Eyebrow',
    category: 'Subtitle & Eyebrows',
    target: '2D HUD',
    sampleText: 'FEATURED AR MODEL',
    description: 'Pill badge backdrop with tracked accent text.',
    badge: 'BADGE',
    objectType: 'hudText',
    tags: ['subtitle', 'pill', 'badge', 'accent'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '11px',
      fontWeight: '700',
      color: '#a855f7',
      background: 'rgba(168,85,247,0.15)',
      border: '1px solid rgba(168,85,247,0.3)',
      borderRadius: '20px',
      padding: '4px 12px',
      letterSpacing: '0.1em',
    },
    properties: {
      text: 'FEATURED AR MODEL',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 12,
      fontWeight: '700',
      color: '#a855f7',
      backgroundColor: 'rgba(168,85,247,0.15)',
      border: '1px solid rgba(168,85,247,0.3)',
      borderRadius: '20px',
      padding: '6px 14px',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-sub-3d-cyan-label',
    name: '3D Spatial Cyan Subtitle',
    category: 'Subtitle & Eyebrows',
    target: '3D Scene',
    sampleText: 'Target Position: [X: 0.2, Y: 1.4, Z: -0.8]',
    description: '3D monospaced subtitle label for spatial coordinates.',
    badge: '3D SUBTITLE',
    objectType: 'text',
    tags: ['3d', 'subtitle', 'cyan', 'mono'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '13px',
      fontWeight: '600',
      color: '#38bdf8',
    },
    properties: {
      text: 'Target Position: [X: 0.2, Y: 1.4, Z: -0.8]',
      color: '#38bdf8',
      fontSize: 0.12,
      outlineColor: '#0c4a6e',
      outlineWidth: 0.01,
      textAlign: 'center',
    },
    position: [0, 0.9, 0]
  },
  {
    id: 'ts-sub-emerald-status',
    name: 'Live Emerald Status Subtitle',
    category: 'Subtitle & Eyebrows',
    target: '2D HUD',
    sampleText: '● LIVE STREAMING TO CLOUD',
    description: 'Live indicator subtitle with pulsating emerald theme.',
    badge: 'STATUS',
    objectType: 'hudText',
    tags: ['subtitle', 'live', 'emerald', 'status'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '12px',
      fontWeight: '700',
      color: '#22c55e',
      letterSpacing: '0.08em',
    },
    properties: {
      text: '● LIVE STREAMING TO CLOUD',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 13,
      fontWeight: '700',
      color: '#22c55e',
      letterSpacing: '0.08em',
      alignment: 'top-right',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-sub-gold-caption',
    name: 'Golden Accent Subcaption',
    category: 'Subtitle & Eyebrows',
    target: '2D HUD',
    sampleText: 'PREMIUM AR EXPERIENCE',
    description: 'Warm golden tracked caption label.',
    badge: 'GOLD',
    objectType: 'hudText',
    tags: ['subtitle', 'gold', 'caption', 'luxury'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '11px',
      fontWeight: '700',
      color: '#f59e0b',
      letterSpacing: '0.15em',
    },
    properties: {
      text: 'PREMIUM AR EXPERIENCE',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 12,
      fontWeight: '700',
      color: '#f59e0b',
      letterSpacing: '0.15em',
      alignment: 'top-left',
      offsetX: 40,
      offsetY: 20,
    }
  },
  {
    id: 'ts-sub-coral-alert',
    name: 'Coral Warning Eyebrow',
    category: 'Subtitle & Eyebrows',
    target: '2D HUD',
    sampleText: '⚠️ LOW LIGHTING DETECTED',
    description: 'Warning notice subtitle in warm coral amber.',
    badge: 'WARNING',
    objectType: 'hudText',
    tags: ['subtitle', 'warning', 'coral', 'alert'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '12px',
      fontWeight: '700',
      color: '#f97316',
      background: 'rgba(249,115,22,0.12)',
      border: '1px solid rgba(249,115,22,0.3)',
      borderRadius: '8px',
      padding: '4px 10px',
    },
    properties: {
      text: '⚠️ LOW LIGHTING DETECTED',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 13,
      fontWeight: '700',
      color: '#f97316',
      backgroundColor: 'rgba(249,115,22,0.12)',
      border: '1px solid rgba(249,115,22,0.3)',
      borderRadius: '8px',
      padding: '6px 12px',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 20,
    }
  },
  {
    id: 'ts-sub-3d-purple-glow',
    name: '3D Spatial Purple Subtitle',
    category: 'Subtitle & Eyebrows',
    target: '3D Scene',
    sampleText: 'Layer 02 - Mesh Geometry',
    description: '3D purple glowing annotation subtitle.',
    badge: '3D PURPLE',
    objectType: 'text',
    tags: ['3d', 'subtitle', 'purple', 'annotation'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '13px',
      fontWeight: '600',
      color: '#c084fc',
      textShadow: '0 0 8px #a855f7',
    },
    properties: {
      text: 'Layer 02 - Mesh Geometry',
      color: '#c084fc',
      fontSize: 0.11,
      outlineColor: '#581c87',
      outlineWidth: 0.01,
      textAlign: 'center',
    },
    position: [0, 0.7, 0]
  },
  {
    id: 'ts-sub-author-byline',
    name: 'Designer Byline Subtext',
    category: 'Subtitle & Eyebrows',
    target: '2D HUD',
    sampleText: 'Created by Spatial Studio Labs',
    description: 'Elegant italicized design credit byline.',
    badge: 'BYLINE',
    objectType: 'hudText',
    tags: ['subtitle', 'byline', 'author', 'credit'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '12px',
      fontWeight: '500',
      color: '#cbd5e1',
      fontStyle: 'italic',
    },
    properties: {
      text: 'Created by Spatial Studio Labs',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 14,
      fontWeight: '500',
      color: '#cbd5e1',
      alignment: 'bottom-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-sub-mono-timestamp',
    name: 'Monospace Time & Location',
    category: 'Subtitle & Eyebrows',
    target: '2D HUD',
    sampleText: 'TIMESTAMP: 14:32:09 UTC // LAT: 37.7749° N',
    description: 'Technical monospaced timestamp and coordinate label.',
    badge: 'TIME',
    objectType: 'hudText',
    tags: ['subtitle', 'time', 'gps', 'mono'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '11px',
      fontWeight: '500',
      color: '#64748b',
    },
    properties: {
      text: 'TIMESTAMP: 14:32:09 UTC // LAT: 37.7749° N',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 12,
      fontWeight: '500',
      color: '#64748b',
      alignment: 'bottom-right',
      offsetX: 30,
      offsetY: 30,
    }
  },

  // ==========================================
  // 3. CYBER & NEON (10 PRESETS)
  // ==========================================
  {
    id: 'ts-neon-electric-pink',
    name: 'Electric Pink Neon Tube',
    category: 'Cyber & Neon',
    target: '2D HUD',
    sampleText: 'CYBER CITY 2077',
    description: 'Vibrant electric pink glowing tube neon header.',
    badge: 'NEON PINK',
    objectType: 'hudText',
    tags: ['cyber', 'neon', 'pink', 'glow'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '20px',
      fontWeight: '800',
      color: '#f472b6',
      textShadow: '0 0 5px #fff, 0 0 10px #ec4899, 0 0 20px #be185d, 0 0 40px #831843',
    },
    properties: {
      text: 'CYBER CITY 2077',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 28,
      fontWeight: '800',
      color: '#f472b6',
      textShadow: '0 0 5px #fff, 0 0 10px #ec4899, 0 0 20px #be185d, 0 0 40px #831843',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 40,
    }
  },
  {
    id: 'ts-neon-laser-green',
    name: 'Laser Emerald Terminal',
    category: 'Cyber & Neon',
    target: '2D HUD',
    sampleText: '> SYSTEM OVERRIDE INITIATED',
    description: 'Hacker terminal command text with laser green glow.',
    badge: 'LASER GREEN',
    objectType: 'hudText',
    tags: ['cyber', 'green', 'hacker', 'terminal'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '15px',
      fontWeight: '700',
      color: '#4ade80',
      textShadow: '0 0 8px #22c55e, 0 0 16px #15803d',
    },
    properties: {
      text: '> SYSTEM OVERRIDE INITIATED',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 20,
      fontWeight: '700',
      color: '#4ade80',
      textShadow: '0 0 8px #22c55e, 0 0 16px #15803d',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-neon-3d-cyan-sign',
    name: '3D Cyber Cyan Floating Sign',
    category: 'Cyber & Neon',
    target: '3D Scene',
    sampleText: 'AR PORTAL 01',
    description: '3D floating spatial cyber sign with cyan laser aura.',
    badge: '3D CYBER',
    objectType: 'text',
    tags: ['3d', 'cyber', 'cyan', 'sign'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '18px',
      fontWeight: '800',
      color: '#06b6d4',
      textShadow: '0 0 10px #22d3ee, 0 0 20px #0891b2',
    },
    properties: {
      text: 'AR PORTAL 01',
      color: '#06b6d4',
      fontSize: 0.22,
      outlineColor: '#164e63',
      outlineWidth: 0.02,
      textAlign: 'center',
    },
    position: [0, 1.4, 0]
  },
  {
    id: 'ts-neon-toxic-yellow',
    name: 'Toxic Yellow Voltage Header',
    category: 'Cyber & Neon',
    target: '2D HUD',
    sampleText: '⚡ HIGH VOLTAGE 5000V',
    description: 'Luminous toxic yellow energy warning label.',
    badge: 'VOLTAGE',
    objectType: 'hudText',
    tags: ['cyber', 'yellow', 'warning', 'voltage'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '16px',
      fontWeight: '800',
      color: '#facc15',
      textShadow: '0 0 10px #eab308, 0 0 20px #a16207',
    },
    properties: {
      text: '⚡ HIGH VOLTAGE 5000V',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 22,
      fontWeight: '800',
      color: '#facc15',
      textShadow: '0 0 10px #eab308, 0 0 20px #a16207',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-neon-plasma-purple',
    name: 'Plasma Purple Cyber Header',
    category: 'Cyber & Neon',
    target: '2D HUD',
    sampleText: 'SYNTHETIC CORE LINK',
    description: 'Deep plasma purple neon header with intense aura.',
    badge: 'PLASMA',
    objectType: 'hudText',
    tags: ['cyber', 'purple', 'plasma', 'glow'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '18px',
      fontWeight: '800',
      color: '#c084fc',
      textShadow: '0 0 10px #a855f7, 0 0 20px #7e22ce',
    },
    properties: {
      text: 'SYNTHETIC CORE LINK',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 26,
      fontWeight: '800',
      color: '#c084fc',
      textShadow: '0 0 10px #a855f7, 0 0 20px #7e22ce',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 40,
    }
  },
  {
    id: 'ts-neon-glitch-red',
    name: 'Red Alert Cyber Glitch',
    category: 'Cyber & Neon',
    target: '2D HUD',
    sampleText: '[ CRITICAL FAILURE 0x88 ]',
    description: 'Red neon alert glitch text style for warning states.',
    badge: 'ALERT',
    objectType: 'hudText',
    tags: ['cyber', 'red', 'alert', 'glitch'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '15px',
      fontWeight: '700',
      color: '#f43f5e',
      textShadow: '0 0 8px #e11d48, 0 0 16px #9f1239',
      background: 'rgba(244,63,94,0.1)',
      border: '1px solid rgba(244,63,94,0.4)',
      padding: '6px 12px',
      borderRadius: '6px',
    },
    properties: {
      text: '[ CRITICAL FAILURE 0x88 ]',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 18,
      fontWeight: '700',
      color: '#f43f5e',
      textShadow: '0 0 8px #e11d48, 0 0 16px #9f1239',
      backgroundColor: 'rgba(244,63,94,0.1)',
      border: '1px solid rgba(244,63,94,0.4)',
      borderRadius: '8px',
      padding: '8px 16px',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 30,
    }
  },
  {
    id: 'ts-neon-3d-amber-flame',
    name: '3D Solar Amber Flame',
    category: 'Cyber & Neon',
    target: '3D Scene',
    sampleText: 'SOLAR POWER 100%',
    description: '3D amber neon header with intense solar illumination.',
    badge: '3D AMBER',
    objectType: 'text',
    tags: ['3d', 'amber', 'solar', 'neon'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '18px',
      fontWeight: '800',
      color: '#f59e0b',
      textShadow: '0 0 12px #fbbf24, 0 0 24px #d97706',
    },
    properties: {
      text: 'SOLAR POWER 100%',
      color: '#f59e0b',
      fontSize: 0.2,
      outlineColor: '#78350f',
      outlineWidth: 0.018,
      textAlign: 'center',
    },
    position: [0, 1.1, 0]
  },
  {
    id: 'ts-neon-hud-grid-blue',
    name: 'HUD Grid Electric Blue',
    category: 'Cyber & Neon',
    target: '2D HUD',
    sampleText: 'TARGET LOCK: ACQUIRED',
    description: 'Electric blue target lock HUD label.',
    badge: 'LOCK',
    objectType: 'hudText',
    tags: ['cyber', 'hud', 'blue', 'lock'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '14px',
      fontWeight: '700',
      color: '#38bdf8',
      textShadow: '0 0 8px #0284c7',
      letterSpacing: '0.1em',
    },
    properties: {
      text: 'TARGET LOCK: ACQUIRED',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 16,
      fontWeight: '700',
      color: '#38bdf8',
      textShadow: '0 0 8px #0284c7',
      letterSpacing: '0.1em',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-neon-cyber-badge',
    name: 'Cyberpunk Badge Tag',
    category: 'Cyber & Neon',
    target: '2D HUD',
    sampleText: 'STATUS: OPERATIONAL',
    description: 'Dark box badge with luminous neon border.',
    badge: 'CYBER TAG',
    objectType: 'hudText',
    tags: ['cyber', 'badge', 'border', 'tag'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '12px',
      fontWeight: '700',
      color: '#22d3ee',
      background: 'rgba(15, 23, 42, 0.9)',
      border: '1.5px solid #06b6d4',
      borderRadius: '6px',
      padding: '4px 10px',
      boxShadow: '0 0 10px rgba(6,182,212,0.4)',
    },
    properties: {
      text: 'STATUS: OPERATIONAL',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 13,
      fontWeight: '700',
      color: '#22d3ee',
      backgroundColor: 'rgba(15, 23, 42, 0.9)',
      border: '1.5px solid #06b6d4',
      borderRadius: '6px',
      padding: '6px 14px',
      alignment: 'top-right',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-neon-3d-violet-laser',
    name: '3D Violet Laser Title',
    category: 'Cyber & Neon',
    target: '3D Scene',
    sampleText: 'HYPERDRIVE AR',
    description: '3D floating text with radiant violet neon outline.',
    badge: '3D VIOLET',
    objectType: 'text',
    tags: ['3d', 'violet', 'laser', 'neon'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '18px',
      fontWeight: '800',
      color: '#a855f7',
      textShadow: '0 0 10px #c084fc, 0 0 20px #6b21a8',
    },
    properties: {
      text: 'HYPERDRIVE AR',
      color: '#a855f7',
      fontSize: 0.22,
      outlineColor: '#3b0764',
      outlineWidth: 0.02,
      textAlign: 'center',
    },
    position: [0, 1.3, 0]
  },

  // ==========================================
  // 4. GLASS & HOLOGRAPHIC (10 PRESETS)
  // ==========================================
  {
    id: 'ts-glass-pill-title',
    name: 'Glassmorphism Pill Title',
    category: 'Glass & Holographic',
    target: '2D HUD',
    sampleText: 'SPATIAL INSIGHTS',
    description: 'Soft translucent glass pill title with frosted blur.',
    badge: 'GLASS PILL',
    objectType: 'hudText',
    tags: ['glass', 'pill', 'translucent', 'frosted'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '16px',
      fontWeight: '700',
      color: '#ffffff',
      background: 'rgba(255, 255, 255, 0.12)',
      border: '1px solid rgba(255, 255, 255, 0.25)',
      borderRadius: '24px',
      padding: '8px 20px',
      backdropFilter: 'blur(16px)',
      boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
    },
    properties: {
      text: 'SPATIAL INSIGHTS',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 22,
      fontWeight: '700',
      color: '#ffffff',
      backgroundColor: 'rgba(255, 255, 255, 0.12)',
      border: '1px solid rgba(255, 255, 255, 0.25)',
      borderRadius: '30px',
      padding: '10px 24px',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-glass-hologram-cyan',
    name: 'Holographic Translucent Cyan',
    category: 'Glass & Holographic',
    target: '2D HUD',
    sampleText: 'HOLO LINK // ONLINE',
    description: 'Holographic blue frosted glass banner with subtle shimmer.',
    badge: 'HOLO CYAN',
    objectType: 'hudText',
    tags: ['glass', 'hologram', 'cyan', 'shimmer'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '15px',
      fontWeight: '700',
      color: '#e0f2fe',
      background: 'rgba(14, 165, 233, 0.15)',
      border: '1px solid rgba(56, 189, 248, 0.3)',
      borderRadius: '12px',
      padding: '6px 14px',
      boxShadow: '0 0 15px rgba(56, 189, 248, 0.2)',
    },
    properties: {
      text: 'HOLO LINK // ONLINE',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 18,
      fontWeight: '700',
      color: '#e0f2fe',
      backgroundColor: 'rgba(14, 165, 233, 0.15)',
      border: '1px solid rgba(56, 189, 248, 0.3)',
      borderRadius: '14px',
      padding: '8px 18px',
      alignment: 'top-right',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-glass-3d-hologram-plate',
    name: '3D Holographic Spatial Plate',
    category: 'Glass & Holographic',
    target: '3D Scene',
    sampleText: 'SPATIAL ANCHOR 01',
    description: '3D text plate for floating holographic anchor markers.',
    badge: '3D HOLO',
    objectType: 'text',
    tags: ['3d', 'hologram', 'plate', 'anchor'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '18px',
      fontWeight: '700',
      color: '#38bdf8',
      textShadow: '0 0 10px #7dd3fc',
    },
    properties: {
      text: 'SPATIAL ANCHOR 01',
      color: '#38bdf8',
      fontSize: 0.18,
      outlineColor: '#075985',
      outlineWidth: 0.015,
      textAlign: 'center',
    },
    position: [0, 1.0, 0]
  },
  {
    id: 'ts-glass-rose-translucent',
    name: 'Rose Frosted Glass Card',
    category: 'Glass & Holographic',
    target: '2D HUD',
    sampleText: 'MAGENTA GLASS',
    description: 'Rose-tinted translucent glass label with soft border.',
    badge: 'ROSE GLASS',
    objectType: 'hudText',
    tags: ['glass', 'rose', 'pink', 'frosted'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '16px',
      fontWeight: '700',
      color: '#fce7f3',
      background: 'rgba(236, 72, 153, 0.15)',
      border: '1px solid rgba(244, 114, 182, 0.3)',
      borderRadius: '16px',
      padding: '8px 16px',
    },
    properties: {
      text: 'MAGENTA GLASS',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 20,
      fontWeight: '700',
      color: '#fce7f3',
      backgroundColor: 'rgba(236, 72, 153, 0.15)',
      border: '1px solid rgba(244, 114, 182, 0.3)',
      borderRadius: '18px',
      padding: '10px 20px',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-glass-dark-obsidian',
    name: 'Dark Obsidian Glass Plaque',
    category: 'Glass & Holographic',
    target: '2D HUD',
    sampleText: 'OBSIDIAN HUD PANEL',
    description: 'Dark obsidian glass backdrop with white typography.',
    badge: 'OBSIDIAN',
    objectType: 'hudText',
    tags: ['glass', 'obsidian', 'dark', 'panel'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '16px',
      fontWeight: '700',
      color: '#f8fafc',
      background: 'rgba(15, 23, 42, 0.85)',
      border: '1px solid rgba(255, 255, 255, 0.15)',
      borderRadius: '14px',
      padding: '8px 16px',
      boxShadow: '0 10px 30px rgba(0, 0, 0, 0.5)',
    },
    properties: {
      text: 'OBSIDIAN HUD PANEL',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 22,
      fontWeight: '700',
      color: '#f8fafc',
      backgroundColor: 'rgba(15, 23, 42, 0.85)',
      border: '1px solid rgba(255, 255, 255, 0.15)',
      borderRadius: '16px',
      padding: '10px 22px',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-glass-emerald-crystal',
    name: 'Emerald Crystal Translucent',
    category: 'Glass & Holographic',
    target: '2D HUD',
    sampleText: 'VERDANT GLASS',
    description: 'Emerald crystal translucent label with subtle green glow.',
    badge: 'EMERALD',
    objectType: 'hudText',
    tags: ['glass', 'emerald', 'green', 'crystal'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '16px',
      fontWeight: '700',
      color: '#d1fae5',
      background: 'rgba(16, 185, 129, 0.15)',
      border: '1px solid rgba(52, 211, 153, 0.3)',
      borderRadius: '14px',
      padding: '8px 16px',
    },
    properties: {
      text: 'VERDANT GLASS',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 20,
      fontWeight: '700',
      color: '#d1fae5',
      backgroundColor: 'rgba(16, 185, 129, 0.15)',
      border: '1px solid rgba(52, 211, 153, 0.3)',
      borderRadius: '16px',
      padding: '10px 20px',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-glass-3d-prism-text',
    name: '3D Iridescent Prism Text',
    category: 'Glass & Holographic',
    target: '3D Scene',
    sampleText: 'PRISM REFRACTION 3D',
    description: '3D floating text with prism refraction aura.',
    badge: '3D PRISM',
    objectType: 'text',
    tags: ['3d', 'prism', 'iridescent', 'glass'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '18px',
      fontWeight: '800',
      color: '#f0f9ff',
      textShadow: '0 0 10px #38bdf8, 0 0 20px #e0e7ff',
    },
    properties: {
      text: 'PRISM REFRACTION 3D',
      color: '#f0f9ff',
      fontSize: 0.22,
      outlineColor: '#0369a1',
      outlineWidth: 0.018,
      textAlign: 'center',
    },
    position: [0, 1.2, 0]
  },
  {
    id: 'ts-glass-minimal-frost',
    name: 'Minimal Frosted Strip',
    category: 'Glass & Holographic',
    target: '2D HUD',
    sampleText: 'SPATIAL CAMERA ACTIVE',
    description: 'Subtle long frosted glass strip banner.',
    badge: 'FROST STRIP',
    objectType: 'hudText',
    tags: ['glass', 'strip', 'minimal', 'banner'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '13px',
      fontWeight: '600',
      color: '#ffffff',
      background: 'rgba(255, 255, 255, 0.08)',
      border: '1px solid rgba(255, 255, 255, 0.15)',
      borderRadius: '8px',
      padding: '6px 14px',
    },
    properties: {
      text: 'SPATIAL CAMERA ACTIVE',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 15,
      fontWeight: '600',
      color: '#ffffff',
      backgroundColor: 'rgba(255, 255, 255, 0.08)',
      border: '1px solid rgba(255, 255, 255, 0.15)',
      borderRadius: '10px',
      padding: '8px 18px',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 20,
    }
  },
  {
    id: 'ts-glass-golden-amber',
    name: 'Amber Solar Glass Plaque',
    category: 'Glass & Holographic',
    target: '2D HUD',
    sampleText: 'SOLAR ENERGY HARVEST',
    description: 'Golden translucent glass plaque with warm tone.',
    badge: 'AMBER GLASS',
    objectType: 'hudText',
    tags: ['glass', 'amber', 'gold', 'warm'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '15px',
      fontWeight: '700',
      color: '#fef3c7',
      background: 'rgba(245, 158, 11, 0.15)',
      border: '1px solid rgba(251, 191, 36, 0.3)',
      borderRadius: '14px',
      padding: '8px 16px',
    },
    properties: {
      text: 'SOLAR ENERGY HARVEST',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 18,
      fontWeight: '700',
      color: '#fef3c7',
      backgroundColor: 'rgba(245, 158, 11, 0.15)',
      border: '1px solid rgba(251, 191, 36, 0.3)',
      borderRadius: '16px',
      padding: '10px 20px',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-glass-3d-violet-holo',
    name: '3D Violet Hologram Label',
    category: 'Glass & Holographic',
    target: '3D Scene',
    sampleText: 'QUANTUM DATA NODE',
    description: '3D violet holographic text with soft purple aura.',
    badge: '3D VIOLET',
    objectType: 'text',
    tags: ['3d', 'violet', 'hologram', 'node'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '18px',
      fontWeight: '800',
      color: '#e9d5ff',
      textShadow: '0 0 10px #c084fc',
    },
    properties: {
      text: 'QUANTUM DATA NODE',
      color: '#e9d5ff',
      fontSize: 0.2,
      outlineColor: '#6b21a8',
      outlineWidth: 0.015,
      textAlign: 'center',
    },
    position: [0, 1.1, 0]
  },

  // ==========================================
  // 5. CTA & BUTTONS (10 PRESETS)
  // ==========================================
  {
    id: 'ts-cta-gradient-blue',
    name: 'Gradient Cyan CTA Button',
    category: 'CTA & Buttons',
    target: '2D HUD',
    sampleText: 'LAUNCH AR EXPERIENCE',
    description: 'Vibrant cyan gradient interactive CTA button.',
    badge: 'CTA BUTTON',
    objectType: 'hudButton',
    tags: ['cta', 'button', 'cyan', 'interactive'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '14px',
      fontWeight: '700',
      color: '#0f172a',
      background: 'linear-gradient(135deg, #38bdf8 0%, #2563eb 100%)',
      borderRadius: '14px',
      padding: '10px 20px',
      boxShadow: '0 8px 24px rgba(56, 189, 248, 0.3)',
    },
    properties: {
      text: 'LAUNCH AR EXPERIENCE',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 15,
      fontWeight: '700',
      color: '#ffffff',
      backgroundColor: '#2563eb',
      border: '1px solid rgba(255,255,255,0.2)',
      borderRadius: '14px',
      padding: '12px 24px',
      alignment: 'bottom-center',
      offsetX: 0,
      offsetY: 40,
    }
  },
  {
    id: 'ts-cta-neon-magenta-pill',
    name: 'Neon Magenta Pill Button',
    category: 'CTA & Buttons',
    target: '2D HUD',
    sampleText: 'SHOP IN AR NOW',
    description: 'Pill-shaped neon magenta shopping call-to-action button.',
    badge: 'SHOP CTA',
    objectType: 'hudButton',
    tags: ['cta', 'magenta', 'pill', 'shop'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '13px',
      fontWeight: '800',
      color: '#ffffff',
      background: 'linear-gradient(135deg, #ec4899 0%, #be185d 100%)',
      borderRadius: '30px',
      padding: '8px 22px',
      boxShadow: '0 8px 20px rgba(236, 72, 153, 0.4)',
    },
    properties: {
      text: 'SHOP IN AR NOW',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 14,
      fontWeight: '800',
      color: '#ffffff',
      backgroundColor: '#ec4899',
      borderRadius: '30px',
      padding: '10px 26px',
      alignment: 'bottom-right',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-cta-3d-spatial-button',
    name: '3D Spatial Glass Button',
    category: 'CTA & Buttons',
    target: '3D Scene',
    sampleText: 'ENTER 3D PORTAL',
    description: 'Interactive 3D spatial floating action button.',
    badge: '3D BUTTON',
    objectType: 'button',
    tags: ['3d', 'button', 'cta', 'spatial'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '15px',
      fontWeight: '700',
      color: '#ffffff',
      background: '#0284c7',
      borderRadius: '12px',
      padding: '8px 18px',
    },
    properties: {
      text: 'ENTER 3D PORTAL',
      color: '#0284c7',
      textColor: '#ffffff',
      url: '#',
    },
    scale: [1, 0.35, 0.05],
    position: [0, 0.3, 0.1]
  },
  {
    id: 'ts-cta-emerald-start',
    name: 'Emerald Start Trigger',
    category: 'CTA & Buttons',
    target: '2D HUD',
    sampleText: '▶ BEGIN AR SCAN',
    description: 'Emerald green action trigger button.',
    badge: 'START',
    objectType: 'hudButton',
    tags: ['cta', 'emerald', 'green', 'start'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '13px',
      fontWeight: '700',
      color: '#022c22',
      background: 'linear-gradient(135deg, #34d399 0%, #059669 100%)',
      borderRadius: '12px',
      padding: '8px 18px',
      boxShadow: '0 8px 20px rgba(16, 185, 129, 0.3)',
    },
    properties: {
      text: '▶ BEGIN AR SCAN',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 14,
      fontWeight: '700',
      color: '#ffffff',
      backgroundColor: '#059669',
      borderRadius: '12px',
      padding: '10px 20px',
      alignment: 'bottom-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-cta-dark-minimal-pill',
    name: 'Dark Minimalist Action Pill',
    category: 'CTA & Buttons',
    target: '2D HUD',
    sampleText: 'EXPLORE MODEL →',
    description: 'Sleek dark minimalist pill button with white text.',
    badge: 'DARK PILL',
    objectType: 'hudButton',
    tags: ['cta', 'dark', 'minimal', 'pill'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '13px',
      fontWeight: '600',
      color: '#ffffff',
      background: 'rgba(15, 23, 42, 0.9)',
      border: '1px solid rgba(255, 255, 255, 0.2)',
      borderRadius: '24px',
      padding: '8px 18px',
    },
    properties: {
      text: 'EXPLORE MODEL →',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 14,
      fontWeight: '600',
      color: '#ffffff',
      backgroundColor: 'rgba(15, 23, 42, 0.9)',
      border: '1px solid rgba(255, 255, 255, 0.2)',
      borderRadius: '24px',
      padding: '10px 22px',
      alignment: 'bottom-center',
      offsetX: 0,
      offsetY: 30,
    }
  },
  {
    id: 'ts-cta-amber-buy-now',
    name: 'Amber Gold Checkout CTA',
    category: 'CTA & Buttons',
    target: '2D HUD',
    sampleText: '⚡ BUY NOW - $199',
    description: 'Golden checkout conversion CTA button.',
    badge: 'BUY CTA',
    objectType: 'hudButton',
    tags: ['cta', 'buy', 'gold', 'checkout'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '14px',
      fontWeight: '800',
      color: '#78350f',
      background: 'linear-gradient(135deg, #fde047 0%, #d97706 100%)',
      borderRadius: '12px',
      padding: '10px 20px',
      boxShadow: '0 8px 20px rgba(217, 119, 6, 0.35)',
    },
    properties: {
      text: '⚡ BUY NOW - $199',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 15,
      fontWeight: '800',
      color: '#78350f',
      backgroundColor: '#f59e0b',
      borderRadius: '12px',
      padding: '12px 24px',
      alignment: 'bottom-right',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-cta-3d-red-alert-button',
    name: '3D Red Emergency Trigger',
    category: 'CTA & Buttons',
    target: '3D Scene',
    sampleText: 'STOP RECORDING',
    description: '3D spatial red emergency stop button.',
    badge: '3D STOP',
    objectType: 'button',
    tags: ['3d', 'button', 'red', 'stop'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '14px',
      fontWeight: '700',
      color: '#ffffff',
      background: '#e11d48',
      borderRadius: '10px',
      padding: '8px 16px',
    },
    properties: {
      text: 'STOP RECORDING',
      color: '#e11d48',
      textColor: '#ffffff',
      url: '#',
    },
    scale: [1, 0.35, 0.05],
    position: [0, 0.2, 0]
  },
  {
    id: 'ts-cta-ghost-white-outline',
    name: 'Ghost White Outline Button',
    category: 'CTA & Buttons',
    target: '2D HUD',
    sampleText: 'VIEW SPECIFICATIONS',
    description: 'Translucent ghost button with white outline.',
    badge: 'GHOST',
    objectType: 'hudButton',
    tags: ['cta', 'ghost', 'outline', 'white'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '13px',
      fontWeight: '600',
      color: '#ffffff',
      background: 'transparent',
      border: '1.5px solid #ffffff',
      borderRadius: '12px',
      padding: '8px 18px',
    },
    properties: {
      text: 'VIEW SPECIFICATIONS',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 14,
      fontWeight: '600',
      color: '#ffffff',
      backgroundColor: 'transparent',
      border: '1.5px solid #ffffff',
      borderRadius: '12px',
      padding: '10px 20px',
      alignment: 'bottom-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-cta-purple-violet-glow',
    name: 'Violet Glow Trigger Button',
    category: 'CTA & Buttons',
    target: '2D HUD',
    sampleText: 'CONNECT SPATIAL AUDIO',
    description: 'Purple violet glowing audio trigger button.',
    badge: 'AUDIO CTA',
    objectType: 'hudButton',
    tags: ['cta', 'purple', 'audio', 'glow'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '13px',
      fontWeight: '700',
      color: '#ffffff',
      background: 'linear-gradient(135deg, #a855f7 0%, #6b21a8 100%)',
      borderRadius: '14px',
      padding: '8px 18px',
      boxShadow: '0 8px 24px rgba(168, 85, 247, 0.4)',
    },
    properties: {
      text: 'CONNECT SPATIAL AUDIO',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 14,
      fontWeight: '700',
      color: '#ffffff',
      backgroundColor: '#8b5cf6',
      borderRadius: '14px',
      padding: '10px 22px',
      alignment: 'bottom-center',
      offsetX: 0,
      offsetY: 30,
    }
  },
  {
    id: 'ts-cta-cyan-square-btn',
    name: 'Cyberpunk Compact Action Button',
    category: 'CTA & Buttons',
    target: '2D HUD',
    sampleText: 'CALIBRATE',
    description: 'Compact cyber squared action button.',
    badge: 'COMPACT',
    objectType: 'hudButton',
    tags: ['cta', 'compact', 'cyber', 'button'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '12px',
      fontWeight: '800',
      color: '#0891b2',
      background: '#cffaff',
      border: '1px solid #06b6d4',
      borderRadius: '6px',
      padding: '6px 14px',
    },
    properties: {
      text: 'CALIBRATE',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 13,
      fontWeight: '800',
      color: '#0891b2',
      backgroundColor: '#cffaff',
      border: '1px solid #06b6d4',
      borderRadius: '6px',
      padding: '8px 16px',
      alignment: 'top-right',
      offsetX: 30,
      offsetY: 30,
    }
  },

  // ==========================================
  // 6. AR TELEMETRY & METRICS (10 PRESETS)
  // ==========================================
  {
    id: 'ts-metric-fps-counter',
    name: 'FPS & Refresh Rate Meter',
    category: 'AR Telemetry & Metrics',
    target: '2D HUD',
    sampleText: '90.2 FPS // 11.1 ms',
    description: 'Monospaced framerate counter for AR performance debugging.',
    badge: 'FPS METER',
    objectType: 'hudText',
    tags: ['metric', 'fps', 'telemetry', 'mono'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '14px',
      fontWeight: '800',
      color: '#22c55e',
      background: 'rgba(0,0,0,0.8)',
      border: '1px solid rgba(34,197,94,0.4)',
      padding: '4px 10px',
      borderRadius: '6px',
    },
    properties: {
      text: '90.2 FPS // 11.1 ms',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 15,
      fontWeight: '800',
      color: '#22c55e',
      backgroundColor: 'rgba(0,0,0,0.8)',
      border: '1px solid rgba(34,197,94,0.4)',
      borderRadius: '6px',
      padding: '6px 12px',
      alignment: 'top-right',
      offsetX: 20,
      offsetY: 20,
    }
  },
  {
    id: 'ts-metric-battery-status',
    name: 'Battery Level Telemetry',
    category: 'AR Telemetry & Metrics',
    target: '2D HUD',
    sampleText: '🔋 BATTERY: 88% (3h 40m remaining)',
    description: 'Battery percentage and remaining time HUD readout.',
    badge: 'BATTERY',
    objectType: 'hudText',
    tags: ['metric', 'battery', 'telemetry', 'hud'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '12px',
      fontWeight: '700',
      color: '#38bdf8',
    },
    properties: {
      text: '🔋 BATTERY: 88% (3h 40m remaining)',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 13,
      fontWeight: '700',
      color: '#38bdf8',
      alignment: 'top-right',
      offsetX: 20,
      offsetY: 55,
    }
  },
  {
    id: 'ts-metric-3d-coordinate-display',
    name: '3D Spatial Coordinate Label',
    category: 'AR Telemetry & Metrics',
    target: '3D Scene',
    sampleText: 'X: +1.24  Y: +0.82  Z: -2.10',
    description: '3D floating spatial vector coordinates text readout.',
    badge: '3D METRIC',
    objectType: 'text',
    tags: ['3d', 'metric', 'coordinates', 'vector'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '14px',
      fontWeight: '700',
      color: '#38bdf8',
    },
    properties: {
      text: 'X: +1.24  Y: +0.82  Z: -2.10',
      color: '#38bdf8',
      fontSize: 0.12,
      outlineColor: '#0c4a6e',
      outlineWidth: 0.01,
      textAlign: 'center',
    },
    position: [0, 0.5, 0]
  },
  {
    id: 'ts-metric-distance-meter',
    name: 'Distance to Target Meter',
    category: 'AR Telemetry & Metrics',
    target: '2D HUD',
    sampleText: 'RANGE TO TARGET: 14.8 m',
    description: 'Distance measurement readout for target markers.',
    badge: 'RANGE',
    objectType: 'hudText',
    tags: ['metric', 'distance', 'range', 'meter'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '13px',
      fontWeight: '700',
      color: '#facc15',
    },
    properties: {
      text: 'RANGE TO TARGET: 14.8 m',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 14,
      fontWeight: '700',
      color: '#facc15',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 60,
    }
  },
  {
    id: 'ts-metric-memory-leak-tracker',
    name: 'RAM & VRAM Usage Meter',
    category: 'AR Telemetry & Metrics',
    target: '2D HUD',
    sampleText: 'VRAM: 1.8 GB / 4.0 GB (45%)',
    description: 'VRAM memory consumption metric banner.',
    badge: 'VRAM',
    objectType: 'hudText',
    tags: ['metric', 'vram', 'memory', 'mono'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '12px',
      fontWeight: '600',
      color: '#c084fc',
    },
    properties: {
      text: 'VRAM: 1.8 GB / 4.0 GB (45%)',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 13,
      fontWeight: '600',
      color: '#c084fc',
      alignment: 'top-right',
      offsetX: 20,
      offsetY: 85,
    }
  },
  {
    id: 'ts-metric-tracking-loss-alert',
    name: 'LiDAR Tracking Confidence',
    category: 'AR Telemetry & Metrics',
    target: '2D HUD',
    sampleText: 'LIDAR SENSOR: 99.8% CONFIDENCE',
    description: 'LiDAR surface mesh tracking confidence metric.',
    badge: 'LIDAR',
    objectType: 'hudText',
    tags: ['metric', 'lidar', 'sensor', 'confidence'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '12px',
      fontWeight: '700',
      color: '#06b6d4',
      background: 'rgba(6,182,212,0.12)',
      border: '1px solid rgba(6,182,212,0.3)',
      padding: '4px 10px',
      borderRadius: '6px',
    },
    properties: {
      text: 'LIDAR SENSOR: 99.8% CONFIDENCE',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 13,
      fontWeight: '700',
      color: '#06b6d4',
      backgroundColor: 'rgba(6,182,212,0.12)',
      border: '1px solid rgba(6,182,212,0.3)',
      borderRadius: '6px',
      padding: '6px 12px',
      alignment: 'bottom-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-metric-temperature-celsius',
    name: 'Ambient Temperature Metric',
    category: 'AR Telemetry & Metrics',
    target: '2D HUD',
    sampleText: 'THERMAL: 34.2°C [NORMAL]',
    description: 'Device thermal status readout in Celsius.',
    badge: 'THERMAL',
    objectType: 'hudText',
    tags: ['metric', 'thermal', 'temp', 'celsius'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '12px',
      fontWeight: '700',
      color: '#f97316',
    },
    properties: {
      text: 'THERMAL: 34.2°C [NORMAL]',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 13,
      fontWeight: '700',
      color: '#f97316',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 85,
    }
  },
  {
    id: 'ts-metric-3d-polygon-counter',
    name: '3D Scene Polygon Count Readout',
    category: 'AR Telemetry & Metrics',
    target: '3D Scene',
    sampleText: 'POLY COUNT: 42,890 TRIS',
    description: '3D scene polygon count readout.',
    badge: '3D TRIS',
    objectType: 'text',
    tags: ['3d', 'metric', 'poly', 'tris'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '13px',
      fontWeight: '700',
      color: '#a855f7',
    },
    properties: {
      text: 'POLY COUNT: 42,890 TRIS',
      color: '#a855f7',
      fontSize: 0.11,
      outlineColor: '#3b0764',
      outlineWidth: 0.01,
      textAlign: 'center',
    },
    position: [0, 0.3, 0]
  },
  {
    id: 'ts-metric-network-latency',
    name: 'Network Latency Ping Banner',
    category: 'AR Telemetry & Metrics',
    target: '2D HUD',
    sampleText: 'PING: 18 ms // CLOUD SYNC: OK',
    description: 'Network ping and cloud synchronization indicator.',
    badge: 'PING',
    objectType: 'hudText',
    tags: ['metric', 'ping', 'network', 'cloud'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '11px',
      fontWeight: '600',
      color: '#94a3b8',
    },
    properties: {
      text: 'PING: 18 ms // CLOUD SYNC: OK',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 12,
      fontWeight: '600',
      color: '#94a3b8',
      alignment: 'bottom-right',
      offsetX: 30,
      offsetY: 55,
    }
  },
  {
    id: 'ts-metric-compass-azimuth',
    name: 'Compass Azimuth Bearing',
    category: 'AR Telemetry & Metrics',
    target: '2D HUD',
    sampleText: 'BEARING: 214° SW (AZIMUTH)',
    description: 'Spatial compass azimuth orientation readout.',
    badge: 'AZIMUTH',
    objectType: 'hudText',
    tags: ['metric', 'compass', 'bearing', 'azimuth'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '12px',
      fontWeight: '700',
      color: '#38bdf8',
    },
    properties: {
      text: 'BEARING: 214° SW (AZIMUTH)',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 13,
      fontWeight: '700',
      color: '#38bdf8',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 15,
    }
  },

  // ==========================================
  // 7. RETRO & VINTAGE (5 PRESETS)
  // ==========================================
  {
    id: 'ts-retro-arcade-title',
    name: 'Arcade Pixel Header',
    category: 'Retro & Vintage',
    target: '2D HUD',
    sampleText: 'HIGH SCORE: 999990',
    description: 'Retro 8-bit arcade high score text layout.',
    badge: '8-BIT',
    objectType: 'hudText',
    tags: ['retro', 'arcade', 'pixel', '8bit'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '16px',
      fontWeight: '800',
      color: '#facc15',
      letterSpacing: '0.1em',
      textShadow: '3px 3px 0px #b45309',
    },
    properties: {
      text: 'HIGH SCORE: 999990',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 22,
      fontWeight: '800',
      color: '#facc15',
      letterSpacing: '0.1em',
      textShadow: '3px 3px 0px #b45309',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 30,
    }
  },
  {
    id: 'ts-retro-synthwave-pink',
    name: 'Synthwave 80s Sunset Text',
    category: 'Retro & Vintage',
    target: '2D HUD',
    sampleText: 'OUTRUN 1986',
    description: 'Classic 80s synthwave neon magenta text.',
    badge: 'SYNTHWAVE',
    objectType: 'hudText',
    tags: ['retro', 'synthwave', '80s', 'pink'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '20px',
      fontWeight: '900',
      color: '#ec4899',
      fontStyle: 'italic',
      textShadow: '0 0 10px #f472b6, 0 0 20px #be185d',
    },
    properties: {
      text: 'OUTRUN 1986',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 28,
      fontWeight: '900',
      color: '#ec4899',
      textShadow: '0 0 10px #f472b6, 0 0 20px #be185d',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 40,
    }
  },
  {
    id: 'ts-retro-amber-crt-monitor',
    name: 'Amber CRT Terminal Screen',
    category: 'Retro & Vintage',
    target: '2D HUD',
    sampleText: 'READY.\nLOAD "AR_GAME",8,1',
    description: 'Commodore-style vintage amber CRT monitor display.',
    badge: 'CRT AMBER',
    objectType: 'hudText',
    tags: ['retro', 'crt', 'amber', 'terminal'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '13px',
      fontWeight: '700',
      color: '#f59e0b',
      background: '#1c1917',
      border: '2px solid #78350f',
      padding: '8px 12px',
      borderRadius: '8px',
    },
    properties: {
      text: 'READY.\nLOAD "AR_GAME",8,1',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 15,
      fontWeight: '700',
      color: '#f59e0b',
      backgroundColor: '#1c1917',
      border: '2px solid #78350f',
      borderRadius: '8px',
      padding: '10px 16px',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-retro-3d-neon-arcade',
    name: '3D Retro Arcade Sign',
    category: 'Retro & Vintage',
    target: '3D Scene',
    sampleText: 'INSERT COIN 3D',
    description: '3D floating arcade insert coin marquee sign.',
    badge: '3D ARCADE',
    objectType: 'text',
    tags: ['3d', 'retro', 'arcade', 'coin'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '18px',
      fontWeight: '800',
      color: '#facc15',
      textShadow: '2px 2px 0px #854d0e',
    },
    properties: {
      text: 'INSERT COIN 3D',
      color: '#facc15',
      fontSize: 0.2,
      outlineColor: '#713f12',
      outlineWidth: 0.018,
      textAlign: 'center',
    },
    position: [0, 1.2, 0]
  },
  {
    id: 'ts-retro-vhs-timestamp',
    name: 'VHS Camcorder Timestamp',
    category: 'Retro & Vintage',
    target: '2D HUD',
    sampleText: 'PLAY ▷ 00:04:18 [REC]',
    description: 'Authentic 90s camcorder VHS timestamp overlay.',
    badge: 'VHS REC',
    objectType: 'hudText',
    tags: ['retro', 'vhs', 'camcorder', 'timestamp'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '14px',
      fontWeight: '700',
      color: '#ffffff',
      textShadow: '2px 2px 0px #000',
    },
    properties: {
      text: 'PLAY ▷ 00:04:18 [REC]',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 16,
      fontWeight: '700',
      color: '#ffffff',
      textShadow: '2px 2px 0px #000',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },

  // ==========================================
  // 8. GRADIENTS & METALLIC (5 PRESETS)
  // ==========================================
  {
    id: 'ts-gradient-gold-metallic',
    name: 'Liquid Gold Metallic Header',
    category: 'Gradients & Metallic',
    target: '2D HUD',
    sampleText: 'SOLARIS ROYAL GOLD',
    description: 'Polished metallic gold title style with luxury aura.',
    badge: 'GOLD METAL',
    objectType: 'hudText',
    tags: ['gradient', 'gold', 'metallic', 'luxury'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '20px',
      fontWeight: '800',
      color: '#fbbf24',
      textShadow: '0 4px 15px rgba(245,158,11,0.5)',
    },
    properties: {
      text: 'SOLARIS ROYAL GOLD',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 28,
      fontWeight: '800',
      color: '#fbbf24',
      textShadow: '0 4px 15px rgba(245,158,11,0.5)',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 40,
    }
  },
  {
    id: 'ts-gradient-silver-titanium',
    name: 'Titanium Steel Metallic Title',
    category: 'Gradients & Metallic',
    target: '2D HUD',
    sampleText: 'TITANIUM ALLOY',
    description: 'Sleek silver titanium metallic header.',
    badge: 'TITANIUM',
    objectType: 'hudText',
    tags: ['gradient', 'silver', 'titanium', 'metal'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '20px',
      fontWeight: '800',
      color: '#f1f5f9',
      textShadow: '0 4px 12px rgba(148,163,184,0.5)',
    },
    properties: {
      text: 'TITANIUM ALLOY',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 28,
      fontWeight: '800',
      color: '#f1f5f9',
      textShadow: '0 4px 12px rgba(148,163,184,0.5)',
      alignment: 'top-left',
      offsetX: 40,
      offsetY: 40,
    }
  },
  {
    id: 'ts-gradient-cyber-rainbow',
    name: 'Iridescent Rainbow Spectra',
    category: 'Gradients & Metallic',
    target: '2D HUD',
    sampleText: 'IRIDESCENT SPECTRA',
    description: 'Multi-hue rainbow spectrum gradient title.',
    badge: 'RAINBOW',
    objectType: 'hudText',
    tags: ['gradient', 'rainbow', 'iridescent', 'spectra'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '20px',
      fontWeight: '800',
      color: '#38bdf8',
      textShadow: '0 4px 15px rgba(168,85,247,0.5)',
    },
    properties: {
      text: 'IRIDESCENT SPECTRA',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 28,
      fontWeight: '800',
      color: '#38bdf8',
      textShadow: '0 4px 15px rgba(168,85,247,0.5)',
      alignment: 'top-center',
      offsetX: 0,
      offsetY: 40,
    }
  },
  {
    id: 'ts-gradient-3d-gold-spatial',
    name: '3D Gold Spatial Metallic Title',
    category: 'Gradients & Metallic',
    target: '3D Scene',
    sampleText: 'SPATIAL GOLD 3D',
    description: '3D golden spatial metallic header text.',
    badge: '3D GOLD',
    objectType: 'text',
    tags: ['3d', 'gold', 'metallic', 'spatial'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '18px',
      fontWeight: '800',
      color: '#f59e0b',
      textShadow: '0 0 10px #fef08a',
    },
    properties: {
      text: 'SPATIAL GOLD 3D',
      color: '#f59e0b',
      fontSize: 0.22,
      outlineColor: '#78350f',
      outlineWidth: 0.02,
      textAlign: 'center',
    },
    position: [0, 1.2, 0]
  },
  {
    id: 'ts-gradient-rose-gold',
    name: 'Rose Gold Luxury Header',
    category: 'Gradients & Metallic',
    target: '2D HUD',
    sampleText: 'ROSE GOLD AR',
    description: 'Polished rose gold metallic title.',
    badge: 'ROSE GOLD',
    objectType: 'hudText',
    tags: ['gradient', 'rose', 'gold', 'luxury'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '18px',
      fontWeight: '800',
      color: '#fb7185',
      textShadow: '0 4px 12px rgba(251,113,133,0.4)',
    },
    properties: {
      text: 'ROSE GOLD AR',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 26,
      fontWeight: '800',
      color: '#fb7185',
      textShadow: '0 4px 12px rgba(251,113,133,0.4)',
      alignment: 'top-left',
      offsetX: 40,
      offsetY: 40,
    }
  },

  // ==========================================
  // 9. BADGES & LABELS (5 PRESETS)
  // ==========================================
  {
    id: 'ts-badge-verified-green',
    name: 'Verified Checkmark Badge',
    category: 'Badges & Labels',
    target: '2D HUD',
    sampleText: '✓ VERIFIED MODEL',
    description: 'Green verified model badge label.',
    badge: 'VERIFIED',
    objectType: 'hudText',
    tags: ['badge', 'verified', 'green', 'check'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '12px',
      fontWeight: '700',
      color: '#15803d',
      background: '#dcfce7',
      borderRadius: '20px',
      padding: '4px 12px',
    },
    properties: {
      text: '✓ VERIFIED MODEL',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 13,
      fontWeight: '700',
      color: '#15803d',
      backgroundColor: '#dcfce7',
      borderRadius: '20px',
      padding: '6px 14px',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-badge-beta-version',
    name: 'Beta Tag Label',
    category: 'Badges & Labels',
    target: '2D HUD',
    sampleText: 'BETA v0.9.4',
    description: 'Small purple beta software tag.',
    badge: 'BETA',
    objectType: 'hudText',
    tags: ['badge', 'beta', 'purple', 'version'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '11px',
      fontWeight: '700',
      color: '#a855f7',
      background: 'rgba(168,85,247,0.15)',
      border: '1px solid rgba(168,85,247,0.3)',
      borderRadius: '6px',
      padding: '3px 8px',
    },
    properties: {
      text: 'BETA v0.9.4',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 12,
      fontWeight: '700',
      color: '#a855f7',
      backgroundColor: 'rgba(168,85,247,0.15)',
      border: '1px solid rgba(168,85,247,0.3)',
      borderRadius: '6px',
      padding: '4px 10px',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-badge-hot-sale-red',
    name: 'Hot Sale Promo Tag',
    category: 'Badges & Labels',
    target: '2D HUD',
    sampleText: '🔥 50% OFF TODAY',
    description: 'Vibrant hot sale promotional discount badge.',
    badge: 'HOT SALE',
    objectType: 'hudText',
    tags: ['badge', 'sale', 'red', 'discount'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '12px',
      fontWeight: '800',
      color: '#ffffff',
      background: '#ef4444',
      borderRadius: '6px',
      padding: '4px 10px',
    },
    properties: {
      text: '🔥 50% OFF TODAY',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 13,
      fontWeight: '800',
      color: '#ffffff',
      backgroundColor: '#ef4444',
      borderRadius: '6px',
      padding: '6px 12px',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  },
  {
    id: 'ts-badge-3d-node-pin',
    name: '3D Node Marker Badge',
    category: 'Badges & Labels',
    target: '3D Scene',
    sampleText: '[ NODE #04 ]',
    description: '3D spatial pin marker badge for scene annotations.',
    badge: '3D PIN',
    objectType: 'text',
    tags: ['3d', 'badge', 'node', 'pin'],
    previewStyle: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '13px',
      fontWeight: '700',
      color: '#38bdf8',
    },
    properties: {
      text: '[ NODE #04 ]',
      color: '#38bdf8',
      fontSize: 0.14,
      outlineColor: '#0c4a6e',
      outlineWidth: 0.012,
      textAlign: 'center',
    },
    position: [0, 0.8, 0]
  },
  {
    id: 'ts-badge-ai-generated',
    name: 'AI Generated Tag',
    category: 'Badges & Labels',
    target: '2D HUD',
    sampleText: '✨ AI GENERATED SCENE',
    description: 'Sparkling cyan AI generated content badge.',
    badge: 'AI TAG',
    objectType: 'hudText',
    tags: ['badge', 'ai', 'sparkle', 'cyan'],
    previewStyle: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '11px',
      fontWeight: '700',
      color: '#06b6d4',
      background: 'rgba(6,182,212,0.12)',
      border: '1px solid rgba(6,182,212,0.3)',
      borderRadius: '20px',
      padding: '4px 10px',
    },
    properties: {
      text: '✨ AI GENERATED SCENE',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: 12,
      fontWeight: '700',
      color: '#06b6d4',
      backgroundColor: 'rgba(6,182,212,0.12)',
      border: '1px solid rgba(6,182,212,0.3)',
      borderRadius: '20px',
      padding: '6px 12px',
      alignment: 'top-left',
      offsetX: 30,
      offsetY: 30,
    }
  }
];
