import { Real3DAsset, createRealAsset, BASE_KHRONOS_URL, BASE_ITEM_URL } from './types';

export const ADVERTISING_RETAIL_ASSETS: Real3DAsset[] = [
  createRealAsset(
    'ad-billboard-stand',
    'Outdoor Commercial Billboard Stand',
    'Advertising & Retail',
    'Heavy steel dual-column freestanding commercial advertising billboard frame structure.',
    'BILLBOARD STAND',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🪧',
    `${BASE_ITEM_URL}/flat-screen-tv/thumbnail.webp`,
    `${BASE_ITEM_URL}/flat-screen-tv/model.glb`,
    '#2563eb',
    0.95,
    ['billboard', 'advertising', 'outdoor', 'signage', 'commercial', 'poster']
  ),
  createRealAsset(
    'ad-lightbox-frame',
    'Ultra-Thin LED Snap Lightbox',
    'Advertising & Retail',
    'Anodized aluminum edge-lit magnetic poster lightbox frame with uniform backlighting glow.',
    'LED LIGHTBOX',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '💡',
    `${BASE_ITEM_URL}/television/thumbnail.webp`,
    `${BASE_ITEM_URL}/television/model.glb`,
    '#eab308',
    0.80,
    ['lightbox', 'poster', 'print ad', 'display', 'retail', 'sign']
  ),
  createRealAsset(
    'ad-rollup-banner-stand',
    'Retractable Expo Rollup Banner',
    'Advertising & Retail',
    'Aluminum cassette retractable floor banner stand for trade shows, events, and retail promotions.',
    'ROLLUP BANNER',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🚩',
    `${BASE_ITEM_URL}/easel/thumbnail.webp`,
    `${BASE_ITEM_URL}/easel/model.glb`,
    '#10b981',
    0.75,
    ['rollup', 'banner', 'trade show', 'stand', 'marketing', 'poster']
  ),
  createRealAsset(
    'ad-pedestal-acrylic',
    'Museum Glossy Product Pedestal',
    'Advertising & Retail',
    'Minimalist white museum plinth display column for luxury product showcases.',
    'PRODUCT PEDESTAL',
    'bg-stone-500/20 text-stone-300 border-stone-500/30',
    '🏛️',
    `${BASE_ITEM_URL}/bedside-table/thumbnail.webp`,
    `${BASE_ITEM_URL}/bedside-table/model.glb`,
    '#78716c',
    0.60,
    ['pedestal', 'plinth', 'display', 'luxury', 'showcase', 'podium']
  ),
  createRealAsset(
    'ad-podium-presentation',
    'Keynote Exhibition Presentation Podium',
    'Advertising & Retail',
    'Curved architectural stage keynote podium with integrated document shelf and mic mount.',
    'KEYNOTE PODIUM',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🎙️',
    `${BASE_ITEM_URL}/desk/thumbnail.webp`,
    `${BASE_ITEM_URL}/desk/model.glb`,
    '#4f46e5',
    0.70,
    ['podium', 'lectern', 'presentation', 'stage', 'conference']
  ),
  createRealAsset(
    'ad-supermarket-gondola',
    'Modular Retail Merchandising Gondola',
    'Advertising & Retail',
    'Double-sided steel supermarket shelving unit with price channel strips and end caps.',
    'RETAIL GONDOLA',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🛒',
    `${BASE_ITEM_URL}/bookshelf/thumbnail.webp`,
    `${BASE_ITEM_URL}/bookshelf/model.glb`,
    '#059669',
    0.85,
    ['supermarket', 'gondola', 'shelving', 'retail', 'merchandising', 'store']
  ),
  createRealAsset(
    'ad-showcase-vitrine',
    'Tempered Glass Jewelry Showcase Vitrine',
    'Advertising & Retail',
    'Lockable illuminated museum glass display counter with brushed aluminum frame.',
    'GLASS SHOWCASE',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '💎',
    `${BASE_ITEM_URL}/coffee-table/thumbnail.webp`,
    `${BASE_ITEM_URL}/coffee-table/model.glb`,
    '#0891b2',
    0.75,
    ['vitrine', 'showcase', 'glass', 'jewelry', 'luxury', 'retail']
  ),
  createRealAsset(
    'ad-brochure-dispenser',
    'Multi-Tier Literature Brochure Stand',
    'Advertising & Retail',
    'Curved metal floor brochure rack for tri-fold pamphlets, catalogs, and marketing flyers.',
    'BROCHURE STAND',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '📄',
    `${BASE_ITEM_URL}/shelf/thumbnail.webp`,
    `${BASE_ITEM_URL}/shelf/model.glb`,
    '#475569',
    0.65,
    ['brochure', 'pamphlet', 'catalog', 'flyer', 'literature', 'stand']
  ),
  createRealAsset(
    'ad-gold-trophy',
    'Gilded Star Excellence Award Trophy',
    'Advertising & Retail',
    'Solid gold award trophy on black polished marble pedestal for contest campaigns.',
    'GOLD TROPHY',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🏆',
    `${BASE_KHRONOS_URL}/Lantern/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/Lantern/glTF-Binary/Lantern.glb`,
    '#eab308',
    0.40,
    ['trophy', 'award', 'gold', 'contest', 'winner', 'prize']
  ),
  createRealAsset(
    'ad-prize-wheel-fortune',
    'Carnival Spin-to-Win Lucky Prize Wheel',
    'Advertising & Retail',
    'Colorful multi-segment spinning prize wheel with ticker pointer for promotional giveaways.',
    'PRIZE WHEEL',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '🎡',
    `${BASE_ITEM_URL}/ceiling-fan/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-fan/model.glb`,
    '#e11d48',
    0.75,
    ['prize wheel', 'spin', 'giveaway', 'gamification', 'contest', 'promo']
  ),
  createRealAsset(
    'ad-luxury-gift-box',
    'Matte Black & Gold Ribbon Gift Box',
    'Advertising & Retail',
    'Luxury embossed rigid gift box tied with shimmering satin gold ribbon and bow.',
    'LUXURY GIFT BOX',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🎁',
    `${BASE_KHRONOS_URL}/CarbonFibreBox/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/CarbonFibreBox/glTF-Binary/CarbonFibreBox.glb`,
    '#b45309',
    0.38,
    ['gift box', 'packaging', 'unboxing', 'luxury', 'retail', 'promo']
  ),
  createRealAsset(
    'ad-interactive-kiosk-totem',
    '55" Vertical Wayfinding Touch Kiosk',
    'Advertising & Retail',
    'Slim freestanding interactive touchscreen totem pylon for digital interactive ads.',
    'INTERACTIVE KIOSK',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🖥️',
    `${BASE_ITEM_URL}/flat-screen-tv/thumbnail.webp`,
    `${BASE_ITEM_URL}/flat-screen-tv/model.glb`,
    '#1d4ed8',
    0.85,
    ['kiosk', 'digital signage', 'touchscreen', 'wayfinding', 'retail', 'ad']
  ),
  createRealAsset(
    'ad-shopping-cart-chrome',
    'Commercial Supermarket Shopping Cart',
    'Advertising & Retail',
    'Chrome wire steel grocery shopping trolley with child seat and swivel casters.',
    'SHOPPING CART',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🛒',
    `${BASE_ITEM_URL}/barbell-stand/thumbnail.webp`,
    `${BASE_ITEM_URL}/barbell-stand/model.glb`,
    '#10b981',
    0.65,
    ['cart', 'shopping cart', 'trolley', 'e-commerce', 'retail', 'grocery']
  ),
  createRealAsset(
    'ad-kraft-shopping-bag',
    'Premium Embossed Kraft Shopping Bag',
    'Advertising & Retail',
    'Heavyweight recycled kraft paper luxury retail shopping bag with twisted paper handles.',
    'SHOPPING BAG',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🛍️',
    `${BASE_KHRONOS_URL}/Corset/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Corset/glTF-Binary/Corset.glb`,
    '#ca8a04',
    0.40,
    ['bag', 'shopping bag', 'kraft', 'retail', 'branding', 'merch']
  ),
  createRealAsset(
    'ad-mannequin-bust',
    'Haute Couture Tailor Mannequin Bust',
    'Advertising & Retail',
    'Linen fabric upholstered female dressmaker torso mannequin on cast iron tripod stand.',
    'TAILOR MANNEQUIN',
    'bg-stone-500/20 text-stone-300 border-stone-500/30',
    '👗',
    `${BASE_KHRONOS_URL}/Corset/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Corset/glTF-Binary/Corset.glb`,
    '#78716c',
    0.70,
    ['mannequin', 'fashion', 'apparel', 'bust', 'retail', 'couture']
  ),
  createRealAsset(
    'ad-neon-sale-marquee',
    '3D Neon "FLASH SALE" Marquee Sign',
    'Advertising & Retail',
    'Luminous vintage-style neon marquee sign with animated blinking promotional letters.',
    'SALE MARQUEE',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '💥',
    `${BASE_ITEM_URL}/exit-sign/thumbnail.webp`,
    `${BASE_ITEM_URL}/exit-sign/model.glb`,
    '#ef4444',
    0.55,
    ['sale', 'marquee', 'neon', 'discount', 'promotion', 'advertising']
  ),
  createRealAsset(
    'ad-promotional-tent-canopy',
    '10x10 Event Pop-Up Canopy Tent',
    'Advertising & Retail',
    'Branded waterproof outdoor promotional event gazebo canopy tent.',
    'CANOPY TENT',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '⛺',
    `${BASE_ITEM_URL}/patio-umbrella/thumbnail.webp`,
    `${BASE_ITEM_URL}/patio-umbrella/model.glb`,
    '#06b6d4',
    0.95,
    ['canopy', 'tent', 'event', 'pop-up', 'promo', 'outdoor']
  ),
  createRealAsset(
    'ad-directional-pylon-sign',
    'Brushed Aluminum Wayfinding Pylon',
    'Advertising & Retail',
    'Architectural curved monolithic directory pylon sign for malls and retail parks.',
    'WAYFINDING PYLON',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🗺️',
    `${BASE_ITEM_URL}/door/thumbnail.webp`,
    `${BASE_ITEM_URL}/door/model.glb`,
    '#52525b',
    0.85,
    ['pylon', 'sign', 'wayfinding', 'directory', 'mall', 'retail']
  ),
  createRealAsset(
    'ad-acrylic-price-tag-stand',
    'Angled L-Shape Acrylic Price Stand',
    'Advertising & Retail',
    'Clear optical polished acrylic counter card holder for price tags and QR discount codes.',
    'PRICE CARD STAND',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🏷️',
    `${BASE_ITEM_URL}/alarm-keypad/thumbnail.webp`,
    `${BASE_ITEM_URL}/alarm-keypad/model.glb`,
    '#64748b',
    0.22,
    ['price tag', 'acrylic', 'qr code', 'stand', 'counter', 'pos']
  ),
  createRealAsset(
    'ad-sidewalk-a-frame-chalkboard',
    'Bistro Wooden A-Frame Chalkboard',
    'Advertising & Retail',
    'Rustic dark oak sidewalk sandwich board chalkboard for daily specials and announcements.',
    'A-FRAME CHALKBOARD',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '📋',
    `${BASE_ITEM_URL}/easel/thumbnail.webp`,
    `${BASE_ITEM_URL}/easel/model.glb`,
    '#b45309',
    0.60,
    ['a-frame', 'sandwich board', 'chalkboard', 'bistro', 'cafe', 'menu']
  ),
  createRealAsset(
    'ad-crowd-control-stanchion',
    'VIP Retractable Belt Crowd Stanchion',
    'Advertising & Retail',
    'Heavy polished chrome crowd control queue barrier post with red velvet retractable belt.',
    'VIP STANCHION',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🚧',
    `${BASE_ITEM_URL}/floor-lamp/thumbnail.webp`,
    `${BASE_ITEM_URL}/floor-lamp/model.glb`,
    '#dc2626',
    0.50,
    ['stanchion', 'crowd control', 'barrier', 'vip', 'queue', 'red carpet']
  ),
  createRealAsset(
    'ad-pos-cashier-counter',
    'Modern Retail Cashier Checkout Desk',
    'Advertising & Retail',
    'Architectural POS checkout station counter with touch register, scanner, and receipt terminal.',
    'POS CHECKOUT',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '💳',
    `${BASE_ITEM_URL}/desk/thumbnail.webp`,
    `${BASE_ITEM_URL}/desk/model.glb`,
    '#4338ca',
    0.80,
    ['checkout', 'pos', 'cashier', 'terminal', 'register', 'counter']
  ),
  createRealAsset(
    'ad-hanging-retail-banner',
    'Ceiling Hanging Fabric Promo Banner',
    'Advertising & Retail',
    'Suspended double-sided ceiling banner flag for department store sale promotions.',
    'HANGING BANNER',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🎏',
    `${BASE_ITEM_URL}/window-large/thumbnail.webp`,
    `${BASE_ITEM_URL}/window-large/model.glb`,
    '#f59e0b',
    0.70,
    ['hanging banner', 'ceiling', 'promo', 'retail', 'flag', 'sale']
  ),
  createRealAsset(
    'ad-rotating-wire-spinner',
    '4-Sided Rotating Wire Display Spinner',
    'Advertising & Retail',
    'Revolving retail countertop wire display rack for postcards, gift cards, and merchandise.',
    'CARD SPINNER',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🔄',
    `${BASE_ITEM_URL}/floor-lamp/thumbnail.webp`,
    `${BASE_ITEM_URL}/floor-lamp/model.glb`,
    '#475569',
    0.65,
    ['spinner', 'wire rack', 'gift cards', 'merchandise', 'retail']
  ),
  createRealAsset(
    'ad-bakery-display-case',
    'Curved Glass Bakery Counter Case',
    'Advertising & Retail',
    'Illuminated countertop pastry and confectionery display vitrine with sliding rear doors.',
    'PASTRY CASE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🥐',
    `${BASE_ITEM_URL}/coffee-table/thumbnail.webp`,
    `${BASE_ITEM_URL}/coffee-table/model.glb`,
    '#d97706',
    0.75,
    ['bakery', 'pastry', 'display', 'counter', 'food', 'cafe']
  ),
  createRealAsset(
    'ad-slanted-beverage-gondola',
    'Slanted Bottle Merchandising Rack',
    'Advertising & Retail',
    'Specialty beverage and wine bottle retail merchandising shelf rack.',
    'BEVERAGE RACK',
    'bg-purple-500/20 text-purple-300 border-purple-500/30',
    '🍾',
    `${BASE_ITEM_URL}/bookshelf/thumbnail.webp`,
    `${BASE_ITEM_URL}/bookshelf/model.glb`,
    '#9333ea',
    0.80,
    ['beverage', 'wine', 'bottles', 'merchandising', 'rack', 'retail']
  ),
  createRealAsset(
    'ad-cosmetics-tester-stand',
    'Illuminated Beauty Cosmetic Tester Bar',
    'Advertising & Retail',
    'Countertop beauty tester tray with integrated LED mirror and lipstick slots.',
    'COSMETICS TESTER',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '💄',
    `${BASE_ITEM_URL}/rectangular-mirror/thumbnail.webp`,
    `${BASE_ITEM_URL}/rectangular-mirror/model.glb`,
    '#f43f5e',
    0.50,
    ['cosmetics', 'beauty', 'makeup', 'tester', 'counter', 'lipstick']
  ),
  createRealAsset(
    'ad-security-turnstile-gate',
    'Stainless Optical Turnstile Barrier',
    'Advertising & Retail',
    'High-throughput motorized optical flap barrier gate with RFID reader column.',
    'TURNSTILE GATE',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🛂',
    `${BASE_ITEM_URL}/high-fence/thumbnail.webp`,
    `${BASE_ITEM_URL}/high-fence/model.glb`,
    '#3f3f46',
    0.70,
    ['turnstile', 'gate', 'security', 'rfid', 'entry', 'access']
  ),
  createRealAsset(
    'ad-digital-menu-board',
    'Triple-Screen Fast Food Digital Menu Board',
    'Advertising & Retail',
    'Ceiling-mounted 3-screen high-brightness restaurant menu display array.',
    'DIGITAL MENU',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🍔',
    `${BASE_ITEM_URL}/flat-screen-tv/thumbnail.webp`,
    `${BASE_ITEM_URL}/flat-screen-tv/model.glb`,
    '#f59e0b',
    0.85,
    ['menu board', 'digital menu', 'fast food', 'restaurant', 'screens']
  ),
  createRealAsset(
    'ad-perfume-display-tray',
    'Mirrored Fragrance Display Podium',
    'Advertising & Retail',
    'Hexagonal mirrored crystal tray with perfume bottle risers for luxury boutique counters.',
    'PERFUME TRAY',
    'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-500/30',
    '🌸',
    `${BASE_ITEM_URL}/table/thumbnail.webp`,
    `${BASE_ITEM_URL}/table/model.glb`,
    '#d946ef',
    0.40,
    ['perfume', 'fragrance', 'luxury', 'cosmetics', 'tray', 'boutique']
  )
];
