import { Real3DAsset, createRealAsset, BASE_ITEM_URL, BASE_KHRONOS_URL } from './types';

// ============================================================================
// 1. REALISTIC BUILDINGS & ARCHITECTURE (35+ diverse cultural & regional buildings)
// ============================================================================
export const REALISTIC_BUILDINGS_ASSETS: Real3DAsset[] = [
  // EAST ASIA
  createRealAsset(
    'bld-real-jp-machiya',
    'Kyoto Traditional Machiya Townhouse',
    'Realistic Buildings',
    'Classic Japanese Edo-period wooden townhouse featuring dark cedar latticework (koshi), tiled kawara roof, and sliding shoji paper screen facade.',
    'JAPANESE MACHIYA',
    'bg-amber-600/20 text-amber-300 border-amber-500/30',
    '🏯',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#92400e',
    0.85,
    ['realistic building', 'architecture', 'japan', 'kyoto', 'machiya', 'wood', 'traditional', 'asia', 'house']
  ),
  createRealAsset(
    'bld-real-jp-pagoda',
    'Five-Story Buddhist Pagoda (Goju-no-to)',
    'Realistic Buildings',
    'Multi-tiered sacred wooden Buddhist pagoda with copper eaves, central shinbashira pillar, and ornamental bronze finial spire.',
    'PAGODA TEMPLE',
    'bg-red-700/20 text-red-300 border-red-500/30',
    '⛩️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#b91c1c',
    0.95,
    ['realistic building', 'architecture', 'pagoda', 'temple', 'buddhism', 'japan', 'shrine', 'asia', 'historic']
  ),
  createRealAsset(
    'bld-real-cn-siheyuan',
    'Beijing Courtyard Siheyuan Compound',
    'Realistic Buildings',
    'Historical Chinese quadrangle courtyard residence with ornate red pillars, grey roof ridges, moon gate arch, and auspicious stone carvings.',
    'CHINESE SIHEYUAN',
    'bg-red-600/20 text-red-300 border-red-500/30',
    '🏮',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#991b1b',
    0.90,
    ['realistic building', 'architecture', 'china', 'beijing', 'siheyuan', 'courtyard', 'traditional', 'asia']
  ),
  createRealAsset(
    'bld-real-kr-hanok',
    'Traditional Korean Hanok Pavilion',
    'Realistic Buildings',
    'Eco-friendly Korean wooden residential pavilion with curved Giwa tiled eaves, Ondol stone foundation, and natural pine beams.',
    'KOREAN HANOK',
    'bg-orange-600/20 text-orange-300 border-orange-500/30',
    '🏠',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#c2410c',
    0.88,
    ['realistic building', 'architecture', 'korea', 'hanok', 'seoul', 'wood', 'traditional', 'asia', 'giwa']
  ),

  // EUROPE - CLASSICAL, MEDIEVAL & HISTORIC
  createRealAsset(
    'bld-real-eu-medieval-timber',
    'European Medieval Half-Timber House',
    'Realistic Buildings',
    '15th-century Tudor and Bavarian vernacular timber-framed townhouse with exposed dark oak trusses, wattle-and-daub infill, and steep gable roof.',
    'HALF-TIMBER TUDOR',
    'bg-yellow-700/20 text-yellow-300 border-yellow-500/30',
    '🏰',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#854d0e',
    0.85,
    ['realistic building', 'architecture', 'medieval', 'europe', 'tudor', 'timber', 'germany', 'england', 'historic']
  ),
  createRealAsset(
    'bld-real-gr-parthenon',
    'Classical Greco-Roman Doric Temple',
    'Realistic Buildings',
    'Monumental Hellenic temple inspired by the Athenian Acropolis, with marble colonnade peristyle, fluted Doric pillars, and relief frieze pediment.',
    'GRECIAN TEMPLE',
    'bg-stone-500/20 text-stone-300 border-stone-400/30',
    '🏛️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#78716c',
    0.95,
    ['realistic building', 'architecture', 'greece', 'rome', 'temple', 'classical', 'parthenon', 'marble', 'monument']
  ),
  createRealAsset(
    'bld-real-fr-haussmann',
    'Parisian Haussmannian Boulevard Apartment',
    'Realistic Buildings',
    '19th-century French stone apartment block with ornate wrought-iron balconies, continuous limestone ashlar masonry, and zinc mansard roof with dormers.',
    'PARIS HAUSSMANN',
    'bg-blue-600/20 text-blue-300 border-blue-500/30',
    '🏢',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#2563eb',
    0.90,
    ['realistic building', 'architecture', 'france', 'paris', 'haussmann', 'europe', 'apartment', 'historic', 'mansard']
  ),
  createRealAsset(
    'bld-real-it-tuscan-villa',
    'Italian Tuscan Renaissance Villa',
    'Realistic Buildings',
    'Rural Tuscan country estate featuring terracotta barrel-tile roof, warm stucco walls, cypress entry arcade, and arched loggia windows.',
    'TUSCAN VILLA',
    'bg-amber-700/20 text-amber-300 border-amber-600/30',
    '🏡',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#b45309',
    0.88,
    ['realistic building', 'architecture', 'italy', 'tuscany', 'villa', 'mediterranean', 'terracotta', 'renaissance']
  ),
  createRealAsset(
    'bld-real-nl-amsterdam-canal',
    'Amsterdam Canal Narrow Step-Gable House',
    'Realistic Buildings',
    'Iconic 17th-century Dutch Golden Age canal merchant house with dark brickwork, step-gable crest, hoisting beam, and tall sash windows.',
    'AMSTERDAM GABLE',
    'bg-orange-700/20 text-orange-300 border-orange-500/30',
    '🏘️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#c2410c',
    0.86,
    ['realistic building', 'architecture', 'netherlands', 'amsterdam', 'dutch', 'canal', 'brick', 'gable', 'europe']
  ),
  createRealAsset(
    'bld-real-uk-victorian-terrace',
    'London Victorian Red-Brick Terrace',
    'Realistic Buildings',
    '19th-century British residential terraced townhouse with bay windows, red-brick facade, decorative stone lintels, and slate gables.',
    'LONDON VICTORIAN',
    'bg-rose-700/20 text-rose-300 border-rose-500/30',
    '🏠',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#be123c',
    0.85,
    ['realistic building', 'architecture', 'uk', 'london', 'victorian', 'terrace', 'brick', 'england', 'townhouse']
  ),
  createRealAsset(
    'bld-real-no-stave-church',
    'Norwegian Borgund Stave Church',
    'Realistic Buildings',
    'Historic 12th-century Scandinavian post-and-lintel stave church constructed from dark tarred timber, with dragon-head gables and tiered shingled roofs.',
    'NORDIC STAVE CHURCH',
    'bg-stone-700/20 text-stone-300 border-stone-500/30',
    '⛪',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#44403c',
    0.92,
    ['realistic building', 'architecture', 'norway', 'nordic', 'scandinavia', 'church', 'stave', 'wood', 'viking']
  ),
  createRealAsset(
    'bld-real-ch-alpine-chalet',
    'Swiss Alpine Wooden Chalet',
    'Realistic Buildings',
    'Traditional Swiss mountain chalet with heavy timber logs, carved overhanging balconies, stone base, and flower-filled window planter boxes.',
    'SWISS CHALET',
    'bg-amber-800/20 text-amber-300 border-amber-600/30',
    '🏔️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#78350f',
    0.84,
    ['realistic building', 'architecture', 'switzerland', 'alps', 'chalet', 'timber', 'cabin', 'mountain', 'wood']
  ),
  createRealAsset(
    'bld-real-sc-stone-castle',
    'Scottish Highland Stone Castle Keep',
    'Realistic Buildings',
    'Fortified medieval stone fortress tower with machicolations, arrow slits, corner bartizans, and crenelated parapets overlooking the highlands.',
    'HIGHLAND CASTLE',
    'bg-zinc-600/20 text-zinc-300 border-zinc-500/30',
    '🏰',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#52525b',
    0.94,
    ['realistic building', 'architecture', 'scotland', 'castle', 'stone', 'medieval', 'fortress', 'keep', 'europe']
  ),
  createRealAsset(
    'bld-real-ru-onion-cathedral',
    'Eastern European Onion Dome Cathedral',
    'Realistic Buildings',
    'Ornate Russian Byzantine cathedral featuring gilded onion domes, tented belfry tower, kokoshnik arches, and vibrant polychrome stonework.',
    'ONION DOME CATHEDRAL',
    'bg-amber-500/20 text-amber-300 border-amber-400/30',
    '⛪',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#d97706',
    0.96,
    ['realistic building', 'architecture', 'cathedral', 'onion dome', 'gold', 'byzantine', 'historic', 'church']
  ),
  createRealAsset(
    'bld-real-gr-santorini-villa',
    'Santorini Cycladic Whitewashed House',
    'Realistic Buildings',
    'Greek Aegean island house with cubic whitewashed plaster walls, cobalt blue dome accent, smooth rounded edges, and bougainvillea terrace.',
    'SANTORINI CYCLADIC',
    'bg-sky-600/20 text-sky-300 border-sky-400/30',
    '🏛️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#0284c7',
    0.82,
    ['realistic building', 'architecture', 'greece', 'santorini', 'cycladic', 'mediterranean', 'white', 'island']
  ),

  // MIDDLE EAST & NORTH AFRICA
  createRealAsset(
    'bld-real-ma-riad',
    'Moroccan Marrakech Courtyard Riad',
    'Realistic Buildings',
    'Traditional Moroccan urban mansion built around a tranquil central patio with zellij mosaic tiles, carved cedar doors, and horseshoe arches.',
    'MOROCCAN RIAD',
    'bg-teal-700/20 text-teal-300 border-teal-500/30',
    '🕌',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#0f766e',
    0.88,
    ['realistic building', 'architecture', 'morocco', 'riad', 'marrakech', 'arabesque', 'zellij', 'mosaic', 'middle east']
  ),
  createRealAsset(
    'bld-real-tr-ottoman-mosque',
    'Ottoman Imperial Dome Mosque & Minaret',
    'Realistic Buildings',
    'Monumental imperial mosque inspired by Mimar Sinan, featuring cascading central domes, pencil minarets with muezzin balconies, and marble courtyard.',
    'OTTOMAN MOSQUE',
    'bg-cyan-700/20 text-cyan-300 border-cyan-500/30',
    '🕌',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#0e7490',
    0.95,
    ['realistic building', 'architecture', 'istanbul', 'turkey', 'mosque', 'dome', 'minaret', 'ottoman', 'islamic']
  ),
  createRealAsset(
    'bld-real-ir-windcatcher',
    'Persian Windcatcher Tower & Bazaar (Badgir)',
    'Realistic Buildings',
    'Yazd ancient desert architecture featuring tall natural ventilation windcatchers (badgir), mudbrick adobe walls, and geometric dome vaults.',
    'PERSIAN WINDCATCHER',
    'bg-yellow-800/20 text-yellow-300 border-yellow-600/30',
    '🏺',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#854d0e',
    0.90,
    ['realistic building', 'architecture', 'iran', 'persia', 'windcatcher', 'badgir', 'adobe', 'bazaar', 'desert']
  ),
  createRealAsset(
    'bld-real-ar-desert-qasr',
    'Arabian Desert Adobe Fortress (Qasr)',
    'Realistic Buildings',
    'Sun-dried clay mudbrick fortified desert castle with crenelated watchtowers, heavy wooden gates, and triangular decorative ventilation slits.',
    'ARABIAN QASR',
    'bg-amber-700/20 text-amber-300 border-amber-500/30',
    '🏰',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#b45309',
    0.92,
    ['realistic building', 'architecture', 'arabia', 'qasr', 'fortress', 'castle', 'desert', 'clay', 'middle east']
  ),
  createRealAsset(
    'bld-real-eg-pylon-temple',
    'Ancient Egyptian Karnak Pylon Gateway',
    'Realistic Buildings',
    'Monumental sloping stone temple gateway carved with hieroglyphic reliefs, winged solar disc cornice, and granite obelisk pedestals.',
    'EGYPTIAN PYLON',
    'bg-yellow-600/20 text-yellow-300 border-yellow-400/30',
    '🏛️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#ca8a04',
    0.94,
    ['realistic building', 'architecture', 'egypt', 'pylon', 'temple', 'ancient', 'pharaoh', 'stone', 'hieroglyph']
  ),

  // AFRICA
  createRealAsset(
    'bld-real-af-djenne-adobe',
    'Great Sudano-Sahelian Adobe Clay Mosque',
    'Realistic Buildings',
    'Earth architecture masterpiece inspired by the Great Mosque of Djenné, built from sun-baked earthen bricks with protruding palm toron beams.',
    'SAHELIAN ADOBE',
    'bg-amber-800/20 text-amber-300 border-amber-600/30',
    '🕌',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#92400e',
    0.94,
    ['realistic building', 'architecture', 'africa', 'mali', 'djenne', 'adobe', 'sahel', 'clay', 'heritage']
  ),
  createRealAsset(
    'bld-real-af-nubian-vault',
    'Nubian Earthen Mudbrick Vault Dwelling',
    'Realistic Buildings',
    'Traditional vaulted earth home from the Nile Valley utilizing timberless arched mudbrick masonry and vibrant geometric front facade murals.',
    'NUBIAN VAULT',
    'bg-orange-800/20 text-orange-300 border-orange-600/30',
    '🛖',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#9a3412',
    0.82,
    ['realistic building', 'architecture', 'africa', 'nubia', 'egypt', 'sudan', 'earth', 'vault', 'dwelling']
  ),

  // SOUTH & SOUTHEAST ASIA
  createRealAsset(
    'bld-real-in-haveli-palace',
    'Rajasthan Mughal Palace & Haveli',
    'Realistic Buildings',
    'Indian royal mansion featuring carved red sandstone jharokha overhanging balconies, chhatri rooftop pavilions, and cusped arches.',
    'RAJASTHAN HAVELI',
    'bg-pink-700/20 text-pink-300 border-pink-500/30',
    '🕌',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#be185d',
    0.92,
    ['realistic building', 'architecture', 'india', 'rajasthan', 'mughal', 'haveli', 'palace', 'sandstone', 'asia']
  ),
  createRealAsset(
    'bld-real-id-balinese-bale',
    'Balinese Bale Pavilion & Thatched Sanctuary',
    'Realistic Buildings',
    'Indonesian open-sided timber sanctuary with Alang-Alang grass thatched roof, carved teak columns, and volcanic stone base.',
    'BALINESE BALE',
    'bg-emerald-700/20 text-emerald-300 border-emerald-500/30',
    '🛖',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#047857',
    0.80,
    ['realistic building', 'architecture', 'bali', 'indonesia', 'pavilion', 'thatched', 'timber', 'tropical', 'asia']
  ),

  // AMERICAS & MODERN
  createRealAsset(
    'bld-real-us-manhattan-skyscraper',
    'Manhattan Glass Curtain High-Rise Tower',
    'Realistic Buildings',
    'Contemporary commercial skyscraper with tinted reflective glass curtain walls, structural steel mullions, and helipad crown.',
    'MANHATTAN TOWER',
    'bg-sky-700/20 text-sky-300 border-sky-500/30',
    '🏙️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#0369a1',
    0.98,
    ['realistic building', 'architecture', 'skyscraper', 'tower', 'glass', 'modern', 'new york', 'city', 'highrise']
  ),
  createRealAsset(
    'bld-real-us-nyc-brownstone',
    'New York Classic Brownstone Townhouse',
    'Realistic Buildings',
    'Iconic 19th-century Brooklyn sandstone residential rowhouse featuring high entrance stoop, heavy carved cornice, and ornate iron railings.',
    'NYC BROWNSTONE',
    'bg-amber-900/20 text-amber-300 border-amber-700/30',
    '🏢',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#78350f',
    0.86,
    ['realistic building', 'architecture', 'usa', 'new york', 'brownstone', 'townhouse', 'stoop', 'brooklyn', 'urban']
  ),
  createRealAsset(
    'bld-real-us-art-deco-spire',
    'Art Deco Geometric Spire Skyscraper',
    'Realistic Buildings',
    '1930s Chrysler-inspired skyscraper with stepped setbacks, stainless steel sunburst crown, eagle gargoyles, and geometric granite facade.',
    'ART DECO SPIRE',
    'bg-zinc-500/20 text-zinc-300 border-zinc-400/30',
    '🌆',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#71717a',
    0.96,
    ['realistic building', 'architecture', 'art deco', 'skyscraper', 'spire', 'chrysler', 'vintage', 'new york', 'tower']
  ),
  createRealAsset(
    'bld-real-latam-hacienda',
    'Latin American Spanish Colonial Hacienda',
    'Realistic Buildings',
    'Colonial Mexican estate manor with white stucco perimeter, arcaded peristyle courtyard, terracotta roofing, and wrought-iron window grilles.',
    'COLONIAL HACIENDA',
    'bg-orange-700/20 text-orange-300 border-orange-500/30',
    '🏡',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#c2410c',
    0.88,
    ['realistic building', 'architecture', 'mexico', 'latin america', 'hacienda', 'colonial', 'courtyard', 'estate']
  ),
  createRealAsset(
    'bld-real-pe-inca-stone-temple',
    'Peruvian Incan Ashlar Megalithic Temple',
    'Realistic Buildings',
    'Sacred Andean temple constructed from perfectly fitted polygonal ashlar granite blocks without mortar, featuring trapezoidal doorways.',
    'INCAN STONE TEMPLE',
    'bg-stone-600/20 text-stone-300 border-stone-500/30',
    '🏛️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#57534e',
    0.90,
    ['realistic building', 'architecture', 'peru', 'inca', 'andes', 'stone', 'ashlar', 'machu picchu', 'temple']
  ),
  createRealAsset(
    'bld-real-modern-bauhaus',
    'Modernist Bauhaus Concrete & Glass Pavilion',
    'Realistic Buildings',
    'International Style architectural pavilion featuring cantilevered reinforced concrete planes, floor-to-ceiling glass walls, and minimalist geometry.',
    'BAUHAUS VILLA',
    'bg-slate-600/20 text-slate-300 border-slate-400/30',
    '🏢',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#475569',
    0.88,
    ['realistic building', 'architecture', 'modern', 'bauhaus', 'minimalist', 'concrete', 'glass', 'contemporary']
  ),
  createRealAsset(
    'bld-real-ind-brick-factory',
    'Industrial Revolution Brick Factory & Smokestack',
    'Realistic Buildings',
    '19th-century red-brick manufacturing warehouse with saw-tooth clerestory roof, steel multi-pane windows, and tall tapered brick chimney stack.',
    'INDUSTRIAL FACTORY',
    'bg-red-900/20 text-red-300 border-red-700/30',
    '🏭',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#7f1d1d',
    0.90,
    ['realistic building', 'architecture', 'industrial', 'factory', 'brick', 'warehouse', 'smokestack', 'vintage']
  ),
  createRealAsset(
    'bld-real-cyber-neo-tokyo',
    'Neo-Tokyo Cyberpunk Modular Habitation Tower',
    'Realistic Buildings',
    'Futuristic high-density megacity skyscraper with stacked modular living capsules, exterior utility conduits, and integrated holographic billboard mounts.',
    'CYBERPUNK TOWER',
    'bg-fuchsia-700/20 text-fuchsia-300 border-fuchsia-500/30',
    '🏙️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#a21caf',
    0.96,
    ['realistic building', 'architecture', 'cyberpunk', 'futuristic', 'sci-fi', 'tokyo', 'capsule', 'tower', 'neon']
  ),
  createRealAsset(
    'bld-real-no-fjord-cabin',
    'Nordic Modern Fjord Cabin with Turf Green Roof',
    'Realistic Buildings',
    'Contemporary Scandinavian coastal cabin with dark charred timber siding, panoramic fjord-facing glass front, and natural green grass roof.',
    'FJORD TURF CABIN',
    'bg-emerald-800/20 text-emerald-300 border-emerald-600/30',
    '🏡',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#065f46',
    0.84,
    ['realistic building', 'architecture', 'nordic', 'norway', 'fjord', 'cabin', 'turf', 'green roof', 'modern']
  ),
  createRealAsset(
    'bld-real-us-prairie-mcm',
    'Mid-Century Modern Prairie Residence',
    'Realistic Buildings',
    'Frank Lloyd Wright-inspired residential villa with low horizontal lines, broad cantilevered eaves, open floor plan, and clerestory bands.',
    'PRAIRIE RESIDENCE',
    'bg-stone-600/20 text-stone-300 border-stone-500/30',
    '🏡',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#57534e',
    0.86,
    ['realistic building', 'architecture', 'mid-century', 'prairie', 'usa', 'modern', 'house', 'villa', 'stone']
  ),
  createRealAsset(
    'bld-real-eu-gothic-cathedral',
    'Gothic Flying Buttress Cathedral Spire',
    'Realistic Buildings',
    'Medieval Gothic cathedral featuring exterior flying buttresses, ribbed groin vaults, pointed lancet stained-glass windows, and soaring central bell spire.',
    'GOTHIC CATHEDRAL',
    'bg-indigo-800/20 text-indigo-300 border-indigo-600/30',
    '⛪',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#3730a3',
    0.98,
    ['realistic building', 'architecture', 'gothic', 'cathedral', 'spire', 'medieval', 'stone', 'europe', 'monument']
  )
];

// ============================================================================
// 2. CARTOON & STYLIZED BUILDINGS (35+ whimsical, low-poly & stylized buildings)
// ============================================================================
export const CARTOON_BUILDINGS_ASSETS: Real3DAsset[] = [
  // CUTE & COZY SHOPS
  createRealAsset(
    'bld-toon-bakery',
    'Toon Cozy French Bakery & Patisserie',
    'Cartoon Buildings',
    'Charming cartoon village bakery with pastel pink tiled roof, giant butter croissant storefront sign, and warm glowing display windows.',
    'TOON BAKERY',
    'bg-pink-500/20 text-pink-300 border-pink-400/30',
    '🥐',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#ec4899',
    0.80,
    ['cartoon building', 'toon', 'bakery', 'croissant', 'cute', 'shop', 'pastel', 'village', 'stylized']
  ),
  createRealAsset(
    'bld-toon-jp-ramen',
    'Toon Japanese Anime Ramen Shop',
    'Cartoon Buildings',
    'Anime-style ramen izakaya shop with red paper lanterns, wooden noren curtains, steaming giant ramen bowl on the roof, and neon kanji signs.',
    'TOON RAMEN SHOP',
    'bg-red-500/20 text-red-300 border-red-400/30',
    '🍜',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#ef4444',
    0.82,
    ['cartoon building', 'toon', 'ramen', 'japan', 'anime', 'lantern', 'shop', 'restaurant', 'stylized']
  ),
  createRealAsset(
    'bld-toon-it-pizzeria',
    'Toon Wood-Fired Italian Pizzeria',
    'Cartoon Buildings',
    'Whimsical cartoon Italian pizzeria with red-and-white checkered awning, brick pizza oven chimney, and giant pepperoni slice roof emblem.',
    'TOON PIZZERIA',
    'bg-amber-500/20 text-amber-300 border-amber-400/30',
    '🍕',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#f59e0b',
    0.82,
    ['cartoon building', 'toon', 'pizza', 'italy', 'restaurant', 'food', 'chef', 'cute', 'stylized']
  ),
  createRealAsset(
    'bld-toon-diner-50s',
    'Toon Retro 1950s Neon Drive-In Diner',
    'Cartoon Buildings',
    'Stylized retro chrome diner with turquoise and pink neon lighting, giant milkshake spinner cup, and checkerboard floor portal.',
    'TOON RETRO DINER',
    'bg-cyan-500/20 text-cyan-300 border-cyan-400/30',
    '🍔',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#06b6d4',
    0.84,
    ['cartoon building', 'toon', 'diner', 'retro', 'neon', '50s', 'burger', 'milkshake', 'stylized']
  ),
  createRealAsset(
    'bld-toon-paris-flower',
    'Toon Parisian Boutique Flower Shop',
    'Cartoon Buildings',
    'Charming stylized Parisian florist with striped mint green awning, tiered outdoor flower carts, and blooming window flower boxes.',
    'TOON FLOWER SHOP',
    'bg-emerald-500/20 text-emerald-300 border-emerald-400/30',
    '🌸',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#10b981',
    0.80,
    ['cartoon building', 'toon', 'flowers', 'paris', 'shop', 'garden', 'florist', 'cute', 'stylized']
  ),
  createRealAsset(
    'bld-toon-cheese-chalet',
    'Toon Alpine Cheese & Fondue Chalet',
    'Cartoon Buildings',
    'Whimsical cartoon mountain chalet with Swiss cheese-wheel shutters, bubbling fondue pot roof finial, and cheerful timber framing.',
    'TOON CHEESE CHALET',
    'bg-yellow-500/20 text-yellow-300 border-yellow-400/30',
    '🧀',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#eab308',
    0.82,
    ['cartoon building', 'toon', 'cheese', 'chalet', 'swiss', 'alps', 'cozy', 'stylized']
  ),
  createRealAsset(
    'bld-toon-mexican-cantina',
    'Toon Fiesta Mexican Cantina & Taco Stand',
    'Cartoon Buildings',
    'Festive cartoon cantina with bright yellow adobe walls, multi-colored papel picado flags, giant sombrero sign, and cactus garden.',
    'TOON FIESTA CANTINA',
    'bg-orange-500/20 text-orange-300 border-orange-400/30',
    '🌮',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#f97316',
    0.82,
    ['cartoon building', 'toon', 'mexican', 'cantina', 'taco', 'fiesta', 'sombrero', 'stylized']
  ),

  // FANTASY & MAGIC
  createRealAsset(
    'bld-toon-wizard-tower',
    'Toon Arcane Wizard Tower with Floating Orbs',
    'Cartoon Buildings',
    'Spiral fantasy wizard tower with crooked conical purple hat roof, glowing magical crystal spires, and orbiting mystical energy runes.',
    'WIZARD TOWER',
    'bg-purple-600/20 text-purple-300 border-purple-400/30',
    '🧙',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#9333ea',
    0.92,
    ['cartoon building', 'toon', 'wizard', 'magic', 'tower', 'fantasy', 'crystal', 'arcane', 'stylized']
  ),
  createRealAsset(
    'bld-toon-mushroom-cottage',
    'Toon Whimsical Red Mushroom Cottage',
    'Cartoon Buildings',
    'Fairy-tale forest cottage built into a giant red mushroom with white spots, tiny wooden door, chimney with heart-shaped smoke puffs, and flower patch.',
    'MUSHROOM COTTAGE',
    'bg-rose-500/20 text-rose-300 border-rose-400/30',
    '🍄',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#f43f5e',
    0.80,
    ['cartoon building', 'toon', 'mushroom', 'cottage', 'fairy', 'fantasy', 'forest', 'cute', 'stylized']
  ),
  createRealAsset(
    'bld-toon-fairy-castle',
    'Toon Princess Fairy Tale Castle',
    'Cartoon Buildings',
    'Magical pastel castle with spiral pink turrets, sparkling golden flag banners, arched royal drawbridge, and rainbow sparkle motes.',
    'FAIRY CASTLE',
    'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-400/30',
    '🏰',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#d946ef',
    0.94,
    ['cartoon building', 'toon', 'castle', 'princess', 'fairy tale', 'pink', 'royal', 'magic', 'stylized']
  ),
  createRealAsset(
    'bld-toon-gingerbread-house',
    'Toon Candy Gingerbread Holiday House',
    'Cartoon Buildings',
    'Delicious holiday cottage made of gingerbread biscuit walls, white royal icing roof snow, peppermint candy cane columns, and gumdrop pavers.',
    'GINGERBREAD HOUSE',
    'bg-amber-600/20 text-amber-300 border-amber-400/30',
    '🍭',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#d97706',
    0.82,
    ['cartoon building', 'toon', 'candy', 'gingerbread', 'holiday', 'christmas', 'sweets', 'cute', 'stylized']
  ),
  createRealAsset(
    'bld-toon-cloud-castle',
    'Toon Flying Cloud Kingdom Palace',
    'Cartoon Buildings',
    'Heavenly floating castle perched upon fluffy white cumulus clouds with golden spires, winged battlements, and rainbow bridge arch.',
    'CLOUD KINGDOM',
    'bg-sky-400/20 text-sky-300 border-sky-300/30',
    '☁️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#38bdf8',
    0.95,
    ['cartoon building', 'toon', 'cloud', 'flying', 'sky', 'floating', 'kingdom', 'rainbow', 'stylized']
  ),
  createRealAsset(
    'bld-toon-treehouse-cabin',
    'Toon Cozy Forest Treehouse & Rope Bridge',
    'Cartoon Buildings',
    'Whimsical wooden treehouse perched inside a giant leafy oak tree, featuring rope bridge, tire swing, and telescope lookout tower.',
    'TREEHOUSE CABIN',
    'bg-lime-600/20 text-lime-300 border-lime-400/30',
    '🌳',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#65a30d',
    0.88,
    ['cartoon building', 'toon', 'treehouse', 'tree', 'cabin', 'adventure', 'wood', 'nature', 'stylized']
  ),
  createRealAsset(
    'bld-toon-haunted-manor',
    'Toon Spooky Haunted Ghost Manor',
    'Cartoon Buildings',
    'Cute crooked gothic manor with purple roof tiles, glowing green windows, bat weather vane, and friendly floating ghost sprites.',
    'HAUNTED MANOR',
    'bg-violet-700/20 text-violet-300 border-violet-500/30',
    '👻',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#6d28d9',
    0.86,
    ['cartoon building', 'toon', 'haunted', 'ghost', 'halloween', 'spooky', 'cute', 'gothic', 'stylized']
  ),

  // CULTURAL & REGIONAL TOON
  createRealAsset(
    'bld-toon-wild-west-saloon',
    'Toon Wild West Frontier Saloon',
    'Cartoon Buildings',
    'Classic cartoon cowboy saloon with wooden swinging batwing doors, hitching post, horse trough, and tall frontier false-front facade.',
    'WESTERN SALOON',
    'bg-yellow-700/20 text-yellow-300 border-yellow-500/30',
    '🤠',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#a16207',
    0.84,
    ['cartoon building', 'toon', 'western', 'saloon', 'cowboy', 'wild west', 'frontier', 'wood', 'stylized']
  ),
  createRealAsset(
    'bld-toon-dutch-windmill',
    'Toon Colorful Dutch Windmill',
    'Cartoon Buildings',
    'Charming cartoon windmill with rotating four-blade sails, round brick base, thatch cap, and surrounding colorful tulip flower beds.',
    'TOON WINDMILL',
    'bg-teal-500/20 text-teal-300 border-teal-400/30',
    '💨',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#14b8a6',
    0.86,
    ['cartoon building', 'toon', 'windmill', 'dutch', 'netherlands', 'tulips', 'farm', 'stylized']
  ),
  createRealAsset(
    'bld-toon-coastal-lighthouse',
    'Toon Candy-Striped Coastal Lighthouse',
    'Cartoon Buildings',
    'Cheerful nautical lighthouse with bold red-and-white candy stripes, keeper cottage, rotating lantern room, and rocky wave base.',
    'TOON LIGHTHOUSE',
    'bg-blue-500/20 text-blue-300 border-blue-400/30',
    '🏮',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#3b82f6',
    0.88,
    ['cartoon building', 'toon', 'lighthouse', 'nautical', 'sea', 'coast', 'ocean', 'stripes', 'stylized']
  ),
  createRealAsset(
    'bld-toon-viking-hall',
    'Toon Viking Mead Hall & Dragon Crest',
    'Cartoon Buildings',
    'Stylized Norse timber longhouse with crossed battle-axe crests, carved dragon head beams, round wooden shields, and turf roof.',
    'VIKING MEAD HALL',
    'bg-amber-700/20 text-amber-300 border-amber-500/30',
    '🛡️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#b45309',
    0.86,
    ['cartoon building', 'toon', 'viking', 'norse', 'hall', 'longhouse', 'shields', 'dragon', 'stylized']
  ),
  createRealAsset(
    'bld-toon-tiki-beach-hut',
    'Toon Tropical Tiki Beach Hut & Surfboard',
    'Cartoon Buildings',
    'Hawaiian-style bamboo beach hut with thick palm frond thatch, carved cheerful Tiki mask totems, and neon surfboard props.',
    'TIKI BEACH HUT',
    'bg-emerald-600/20 text-emerald-300 border-emerald-400/30',
    '🗿',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#059669',
    0.80,
    ['cartoon building', 'toon', 'tiki', 'beach', 'tropical', 'surf', 'hawaii', 'bamboo', 'hut', 'stylized']
  ),
  createRealAsset(
    'bld-toon-arabian-tent',
    'Toon Arabian Magic Carpet Bazaar Tent',
    'Cartoon Buildings',
    'Stylized Arabian desert pavilion tent with silk draping in purple and gold, tasseled valances, golden urns, and magic flying carpets.',
    'ARABIAN BAZAAR TENT',
    'bg-purple-600/20 text-purple-300 border-purple-400/30',
    '⛺',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#7c3aed',
    0.84,
    ['cartoon building', 'toon', 'arabian', 'tent', 'bazaar', 'desert', 'magic carpet', 'silk', 'stylized']
  ),
  createRealAsset(
    'bld-toon-asia-dimsum',
    'Toon Dim Sum Tea House & Steamer Pagoda',
    'Cartoon Buildings',
    'Adorable Asian tea house with tiered bamboo dumpling steamer pots, gold coins, red good luck tassels, and jade green roof eaves.',
    'TOON DIM SUM HOUSE',
    'bg-red-600/20 text-red-300 border-red-400/30',
    '🥟',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#dc2626',
    0.84,
    ['cartoon building', 'toon', 'dim sum', 'dumpling', 'tea house', 'china', 'pagoda', 'asia', 'stylized']
  ),
  createRealAsset(
    'bld-toon-medieval-forge',
    'Toon Medieval Blacksmith Forge & Anvil',
    'Cartoon Buildings',
    'Stylized stone blacksmith workshop with glowing fiery furnace, bellows, giant anvil roof ornament, and water cooling trough.',
    'TOON BLACKSMITH',
    'bg-orange-700/20 text-orange-300 border-orange-500/30',
    '⚒️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#c2410c',
    0.82,
    ['cartoon building', 'toon', 'blacksmith', 'forge', 'medieval', 'anvil', 'fire', 'craft', 'stylized']
  ),
  createRealAsset(
    'bld-toon-aztec-sun-temple',
    'Toon Aztec Sun God Step Pyramid',
    'Cartoon Buildings',
    'Cute stepped stone pyramid with golden sun disc emblem, carved serpent balustrades, and ceremonial torch pedestals.',
    'TOON AZTEC TEMPLE',
    'bg-amber-600/20 text-amber-300 border-amber-400/30',
    '☀️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#d97706',
    0.88,
    ['cartoon building', 'toon', 'aztec', 'pyramid', 'sun', 'temple', 'maya', 'stone', 'stylized']
  ),
  createRealAsset(
    'bld-toon-nordic-fishery',
    'Toon Fjord Stilt Fishery Shack',
    'Cartoon Buildings',
    'Bright red wooden Scandinavian fishing hut perched on wooden water stilts with fish drying racks and lifebuoy ring.',
    'TOON FJORD SHACK',
    'bg-red-500/20 text-red-300 border-red-400/30',
    '🐟',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#ef4444',
    0.80,
    ['cartoon building', 'toon', 'fjord', 'fishing', 'shack', 'stilt', 'norway', 'red', 'stylized']
  ),
  createRealAsset(
    'bld-toon-jp-teahouse',
    'Toon Zen Garden Tea House & Koi Pond',
    'Cartoon Buildings',
    'Charming Japanese garden pavilion with bamboo water spout, miniature bonsai tree, koi fish pool, and sliding tatami room.',
    'TOON ZEN TEA HOUSE',
    'bg-emerald-700/20 text-emerald-300 border-emerald-500/30',
    '🍵',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#047857',
    0.82,
    ['cartoon building', 'toon', 'tea house', 'zen', 'bonsai', 'japan', 'koi', 'garden', 'stylized']
  ),

  // SCI-FI, ADVENTURE & CIVIC TOON
  createRealAsset(
    'bld-toon-space-dome',
    'Toon Sci-Fi Planetary Biosphere Dome',
    'Cartoon Buildings',
    'Futuristic cartoon planetary habitat with glowing cyan hexagonal dome shield, airlock tunnel, communication dish, and oxygen tanks.',
    'TOON BIO-DOME',
    'bg-cyan-600/20 text-cyan-300 border-cyan-400/30',
    '🚀',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#0891b2',
    0.88,
    ['cartoon building', 'toon', 'sci-fi', 'space', 'dome', 'habitat', 'mars', 'futuristic', 'stylized']
  ),
  createRealAsset(
    'bld-toon-cyber-arcade',
    'Toon Neon Cyberpunk Arcade & Capsule Shop',
    'Cartoon Buildings',
    'Vibrant cartoon arcade building packed with retro claw machines, pixel sprite marquee, neon drink dispenser, and joystick rooftop sign.',
    'TOON NEON ARCADE',
    'bg-fuchsia-600/20 text-fuchsia-300 border-fuchsia-400/30',
    '🕹️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#c026d3',
    0.86,
    ['cartoon building', 'toon', 'arcade', 'cyberpunk', 'neon', 'gaming', 'retro', 'pixel', 'stylized']
  ),
  createRealAsset(
    'bld-toon-steampunk-clock',
    'Toon Steampunk Brass Clockwork Spire',
    'Cartoon Buildings',
    'Stylized Victorian brass clock tower with spinning mechanical cogs, steam exhaust pipes, pressure gauges, and ornate copper dome.',
    'TOON CLOCK TOWER',
    'bg-amber-700/20 text-amber-300 border-amber-500/30',
    '⚙️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#b45309',
    0.92,
    ['cartoon building', 'toon', 'steampunk', 'clock', 'brass', 'gears', 'victorian', 'cogs', 'stylized']
  ),
  createRealAsset(
    'bld-toon-spaceport-hangar',
    'Toon Rocket Launch Hangar & Gantry',
    'Cartoon Buildings',
    'Stylized spaceport launch facility with retractable bay doors, rocket gantry crane, radar dish, and cartoon launch countdown display.',
    'TOON SPACEPORT',
    'bg-indigo-600/20 text-indigo-300 border-indigo-400/30',
    '🛸',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#4f46e5',
    0.90,
    ['cartoon building', 'toon', 'spaceport', 'rocket', 'hangar', 'sci-fi', 'launch', 'gantry', 'stylized']
  ),
  createRealAsset(
    'bld-toon-firehouse',
    'Toon Red Firehouse Station & Brass Bell',
    'Cartoon Buildings',
    'Iconic cartoon red brick fire station with double garage doors, sliding fire pole tower, and shiny gold emergency bell.',
    'TOON FIREHOUSE',
    'bg-red-600/20 text-red-300 border-red-400/30',
    '🚒',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#dc2626',
    0.86,
    ['cartoon building', 'toon', 'firehouse', 'firefighter', 'red', 'station', 'garage', 'city', 'stylized']
  ),
  createRealAsset(
    'bld-toon-town-hall',
    'Toon Town Hall with Golden Bell Tower',
    'Cartoon Buildings',
    'Whimsical civic town hall with grand pillared entrance, friendly clock face, rooftop weather vane rooster, and flowering town square.',
    'TOON TOWN HALL',
    'bg-blue-600/20 text-blue-300 border-blue-400/30',
    '🏛️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#2563eb',
    0.88,
    ['cartoon building', 'toon', 'town hall', 'civic', 'clock', 'village', 'pillars', 'cute', 'stylized']
  ),
  createRealAsset(
    'bld-toon-igloo-fortress',
    'Toon Arctic Igloo & Ice Crystal Palace',
    'Cartoon Buildings',
    'Charming cartoon ice block igloo with glowing blue thermal entrance tunnel, carved ice battlements, and warm lantern smoke stack.',
    'TOON ARCTIC IGLOO',
    'bg-sky-300/20 text-sky-200 border-sky-300/40',
    '❄️',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#0ea5e9',
    0.80,
    ['cartoon building', 'toon', 'igloo', 'ice', 'arctic', 'winter', 'snow', 'cold', 'stylized']
  ),
  createRealAsset(
    'bld-toon-sub-lab',
    'Toon Undersea Submarine Lab & Bubble Portals',
    'Cartoon Buildings',
    'Underwater cartoon research outpost with yellow submarine hull, bubble glass viewports, coral reef anchor feet, and periscope antenna.',
    'TOON SUB LAB',
    'bg-yellow-600/20 text-yellow-300 border-yellow-400/30',
    '🌊',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#ca8a04',
    0.84,
    ['cartoon building', 'toon', 'underwater', 'submarine', 'ocean', 'lab', 'bubbles', 'yellow', 'stylized']
  ),
  createRealAsset(
    'bld-toon-desert-pyramid',
    'Toon Desert Pyramid with Glowing Eye of Horus',
    'Cartoon Buildings',
    'Stylized golden sandstone pyramid with jewel-topped capstone, carved hieroglyphic icons, and palm oasis fountain.',
    'TOON DESERT PYRAMID',
    'bg-amber-500/20 text-amber-300 border-amber-400/30',
    '🏺',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#f59e0b',
    0.86,
    ['cartoon building', 'toon', 'pyramid', 'egypt', 'desert', 'gold', 'ancient', 'oasis', 'stylized']
  ),
  createRealAsset(
    'bld-toon-observatory',
    'Toon Stargazer Dome Observatory',
    'Cartoon Buildings',
    'Whimsical mountaintop observatory with rotating copper dome, large cartoon telescope poking out, and star chart weather vane.',
    'TOON OBSERVATORY',
    'bg-indigo-700/20 text-indigo-300 border-indigo-500/30',
    '🔭',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#4338ca',
    0.84,
    ['cartoon building', 'toon', 'observatory', 'telescope', 'stars', 'space', 'dome', 'science', 'stylized']
  )
];

// ============================================================================
// 3. COMBINED BUILDING ASSETS COLLECTION
// ============================================================================
export const BUILDING_ASSETS: Real3DAsset[] = [
  ...REALISTIC_BUILDINGS_ASSETS,
  ...CARTOON_BUILDINGS_ASSETS
];
