import { Real3DAsset, createRealAsset, BASE_ITEM_URL, BASE_KHRONOS_URL } from './types';

export const ELECTRONICS_ASSETS: Real3DAsset[] = [
  createRealAsset(
    'elec-computer-workstation',
    'Desktop PC Workstation',
    'Electronics',
    'High-performance desktop computer workstation with monitor, keyboard, and tower.',
    'DESKTOP PC',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🖥️',
    `${BASE_ITEM_URL}/computer/thumbnail.webp`,
    `${BASE_ITEM_URL}/computer/model.glb`,
    '#2563eb',
    0.45,
    ['computer', 'pc', 'monitor', 'desktop', 'tech', 'workstation']
  ),
  createRealAsset(
    'elec-television-flat',
    'Ultra HD Smart TV',
    'Electronics',
    'Slim 4K OLED Smart Television with minimalist aluminum stand.',
    'SMART TV',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '📺',
    `${BASE_ITEM_URL}/television/thumbnail.webp`,
    `${BASE_ITEM_URL}/television/model.glb`,
    '#1d4ed8',
    0.65,
    ['tv', 'television', 'screen', 'display', 'smart tv', 'home theater']
  ),
  createRealAsset(
    'elec-flatscreen-wall-tv',
    'Wall-Mounted Display TV',
    'Electronics',
    'Large format commercial flat-panel display screen for interactive AR signage.',
    'WALL DISPLAY',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '📺',
    `${BASE_ITEM_URL}/flat-screen-tv/thumbnail.webp`,
    `${BASE_ITEM_URL}/flat-screen-tv/model.glb`,
    '#3b82f6',
    0.70,
    ['tv', 'screen', 'display', 'monitor', 'video']
  ),
  createRealAsset(
    'elec-stereo-speaker',
    'Hi-Fi Studio Monitor Speaker',
    'Electronics',
    'Acoustic studio reference monitor speaker with exposed drivers.',
    'HI-FI AUDIO',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🔊',
    `${BASE_ITEM_URL}/stereo-speaker/thumbnail.webp`,
    `${BASE_ITEM_URL}/stereo-speaker/model.glb`,
    '#6366f1',
    0.35,
    ['speaker', 'audio', 'sound', 'studio', 'music', 'hifi']
  ),
  createRealAsset(
    'elec-boombox',
    'Retro BoomBox Sound System',
    'Electronics',
    'Classic twin-speaker portable stereo boombox with cassette deck.',
    'BOOMBOX',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '📻',
    `${BASE_KHRONOS_URL}/BoomBox/glTF-Binary/BoomBox.glb`,
    `${BASE_KHRONOS_URL}/BoomBox/glTF-Binary/BoomBox.glb`,
    '#4f46e5',
    0.38,
    ['boombox', 'radio', 'audio', 'retro', 'music']
  ),
  createRealAsset(
    'elec-alarm-keypad',
    'Smart Security Touch Keypad',
    'Electronics',
    'Digital smart home security wall keypad with backlit controls.',
    'SECURITY',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🔢',
    `${BASE_ITEM_URL}/alarm-keypad/thumbnail.webp`,
    `${BASE_ITEM_URL}/alarm-keypad/model.glb`,
    '#0284c7',
    0.20,
    ['security', 'keypad', 'smart home', 'alarm', 'controller']
  ),
  createRealAsset(
    'elec-thermostat',
    'Smart Digital Thermostat',
    'Electronics',
    'Circular wall-mounted smart climate control thermostat with OLED ring display.',
    'THERMOSTAT',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🌡️',
    `${BASE_ITEM_URL}/thermostat/thumbnail.webp`,
    `${BASE_ITEM_URL}/thermostat/model.glb`,
    '#06b6d4',
    0.18,
    ['thermostat', 'iot', 'smart home', 'climate', 'temperature']
  ),
  createRealAsset(
    'elec-smoke-detector',
    'IoT Smoke & Hazard Sensor',
    'Electronics',
    'Ceiling-mounted photoelectric smoke and air quality sensor unit.',
    'SMART SENSOR',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '🚨',
    `${BASE_ITEM_URL}/smoke-detector/thumbnail.webp`,
    `${BASE_ITEM_URL}/smoke-detector/model.glb`,
    '#0ea5e9',
    0.18,
    ['smoke detector', 'sensor', 'iot', 'safety', 'hazard']
  ),
  createRealAsset(
    'elec-fire-alarm',
    'Commercial Fire Alarm Strobe',
    'Electronics',
    'Red emergency audio-visual strobe horn unit for architectural facilities.',
    'ALARM STROBE',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🔔',
    `${BASE_ITEM_URL}/fire-alarm/thumbnail.webp`,
    `${BASE_ITEM_URL}/fire-alarm/model.glb`,
    '#dc2626',
    0.20,
    ['alarm', 'fire alarm', 'emergency', 'sensor', 'strobe']
  ),
  createRealAsset(
    'elec-fire-detector',
    'Optical Heat & Flame Detector',
    'Electronics',
    'Precision industrial infrared flame and thermal threshold detector.',
    'FLAME SENSOR',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🔥',
    `${BASE_ITEM_URL}/fire-detector/thumbnail.webp`,
    `${BASE_ITEM_URL}/fire-detector/model.glb`,
    '#d97706',
    0.18,
    ['detector', 'fire', 'heat', 'sensor']
  ),
  createRealAsset(
    'elec-ev-wall-charger',
    'Electric Vehicle Wallbox Charger',
    'Electronics',
    'High-power 22kW smart EV wallbox fast-charging station with tethered cable.',
    'EV CHARGER',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '⚡',
    `${BASE_ITEM_URL}/ev-wall-charger/thumbnail.webp`,
    `${BASE_ITEM_URL}/ev-wall-charger/model.glb`,
    '#10b981',
    0.40,
    ['ev', 'charger', 'electric vehicle', 'energy', 'power', 'wallbox']
  ),
  createRealAsset(
    'elec-electric-panel',
    'Smart Circuit Breaker Panel',
    'Electronics',
    'Industrial grade modular electrical distribution panel with sub-meters.',
    'BREAKER PANEL',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🎛️',
    `${BASE_ITEM_URL}/electric-panel/thumbnail.webp`,
    `${BASE_ITEM_URL}/electric-panel/model.glb`,
    '#475569',
    0.48,
    ['electrical', 'power', 'panel', 'breaker', 'utility', 'grid']
  ),
  createRealAsset(
    'elec-exit-sign',
    'Illuminated LED Exit Sign',
    'Electronics',
    'Emergency architectural illuminated LED green exit luminaire.',
    'EXIT SIGN',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🚪',
    `${BASE_ITEM_URL}/exit-sign/thumbnail.webp`,
    `${BASE_ITEM_URL}/exit-sign/model.glb`,
    '#059669',
    0.28,
    ['exit', 'sign', 'led', 'light', 'emergency', 'facility']
  ),
  createRealAsset(
    'elec-antique-camera',
    'Retro Optical Camera',
    'Electronics',
    'Vintage analog optical camera with mechanical shutter and twin glass lenses.',
    'RETRO CAMERA',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '📷',
    `${BASE_KHRONOS_URL}/AntiqueCamera/glTF-Binary/AntiqueCamera.glb`,
    `${BASE_KHRONOS_URL}/AntiqueCamera/glTF-Binary/AntiqueCamera.glb`,
    '#d97706',
    0.32,
    ['camera', 'photo', 'optical', 'lens', 'vintage', 'electronics']
  ),
  createRealAsset(
    'elec-lantern',
    'Electric Metal Lantern',
    'Electronics',
    'Heavy-duty industrial electric LED lantern with protective cage.',
    'LED LANTERN',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🏮',
    `${BASE_KHRONOS_URL}/Lantern/glTF-Binary/Lantern.glb`,
    `${BASE_KHRONOS_URL}/Lantern/glTF-Binary/Lantern.glb`,
    '#ca8a04',
    0.34,
    ['lantern', 'lamp', 'light', 'electric', 'industrial']
  ),
  createRealAsset(
    'elec-ceiling-fan',
    'Aero Dynamic Ceiling Fan',
    'Electronics',
    'Modern 3-blade electric ceiling fan with integrated center downlight.',
    'CEILING FAN',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🌀',
    `${BASE_ITEM_URL}/ceiling-fan/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-fan/model.glb`,
    '#64748b',
    0.55,
    ['fan', 'ceiling fan', 'ventilation', 'motor', 'appliance']
  ),
  createRealAsset(
    'elec-ceiling-light',
    'Architectural Ceiling Luminaire',
    'Electronics',
    'Flush architectural surface LED luminaire for retail and residential spaces.',
    'CEILING LIGHT',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '💡',
    `${BASE_ITEM_URL}/ceiling-light/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-light/model.glb`,
    '#eab308',
    0.30,
    ['light', 'ceiling', 'luminaire', 'lighting', 'led']
  ),
  createRealAsset(
    'elec-circular-ceiling-light',
    'Circular Halo Chandelier',
    'Electronics',
    'Contemporary circular suspended halo light fixture with diffused perimeter glow.',
    'HALO LIGHT',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '⭕',
    `${BASE_ITEM_URL}/circular-ceiling-light/thumbnail.webp`,
    `${BASE_ITEM_URL}/circular-ceiling-light/model.glb`,
    '#f59e0b',
    0.45,
    ['light', 'halo', 'circular', 'lighting', 'modern']
  ),
  createRealAsset(
    'elec-recessed-light',
    'Recessed Gimbal Downlight',
    'Electronics',
    'Architectural recessed ceiling spotlight with adjustable directional beam.',
    'SPOTLIGHT',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🔦',
    `${BASE_ITEM_URL}/recessed-light/thumbnail.webp`,
    `${BASE_ITEM_URL}/recessed-light/model.glb`,
    '#f59e0b',
    0.18,
    ['spotlight', 'downlight', 'recessed', 'ceiling', 'lighting']
  ),
  createRealAsset(
    'elec-table-lamp',
    'Minimalist Desk Table Lamp',
    'Electronics',
    'Modern Scandinavian task table lamp with conical shade and brass accents.',
    'DESK LAMP',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🛋️',
    `${BASE_ITEM_URL}/table-lamp/thumbnail.webp`,
    `${BASE_ITEM_URL}/table-lamp/model.glb`,
    '#d97706',
    0.35,
    ['lamp', 'table lamp', 'desk lamp', 'lighting', 'decor']
  ),
  createRealAsset(
    'elec-floor-lamp',
    'Architectural Arc Floor Lamp',
    'Electronics',
    'High-end cantilevered arch floor lamp with marble counterweight base.',
    'FLOOR LAMP',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '💡',
    `${BASE_ITEM_URL}/floor-lamp/thumbnail.webp`,
    `${BASE_ITEM_URL}/floor-lamp/model.glb`,
    '#b45309',
    0.55,
    ['floor lamp', 'lighting', 'interior', 'luminaire']
  ),
  createRealAsset(
    'elec-standing-lamp',
    'Modernist Studio Standing Lamp',
    'Electronics',
    'Triple-legged timber tripod studio standing lamp with cylindrical linen shade.',
    'TRIPOD LAMP',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🛋️',
    `${BASE_ITEM_URL}/floor-lamp/thumbnail.webp`,
    `${BASE_ITEM_URL}/floor-lamp/model.glb`,
    '#eab308',
    0.50,
    ['standing lamp', 'tripod', 'lighting', 'living room']
  ),
  createRealAsset(
    'elec-wall-lamp',
    'Sconce Wall Luminaire',
    'Electronics',
    'Dual-beam architectural up/down LED wall sconce luminaire.',
    'WALL SCONCE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🏮',
    `${BASE_ITEM_URL}/table-lamp/thumbnail.webp`,
    `${BASE_ITEM_URL}/table-lamp/model.glb`,
    '#d97706',
    0.25,
    ['wall lamp', 'sconce', 'lighting', 'interior', 'luminaire']
  ),
  createRealAsset(
    'elec-pendant-lamp',
    'Nordic Brass Pendant Lamp',
    'Electronics',
    'Spun brass suspended architectural dining pendant luminaire.',
    'PENDANT LIGHT',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🏮',
    `${BASE_ITEM_URL}/ceiling-lamp/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-lamp/model.glb`,
    '#b45309',
    0.40,
    ['pendant', 'lamp', 'brass', 'kitchen', 'dining']
  ),
  createRealAsset(
    'elec-pendant-lamp-modern',
    'Geometric Modern Pendant Lamp',
    'Electronics',
    'Faceted geometric matte black pendant light fixture for modern interior decor.',
    'MODERN PENDANT',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '✨',
    `${BASE_ITEM_URL}/recessed-light/thumbnail.webp`,
    `${BASE_ITEM_URL}/recessed-light/model.glb`,
    '#475569',
    0.42,
    ['pendant', 'modern', 'lamp', 'geometric', 'lighting']
  ),
  createRealAsset(
    'elec-chandelier',
    'Grand Contemporary Chandelier',
    'Electronics',
    'Multi-tier sputnik style architectural LED statement chandelier.',
    'CHANDELIER',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '✨',
    `${BASE_ITEM_URL}/ceiling-light/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-light/model.glb`,
    '#ca8a04',
    0.65,
    ['chandelier', 'luxury', 'lighting', 'dining', 'grand']
  ),
  createRealAsset(
    'elec-electric-plug',
    'Duplex Grounded AC Power Outlet',
    'Electronics',
    'Flush architectural duplex electrical AC power wall receptacle with USB ports.',
    'POWER OUTLET',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🔌',
    `${BASE_ITEM_URL}/electric-panel/thumbnail.webp`,
    `${BASE_ITEM_URL}/electric-panel/model.glb`,
    '#52525b',
    0.15,
    ['plug', 'outlet', 'electrical', 'socket', 'ac power']
  ),
  createRealAsset(
    'elec-light-switch',
    'Rocker Smart Light Switch',
    'Electronics',
    'Decora style wall rocker switch plate with subtle LED status indicator.',
    'WALL SWITCH',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '💡',
    `${BASE_ITEM_URL}/electric-panel/thumbnail.webp`,
    `${BASE_ITEM_URL}/electric-panel/model.glb`,
    '#71717a',
    0.14,
    ['switch', 'light switch', 'wall', 'controls', 'smart switch']
  ),
  createRealAsset(
    'elec-double-light-switch',
    'Dual Gang Controller Switch',
    'Electronics',
    'Two-gang architectural lighting control switch with dual toggles.',
    'DUAL SWITCH',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '💡',
    `${BASE_ITEM_URL}/electric-panel/thumbnail.webp`,
    `${BASE_ITEM_URL}/electric-panel/model.glb`,
    '#52525b',
    0.16,
    ['switch', 'double switch', 'electrical', 'lighting', 'gang']
  ),
  createRealAsset(
    'elec-projector',
    '4K Laser Home Cinema Projector',
    'Electronics',
    'Compact high-lumen 4K ultra short-throw laser projector unit.',
    '4K PROJECTOR',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '📽️',
    `${BASE_ITEM_URL}/computer/thumbnail.webp`,
    `${BASE_ITEM_URL}/computer/model.glb`,
    '#4f46e5',
    0.35,
    ['projector', 'cinema', 'video', 'display', 'media']
  ),
  createRealAsset(
    'elec-wifi-router',
    'Wi-Fi 7 Mesh Gateway Router',
    'Electronics',
    'High-speed tri-band mesh network router with internal beamforming antennas.',
    'MESH ROUTER',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '📶',
    `${BASE_ITEM_URL}/alarm-keypad/thumbnail.webp`,
    `${BASE_ITEM_URL}/alarm-keypad/model.glb`,
    '#0891b2',
    0.24,
    ['wifi', 'router', 'network', 'internet', 'smart home']
  ),
  createRealAsset(
    'elec-security-cam',
    'Dome PTZ Surveillance Camera',
    'Electronics',
    '360-degree motorized pan-tilt-zoom smart AI optical security camera.',
    'SECURITY CAM',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '📹',
    `${BASE_ITEM_URL}/smoke-detector/thumbnail.webp`,
    `${BASE_ITEM_URL}/smoke-detector/model.glb`,
    '#2563eb',
    0.22,
    ['camera', 'cctv', 'security', 'surveillance', 'smart']
  ),
  createRealAsset(
    'elec-smart-speaker-hub',
    'Voice AI Smart Assistant Hub',
    'Electronics',
    'Cylindrical fabric-wrapped ambient smart voice speaker with 360 acoustic array.',
    'VOICE HUB',
    'bg-purple-500/20 text-purple-300 border-purple-500/30',
    '🎙️',
    `${BASE_ITEM_URL}/stereo-speaker/thumbnail.webp`,
    `${BASE_ITEM_URL}/stereo-speaker/model.glb`,
    '#9333ea',
    0.25,
    ['speaker', 'smart speaker', 'voice assistant', 'ai', 'iot']
  ),
  createRealAsset(
    'elec-tablet-kiosk',
    'Interactive Multi-Touch Tablet',
    'Electronics',
    'Precision 12.9-inch interactive touchscreen slate for digital catalogs and ordering.',
    'TOUCH TABLET',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '📱',
    `${BASE_ITEM_URL}/flat-screen-tv/thumbnail.webp`,
    `${BASE_ITEM_URL}/flat-screen-tv/model.glb`,
    '#0284c7',
    0.30,
    ['tablet', 'ipad', 'screen', 'display', 'touch', 'digital']
  ),
  createRealAsset(
    'elec-vr-headset-pro',
    'Mixed Reality Spatial Headset',
    'Electronics',
    'High-resolution spatial computing headset with eye tracking and passthrough optics.',
    'MR HEADSET',
    'bg-violet-500/20 text-violet-300 border-violet-500/30',
    '🥽',
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#7c3aed',
    0.36,
    ['vr', 'ar', 'headset', 'spatial', 'metaverse', 'tech']
  )
];
