import { Real3DAsset, createRealAsset, BASE_KHRONOS_URL, BASE_MODELVIEWER_URL, BASE_ITEM_URL } from './types';

export const FACE_TRACKING_ASSETS: Real3DAsset[] = [
  // Glasses & Eyewear (Anchored to Nose or Eyes)
  createRealAsset(
    'face-aviator-sunglasses',
    'Gold Classic Aviator Sunglasses',
    'Face Tracking & Masks',
    'Timeless teardrop gold-framed mirrored polarized aviator sunglasses for face tracking.',
    'AVIATOR SHADES',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🕶️',
    `${BASE_KHRONOS_URL}/OrientationTest/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/OrientationTest/glTF-Binary/OrientationTest.glb`,
    '#eab308',
    0.35,
    ['glasses', 'sunglasses', 'aviator', 'shades', 'eyewear', 'face'],
    'nose'
  ),
  createRealAsset(
    'face-wayfarer-black',
    'Classic Black Wayfarer Shades',
    'Face Tracking & Masks',
    'Iconic thick black acetate frame lifestyle sunglasses with tinted UV lenses.',
    'WAYFARER',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🕶️',
    `${BASE_KHRONOS_URL}/ClearCoatTest/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/ClearCoatTest/glTF-Binary/ClearCoatTest.glb`,
    '#27272a',
    0.35,
    ['sunglasses', 'wayfarer', 'shades', 'black', 'face'],
    'nose'
  ),
  createRealAsset(
    'face-cyber-hud-visor',
    'Cyberpunk Neon HUD Eyewear Visor',
    'Face Tracking & Masks',
    'Sci-fi glowing neon holographic tactical heads-up display ocular visor.',
    'CYBER VISOR',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🥽',
    `${BASE_KHRONOS_URL}/DamagedHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#06b6d4',
    0.40,
    ['visor', 'cyberpunk', 'neon', 'hud', 'sci-fi', 'augmented reality'],
    'nose'
  ),
  createRealAsset(
    'face-cat-eye-glasses',
    'Vintage Cat-Eye Leopard Glasses',
    'Face Tracking & Masks',
    'Chic upturned tortoiseshell cat-eye fashion spectacle frames.',
    'CAT-EYE GLASSES',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '👓',
    `${BASE_KHRONOS_URL}/MaterialsVariantsShoe/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb`,
    '#d97706',
    0.34,
    ['glasses', 'cateye', 'fashion', 'vintage', 'spectacles'],
    'nose'
  ),
  createRealAsset(
    'face-steampunk-monocle',
    'Steampunk Brass Gear Monocle',
    'Face Tracking & Masks',
    'Intricate Victorian brass monocle with miniature gears and hanging chain.',
    'BRASS MONOCLE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🧐',
    `${BASE_KHRONOS_URL}/AntiqueCamera/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/AntiqueCamera/glTF-Binary/AntiqueCamera.glb`,
    '#b45309',
    0.28,
    ['monocle', 'steampunk', 'brass', 'victorian', 'eye'],
    'rightEye'
  ),
  createRealAsset(
    'face-pixel-thug-shades',
    '8-Bit Pixel Deal-With-It Shades',
    'Face Tracking & Masks',
    'Blocky black 8-bit meme pixel sunglasses for viral social face AR filters.',
    'PIXEL SHADES',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🕶️',
    `${BASE_KHRONOS_URL}/BoxAnimated/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/BoxAnimated/glTF-Binary/BoxAnimated.glb`,
    '#0f172a',
    0.32,
    ['pixel', 'shades', 'meme', '8bit', 'retro', 'sunglasses'],
    'nose'
  ),
  createRealAsset(
    'face-snow-goggles',
    'Alpine Mirror Snowboard Goggles',
    'Face Tracking & Masks',
    'Spherical rainbow iridium dual-lens winter alpine ski and snowboard goggles.',
    'SKI GOGGLES',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🥽',
    `${BASE_KHRONOS_URL}/DamagedHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#2563eb',
    0.42,
    ['goggles', 'ski', 'snowboard', 'winter', 'sports', 'eyewear'],
    'nose'
  ),
  createRealAsset(
    'face-party-heart-glasses',
    'Neon Pink Heart Sunglasses',
    'Face Tracking & Masks',
    'Glossy candy pink heart-shaped rave festival sunglasses with UV protection.',
    'HEART SHADES',
    'bg-pink-500/20 text-pink-300 border-pink-500/30',
    '💖',
    `${BASE_KHRONOS_URL}/Corset/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Corset/glTF-Binary/Corset.glb`,
    '#ec4899',
    0.35,
    ['heart', 'glasses', 'pink', 'rave', 'party', 'festival'],
    'nose'
  ),

  // Masks & Face Coverings (Anchored to Head, Mouth, or Forehead)
  createRealAsset(
    'face-kitsune-mask',
    'Japanese Kitsune Fox Spirit Mask',
    'Face Tracking & Masks',
    'Traditional Japanese porcelain Kitsune spirit mask with red painted shrine accents.',
    'KITSUNE MASK',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🦊',
    `${BASE_KHRONOS_URL}/Fox/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/Fox/glTF-Binary/Fox.glb`,
    '#dc2626',
    0.50,
    ['mask', 'kitsune', 'fox', 'japanese', 'anime', 'spirit'],
    'head'
  ),
  createRealAsset(
    'face-oni-samurai-mask',
    'Samurai Oni Menpo Battle Mask',
    'Face Tracking & Masks',
    'Fierce lacquered steel samurai lower face armor mask with bared fangs.',
    'ONI HALF-MASK',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '👹',
    `${BASE_KHRONOS_URL}/Suzanne/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Suzanne/glTF-Binary/Suzanne.glb`,
    '#be123c',
    0.45,
    ['mask', 'oni', 'samurai', 'demon', 'warrior', 'half mask'],
    'mouth'
  ),
  createRealAsset(
    'face-venetian-masquerade',
    'Venetian Gold Filigree Masquerade Mask',
    'Face Tracking & Masks',
    'Intricate laser-cut golden carnival masquerade mask with Swarovski crystals.',
    'VENETIAN MASK',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🎭',
    `${BASE_KHRONOS_URL}/DragonAttenuation/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/DragonAttenuation/glTF-Binary/DragonAttenuation.glb`,
    '#ca8a04',
    0.45,
    ['mask', 'masquerade', 'carnival', 'venetian', 'gold', 'opera'],
    'forehead'
  ),
  createRealAsset(
    'face-cyber-respirator',
    'Cyberpunk LED Gas Filter Respirator',
    'Face Tracking & Masks',
    'Futuristic lower half gas mask with pulsing neon side intake turbine lights.',
    'CYBER RESPIRATOR',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '😷',
    `${BASE_KHRONOS_URL}/DamagedHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#10b981',
    0.42,
    ['mask', 'respirator', 'cyberpunk', 'gas mask', 'led', 'sci-fi'],
    'mouth'
  ),
  createRealAsset(
    'face-phantom-opera-mask',
    'Phantom of the Opera Half-Mask',
    'Face Tracking & Masks',
    'Sleek white ceramic asymmetrical masquerade half-mask covering right cheek and brow.',
    'PHANTOM MASK',
    'bg-stone-500/20 text-stone-300 border-stone-500/30',
    '🎭',
    `${BASE_KHRONOS_URL}/SimpleSkin/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SimpleSkin/glTF-Binary/SimpleSkin.glb`,
    '#e7e5e4',
    0.40,
    ['mask', 'phantom', 'opera', 'theatre', 'drama', 'masquerade'],
    'head'
  ),
  createRealAsset(
    'face-surgical-protective-mask',
    'Medical Surgical Protective Mask',
    'Face Tracking & Masks',
    'Pleated light blue 3-ply surgical medical face mask with elastic ear loops.',
    'SURGICAL MASK',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '😷',
    `${BASE_KHRONOS_URL}/SheenCloth/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SheenCloth/glTF-Binary/SheenCloth.glb`,
    '#0ea5e9',
    0.35,
    ['mask', 'surgical', 'medical', 'health', 'protection'],
    'mouth'
  ),
  createRealAsset(
    'face-skull-jaw-bandana',
    'Biker Skull Skeleton Half-Mask',
    'Face Tracking & Masks',
    'Anatomical white skeleton skull jaw print on black neoprene face gaiter.',
    'SKULL JAW MASK',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '💀',
    `${BASE_KHRONOS_URL}/Suzanne/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Suzanne/glTF-Binary/Suzanne.glb`,
    '#18181b',
    0.38,
    ['mask', 'skull', 'skeleton', 'biker', 'halloween'],
    'mouth'
  ),

  // Crowns, Tiaras & Royal Headwear (Forehead & Head Anchored)
  createRealAsset(
    'face-imperial-gold-crown',
    'Imperial Sovereign Gold Crown',
    'Face Tracking & Masks',
    'Ornate 24K gold royal sovereign crown encrusted with rubies, emeralds, and pearls.',
    'GOLD CROWN',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '👑',
    `${BASE_KHRONOS_URL}/Lantern/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/Lantern/glTF-Binary/Lantern.glb`,
    '#eab308',
    0.50,
    ['crown', 'royal', 'gold', 'king', 'queen', 'tiara', 'sovereign'],
    'head'
  ),
  createRealAsset(
    'face-diamond-tiara',
    'Princess Crystal Diamond Tiara',
    'Face Tracking & Masks',
    'Glittering platinum and marquise-cut diamond bridal princess tiara headband.',
    'DIAMOND TIARA',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '👸',
    `${BASE_KHRONOS_URL}/TransmissionTest/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/TransmissionTest/glTF-Binary/TransmissionTest.glb`,
    '#06b6d4',
    0.42,
    ['tiara', 'diamond', 'princess', 'bridal', 'crown', 'sparkle'],
    'forehead'
  ),
  createRealAsset(
    'face-bohemian-flower-crown',
    'Vibrant Floral Blossom Crown',
    'Face Tracking & Masks',
    'Hand-woven floral wreath crown featuring blooming wild roses, daisies, and baby breath.',
    'FLOWER CROWN',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '🌸',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#f43f5e',
    0.48,
    ['flower crown', 'floral', 'boho', 'spring', 'festival', 'roses'],
    'head'
  ),
  createRealAsset(
    'face-golden-laurel-wreath',
    'Roman Golden Laurel Wreath',
    'Face Tracking & Masks',
    'Ancient classical Grecian and Roman golden laurel leaf victor victory crown.',
    'LAUREL WREATH',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🌿',
    `${BASE_KHRONOS_URL}/Lantern/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/Lantern/glTF-Binary/Lantern.glb`,
    '#d97706',
    0.45,
    ['laurel', 'wreath', 'roman', 'gold', 'victory', 'olympic'],
    'head'
  ),

  // Hats & Themed Headgear (Head Anchored)
  createRealAsset(
    'face-cowboy-hat',
    'Western Distressed Leather Cowboy Hat',
    'Face Tracking & Masks',
    'Classic wide-brim cattleman brown leather cowboy hat with braided hatband.',
    'COWBOY HAT',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🤠',
    `${BASE_KHRONOS_URL}/SheenChair/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/SheenChair/glTF-Binary/SheenChair.glb`,
    '#92400e',
    0.60,
    ['cowboy', 'hat', 'western', 'leather', 'rodeo'],
    'head'
  ),
  createRealAsset(
    'face-baseball-cap-snapback',
    'Urban Athletic Snapback Cap',
    'Face Tracking & Masks',
    'Structured flat-brim streetwear snapback baseball cap with embroidered logo.',
    'SNAPBACK CAP',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🧢',
    `${BASE_KHRONOS_URL}/MaterialsVariantsShoe/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb`,
    '#2563eb',
    0.48,
    ['cap', 'hat', 'baseball', 'snapback', 'streetwear', 'fashion'],
    'head'
  ),
  createRealAsset(
    'face-wizard-pointed-hat',
    'Arcane Midnight Wizard Hat',
    'Face Tracking & Masks',
    'Tall crooked pointed indigo velvet sorcerer hat adorned with glowing golden stars.',
    'WIZARD HAT',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🧙',
    `${BASE_KHRONOS_URL}/Suzanne/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Suzanne/glTF-Binary/Suzanne.glb`,
    '#4338ca',
    0.65,
    ['wizard', 'hat', 'magic', 'sorcerer', 'fantasy', 'witch'],
    'head'
  ),
  createRealAsset(
    'face-birthday-party-cone',
    'Confetti Birthday Party Hat',
    'Face Tracking & Masks',
    'Festive polka-dot cone party hat with fluffy silver pom-pom topper.',
    'PARTY CONE',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🎉',
    `${BASE_KHRONOS_URL}/Duck/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Duck/glTF-Binary/Duck.glb`,
    '#f59e0b',
    0.40,
    ['party', 'birthday', 'hat', 'celebration', 'fun'],
    'head'
  ),
  createRealAsset(
    'face-victorian-top-hat',
    'Silk Victorian Top Hat',
    'Face Tracking & Masks',
    'Refined high-crown black silk formal gentleman top hat with satin ribbon.',
    'TOP HAT',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🎩',
    `${BASE_KHRONOS_URL}/CarbonFibreBox/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/CarbonFibreBox/glTF-Binary/CarbonFibreBox.glb`,
    '#0f172a',
    0.55,
    ['top hat', 'hat', 'formal', 'gentleman', 'victorian', 'magic'],
    'head'
  ),
  createRealAsset(
    'face-fedora-detective',
    'Classic Noir Detective Fedora',
    'Face Tracking & Masks',
    'Charcoal wool felt pinched-crown fedora hat with grosgrain band.',
    'FEDORA HAT',
    'bg-stone-500/20 text-stone-300 border-stone-500/30',
    '🕵️',
    `${BASE_KHRONOS_URL}/SheenChair/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/SheenChair/glTF-Binary/SheenChair.glb`,
    '#57534e',
    0.52,
    ['fedora', 'noir', 'detective', 'hat', 'vintage'],
    'head'
  ),

  // Helmets & Sci-Fi Headgear (Head Anchored)
  createRealAsset(
    'face-astronaut-space-helmet',
    'NASA Apollo Gold Visor Helmet',
    'Face Tracking & Masks',
    'Full pressurized astronaut EVA exploration helmet with reflective gold sun visor.',
    'SPACE HELMET',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '👨‍🚀',
    `${BASE_MODELVIEWER_URL}/Astronaut.glb`,
    `${BASE_MODELVIEWER_URL}/Astronaut.glb`,
    '#0284c7',
    0.65,
    ['astronaut', 'space', 'helmet', 'nasa', 'sci-fi'],
    'head'
  ),
  createRealAsset(
    'face-tactical-flight-helmet',
    'Avionics Jet Fighter Pilot Helmet',
    'Face Tracking & Masks',
    'Modern fighter jet pilot helmet with dual amber tint visor and oxygen mask connector.',
    'PILOT HELMET',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🪖',
    `${BASE_KHRONOS_URL}/DamagedHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#0891b2',
    0.60,
    ['pilot', 'flight', 'helmet', 'aviation', 'tactical'],
    'head'
  ),
  createRealAsset(
    'face-damaged-cyber-helmet',
    'Battle-Tested Cybernetic Helmet',
    'Face Tracking & Masks',
    'High-poly battle-damaged robotic combat helmet with glowing eye sensors.',
    'CYBER HELMET',
    'bg-violet-500/20 text-violet-300 border-violet-500/30',
    '🥽',
    `${BASE_KHRONOS_URL}/DamagedHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#8b5cf6',
    0.62,
    ['helmet', 'cyberpunk', 'sci-fi', 'combat', 'robot'],
    'head'
  ),

  // Ears, Horns & Headbands (Head & Forehead Anchored)
  createRealAsset(
    'face-anime-bunny-ears',
    'Fluffy White & Pink Bunny Ears',
    'Face Tracking & Masks',
    'Plush animated anime bunny rabbit ears headband with gentle bounce.',
    'BUNNY EARS',
    'bg-pink-500/20 text-pink-300 border-pink-500/30',
    '🐰',
    `${BASE_KHRONOS_URL}/Duck/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Duck/glTF-Binary/Duck.glb`,
    '#f472b6',
    0.45,
    ['bunny', 'ears', 'headband', 'kawaii', 'anime', 'cute'],
    'head'
  ),
  createRealAsset(
    'face-kawaii-cat-ears',
    'Neko Cat Ears Headband with Bells',
    'Face Tracking & Masks',
    'Cute fuzzy black cat ears headband with pink inner tufts and golden jingle bells.',
    'CAT EARS',
    'bg-purple-500/20 text-purple-300 border-purple-500/30',
    '🐱',
    `${BASE_KHRONOS_URL}/Fox/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/Fox/glTF-Binary/Fox.glb`,
    '#a855f7',
    0.42,
    ['cat', 'ears', 'neko', 'kawaii', 'anime', 'headband'],
    'head'
  ),
  createRealAsset(
    'face-glowing-devil-horns',
    'Crimson Glowing Devil Horns',
    'Face Tracking & Masks',
    'Curved demonic crimson horns with internal magma crack glow effect.',
    'DEVIL HORNS',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '😈',
    `${BASE_KHRONOS_URL}/Suzanne/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Suzanne/glTF-Binary/Suzanne.glb`,
    '#ef4444',
    0.38,
    ['devil', 'horns', 'demon', 'halloween', 'glowing'],
    'forehead'
  ),
  createRealAsset(
    'face-golden-angel-halo',
    'Luminous Angelic Halo Ring',
    'Face Tracking & Masks',
    'Floating golden halo ring hovering with soft celestial particle glow.',
    'ANGEL HALO',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '😇',
    `${BASE_KHRONOS_URL}/Lantern/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/Lantern/glTF-Binary/Lantern.glb`,
    '#facc15',
    0.35,
    ['halo', 'angel', 'celestial', 'divine', 'ring', 'glow'],
    'head'
  ),
  createRealAsset(
    'face-reindeer-antlers',
    'Festive Holiday Reindeer Antlers',
    'Face Tracking & Masks',
    'Velvet-coated brown reindeer antlers headband with festive holly berries.',
    'REINDEER ANTLERS',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🦌',
    `${BASE_KHRONOS_URL}/Horse/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/Horse/glTF-Binary/Horse.glb`,
    '#059669',
    0.50,
    ['reindeer', 'antlers', 'christmas', 'holiday', 'festive'],
    'head'
  ),

  // Face Jewelry, Facial Overlays & Facial Filters
  createRealAsset(
    'face-diamond-drop-earrings',
    'Sparkling Diamond Chandelier Earrings',
    'Face Tracking & Masks',
    'Pair of dangling teardrop diamond chandelier earrings with optical refraction.',
    'DIAMOND EARRINGS',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '💎',
    `${BASE_KHRONOS_URL}/TransmissionTest/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/TransmissionTest/glTF-Binary/TransmissionTest.glb`,
    '#06b6d4',
    0.30,
    ['earrings', 'jewelry', 'diamond', 'fashion', 'sparkle'],
    'head'
  ),
  createRealAsset(
    'face-gold-hoop-earrings',
    'Chunky 18K Gold Hoop Earrings',
    'Face Tracking & Masks',
    'Polished high-shine chunky 18K yellow gold statement hoop earrings.',
    'GOLD HOOPS',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '✨',
    `${BASE_KHRONOS_URL}/OrientationTest/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/OrientationTest/glTF-Binary/OrientationTest.glb`,
    '#eab308',
    0.28,
    ['earrings', 'hoops', 'gold', 'jewelry', 'chic'],
    'head'
  ),
  createRealAsset(
    'face-crystal-forehead-bindi',
    'Ruby Crystal Forehead Bindi Jewel',
    'Face Tracking & Masks',
    'Intricate teardrop ruby and gold filigree forehead third-eye bindi gemstone.',
    'FOREHEAD BINDI',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🔴',
    `${BASE_KHRONOS_URL}/Suzanne/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Suzanne/glTF-Binary/Suzanne.glb`,
    '#dc2626',
    0.20,
    ['bindi', 'jewel', 'forehead', 'crystal', 'gem', 'boho'],
    'forehead'
  ),
  createRealAsset(
    'face-silver-nose-ring',
    'Polished Silver Nose Hoop Piercing',
    'Face Tracking & Masks',
    'Seamless surgical steel small hoop nose ring piercing with crystal accent.',
    'NOSE RING',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '⭕',
    `${BASE_KHRONOS_URL}/WaterBottle/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/WaterBottle/glTF-Binary/WaterBottle.glb`,
    '#94a3b8',
    0.15,
    ['nose ring', 'piercing', 'jewelry', 'silver', 'punk'],
    'nose'
  ),
  createRealAsset(
    'face-handlebar-mustache',
    'Gentleman Handlebar Mustache Prop',
    'Face Tracking & Masks',
    'Glossy waxed handlebar mustache for whimsical photo-booth face filters.',
    'MUSTACHE PROP',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🥸',
    `${BASE_KHRONOS_URL}/AntiqueCamera/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/AntiqueCamera/glTF-Binary/AntiqueCamera.glb`,
    '#78350f',
    0.25,
    ['mustache', 'gentleman', 'photobooth', 'vintage', 'prop'],
    'mouth'
  ),
  createRealAsset(
    'face-hologram-eye-target',
    'Holographic Sci-Fi Eye Target Reticle',
    'Face Tracking & Masks',
    'Futuristic circular ocular telemetry targeting lock reticle over right eye.',
    'EYE RETICLE',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🎯',
    `${BASE_KHRONOS_URL}/DamagedHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#10b981',
    0.30,
    ['reticle', 'target', 'hud', 'hologram', 'eye', 'cyber'],
    'rightEye'
  ),
  createRealAsset(
    'face-anime-cheek-blush',
    'Kawaii Heart Cheek Blush FX',
    'Face Tracking & Masks',
    'Subtle glowing pink gradient anime blushing cheeks with mini floating hearts.',
    'HEART BLUSH',
    'bg-pink-500/20 text-pink-300 border-pink-500/30',
    '💕',
    `${BASE_KHRONOS_URL}/Corset/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Corset/glTF-Binary/Corset.glb`,
    '#f472b6',
    0.35,
    ['blush', 'anime', 'kawaii', 'hearts', 'cheeks', 'filter'],
    'nose'
  ),
  createRealAsset(
    'face-glitter-star-freckles',
    'Celestial Star Glitter Freckles',
    'Face Tracking & Masks',
    'Shimmering gold and silver holographic miniature star stickers across cheeks and nose.',
    'STAR FRECKLES',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '⭐',
    `${BASE_KHRONOS_URL}/Lantern/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/Lantern/glTF-Binary/Lantern.glb`,
    '#facc15',
    0.32,
    ['freckles', 'glitter', 'stars', 'makeup', 'festival', 'shimmer'],
    'nose'
  )
];
