import { Real3DAsset, createRealAsset, BASE_ITEM_URL, BASE_KHRONOS_URL, BASE_MODELVIEWER_URL } from './types';

// ============================================================================
// 1. REALISTIC FOOD, BEVERAGES, UTENSILS, BOTTLES & CANS (36+ diverse items)
// ============================================================================
export const REALISTIC_FOOD_UTENSILS_ASSETS: Real3DAsset[] = [
  // --- BOTTLES & CANS ---
  createRealAsset(
    'food-real-bottle-olive-oil',
    'Extra Virgin Olive Oil Glass Bottle',
    'Realistic Food & Utensils',
    'Dark green tinted glass bottle with pour spout and golden Mediterranean label for fine dining and home kitchens.',
    'GLASS BOTTLE',
    'bg-emerald-600/20 text-emerald-300 border-emerald-500/30',
    '🍾',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#059669',
    0.35,
    ['realistic food', 'bottle', 'oil', 'olive oil', 'cooking', 'kitchen', 'restaurant', 'mediterranean', 'condiment']
  ),
  createRealAsset(
    'food-real-bordeaux-wine',
    'Vintage Bordeaux Red Wine Bottle',
    'Realistic Food & Utensils',
    'Classic 750ml glass wine bottle with embossed foil seal, deep punt base, and elegant vintage reserve typography label.',
    'WINE BOTTLE',
    'bg-rose-800/20 text-rose-300 border-rose-600/30',
    '🍷',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#881337',
    0.38,
    ['realistic food', 'wine', 'bottle', 'bordeaux', 'alcohol', 'restaurant', 'bar', 'beverage', 'glass']
  ),
  createRealAsset(
    'food-real-champagne-bottle',
    'Brut Champagne Bottle with Gold Foil',
    'Realistic Food & Utensils',
    'Celebratory sparkling champagne glass bottle with gold foil wire cage muselet and textured black luxury label.',
    'CHAMPAGNE',
    'bg-amber-600/20 text-amber-300 border-amber-500/30',
    '🍾',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#d97706',
    0.40,
    ['realistic food', 'champagne', 'bottle', 'celebration', 'restaurant', 'luxury', 'beverage', 'sparkling']
  ),
  createRealAsset(
    'food-real-craft-beer-can',
    'Artisanal IPA Soda & Beer Aluminum Can',
    'Realistic Food & Utensils',
    'Standard 355ml aluminum beverage can with pull tab top, matte condensation texture, and bold craft brewery graphics.',
    'ALUMINUM CAN',
    'bg-cyan-600/20 text-cyan-300 border-cyan-500/30',
    '🥫',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#0891b2',
    0.30,
    ['realistic food', 'can', 'aluminum', 'soda', 'beer', 'beverage', 'drink', 'bar', 'cold']
  ),
  createRealAsset(
    'food-real-sparkling-water-can',
    'Slim Sparkling Citrus Mineral Water Can',
    'Realistic Food & Utensils',
    'Tall, sleek 330ml aluminum slimline beverage can with frosted metallic finish and refreshing lime mint graphics.',
    'SLIM CAN',
    'bg-lime-600/20 text-lime-300 border-lime-500/30',
    '🥤',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#65a30d',
    0.30,
    ['realistic food', 'can', 'sparkling water', 'beverage', 'soda', 'drink', 'restaurant', 'refreshing']
  ),
  createRealAsset(
    'food-real-soy-sauce-dispenser',
    'Japanese Glass Soy Sauce Table Cruet',
    'Realistic Food & Utensils',
    'Traditional Japanese restaurant hourglass glass shoyu bottle with dual drip-free red pouring spouts.',
    'SOY SAUCE',
    'bg-stone-700/20 text-stone-300 border-stone-500/30',
    '🍶',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#44403c',
    0.28,
    ['realistic food', 'soy sauce', 'bottle', 'dispenser', 'japan', 'asian', 'restaurant', 'sushi', 'condiment']
  ),
  createRealAsset(
    'food-real-sriracha-bottle',
    'Sriracha Hot Chili Sauce Squeeze Bottle',
    'Realistic Food & Utensils',
    'Bright red hot chili squeeze bottle with signature bright green nozzle cap and rooster graphic print.',
    'HOT SAUCE',
    'bg-red-700/20 text-red-300 border-red-500/30',
    '🌶️',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#b91c1c',
    0.32,
    ['realistic food', 'sriracha', 'hot sauce', 'chili', 'bottle', 'spicy', 'restaurant', 'condiment']
  ),
  createRealAsset(
    'food-real-glass-milk-bottle',
    'Farm Fresh Glass Milk Bottle & Stopper',
    'Realistic Food & Utensils',
    'Vintage dairy farm heavy glass milk bottle with creamy white contents and metal clamp swing-top lid.',
    'MILK BOTTLE',
    'bg-blue-400/20 text-blue-200 border-blue-400/30',
    '🥛',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#38bdf8',
    0.34,
    ['realistic food', 'milk', 'bottle', 'dairy', 'farm', 'home', 'breakfast', 'beverage']
  ),

  // --- UTENSILS, COOKWARE & TABLEWARE ---
  createRealAsset(
    'food-real-chef-knife-set',
    'Damascus Steel Chef Knife & Wooden Block',
    'Realistic Food & Utensils',
    'Professional 8-inch forged Damascus steel kitchen knife with ergonomic Pakkawood handle seated in acacia block.',
    'CHEF KNIFE',
    'bg-slate-600/20 text-slate-300 border-slate-500/30',
    '🔪',
    `${BASE_ITEM_URL}/kitchen-utensils/thumbnail.webp`,
    `${BASE_ITEM_URL}/kitchen-utensils/model.glb`,
    '#475569',
    0.36,
    ['realistic food', 'utensil', 'knife', 'chef', 'cutlery', 'kitchen', 'cooking', 'blade', 'home']
  ),
  createRealAsset(
    'food-real-cast-iron-skillet',
    'Heavy Seasoned Cast Iron Skillet',
    'Realistic Food & Utensils',
    'Pre-seasoned heavy-duty 10-inch black cast iron frying pan with dual pour spouts and handle helper grip.',
    'CAST IRON',
    'bg-zinc-800/20 text-zinc-300 border-zinc-600/30',
    '🍳',
    `${BASE_ITEM_URL}/frying-pan/thumbnail.webp`,
    `${BASE_ITEM_URL}/frying-pan/model.glb`,
    '#27272a',
    0.45,
    ['realistic food', 'utensil', 'skillet', 'cookware', 'pan', 'cast iron', 'kitchen', 'grill', 'firebrand']
  ),
  createRealAsset(
    'food-real-copper-saucepan',
    'French Copper & Brass Sauté Pan',
    'Realistic Food & Utensils',
    'Traditional French culinary polished copper pan lined with stainless steel and heavy cast brass riveted handle.',
    'COPPER PAN',
    'bg-amber-700/20 text-amber-300 border-amber-600/30',
    '🥘',
    `${BASE_ITEM_URL}/frying-pan/thumbnail.webp`,
    `${BASE_ITEM_URL}/frying-pan/model.glb`,
    '#b45309',
    0.44,
    ['realistic food', 'utensil', 'copper', 'pan', 'saucepan', 'french', 'culinary', 'restaurant', 'cookware']
  ),
  createRealAsset(
    'food-real-dinner-plate-cutlery',
    'Fine Dining Porcelain Plate & Silver Cutlery',
    'Realistic Food & Utensils',
    'Rimmed bone china ceramic dinner plate paired with polished stainless steel dinner fork, knife, and dessert spoon.',
    'TABLE SETTING',
    'bg-stone-500/20 text-stone-300 border-stone-400/30',
    '🍽️',
    `${BASE_ITEM_URL}/cutting-board/thumbnail.webp`,
    `${BASE_ITEM_URL}/cutting-board/model.glb`,
    '#78716c',
    0.42,
    ['realistic food', 'utensil', 'plate', 'cutlery', 'fork', 'spoon', 'knife', 'tableware', 'dining', 'restaurant']
  ),
  createRealAsset(
    'food-real-wine-goblet',
    'Crystal Bordeaux Wine Glass Goblet',
    'Realistic Food & Utensils',
    'Hand-blown crystal red wine goblet with ultra-thin rim, long delicate stem, and broad aerating bowl.',
    'WINE GOBLET',
    'bg-rose-600/20 text-rose-300 border-rose-500/30',
    '🍷',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#e11d48',
    0.32,
    ['realistic food', 'utensil', 'glass', 'wine', 'goblet', 'crystal', 'tableware', 'restaurant', 'bar']
  ),
  createRealAsset(
    'food-real-ramen-bowl-chopsticks',
    'Artisanal Ceramic Ramen Bowl & Wooden Chopsticks',
    'Realistic Food & Utensils',
    'Hand-thrown dark speckled stoneware noodle bowl with rests for natural bamboo chopsticks and ceramic soup ladle.',
    'RAMEN BOWL',
    'bg-stone-700/20 text-stone-300 border-stone-600/30',
    '🍜',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#57534e',
    0.38,
    ['realistic food', 'utensil', 'bowl', 'ramen', 'chopsticks', 'japanese', 'tableware', 'stoneware', 'asian']
  ),
  createRealAsset(
    'food-real-espresso-cup',
    'Barista Ceramic Espresso Cup & Saucer',
    'Realistic Food & Utensils',
    'Thick-walled Italian porcelain demitasse espresso cup with rich golden crema coffee and matching saucer.',
    'ESPRESSO SET',
    'bg-amber-900/20 text-amber-300 border-amber-700/30',
    '☕',
    `${BASE_ITEM_URL}/kettle/thumbnail.webp`,
    `${BASE_ITEM_URL}/kettle/model.glb`,
    '#78350f',
    0.28,
    ['realistic food', 'coffee', 'espresso', 'cup', 'saucer', 'barista', 'cafe', 'italian', 'beverage']
  ),
  createRealAsset(
    'food-real-tea-kettle',
    'Brushed Stainless Steel Stovetop Whistling Kettle',
    'Realistic Food & Utensils',
    'Classic domed stainless steel boiling kettle with heat-resistant ergonomic black handle and flip whistling spout.',
    'TEA KETTLE',
    'bg-slate-500/20 text-slate-300 border-slate-400/30',
    '🫖',
    `${BASE_ITEM_URL}/kettle/thumbnail.webp`,
    `${BASE_ITEM_URL}/kettle/model.glb`,
    '#64748b',
    0.40,
    ['realistic food', 'utensil', 'kettle', 'tea', 'boiling', 'kitchen', 'stovetop', 'home', 'cookware']
  ),
  createRealAsset(
    'food-real-mortar-pestle',
    'Granite Stone Mortar & Pestle Grinder',
    'Realistic Food & Utensils',
    'Heavy unpolished natural grey granite spice and guacamole grinding mortar with contoured stone pestle.',
    'MORTAR & PESTLE',
    'bg-zinc-600/20 text-zinc-300 border-zinc-500/30',
    '🥣',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#52525b',
    0.36,
    ['realistic food', 'utensil', 'mortar', 'pestle', 'granite', 'spices', 'guacamole', 'kitchen', 'tools']
  ),
  createRealAsset(
    'food-real-bbq-grill-tongs',
    'Heavy Stainless Firebrand BBQ Grill Tongs & Spatula',
    'Realistic Food & Utensils',
    'Extra-long heavy gauge stainless steel barbecue tongs with oak grip inlays and serrated grilling tips.',
    'GRILL TONGS',
    'bg-orange-700/20 text-orange-300 border-orange-500/30',
    '🥩',
    `${BASE_ITEM_URL}/kitchen-utensils/thumbnail.webp`,
    `${BASE_ITEM_URL}/kitchen-utensils/model.glb`,
    '#c2410c',
    0.40,
    ['realistic food', 'utensil', 'bbq', 'grill', 'tongs', 'firebrand', 'meat', 'cookware', 'outdoor']
  ),

  // --- RESTAURANT, HOME & CULTURAL DISHES ---
  createRealAsset(
    'food-real-margherita-pizza',
    'Wood-Fired Neapolitan Margherita Pizza',
    'Realistic Food & Utensils',
    'Authentic blistered leopard-crust Neapolitan pizza with San Marzano tomato sauce, fresh buffalo mozzarella, and basil.',
    'NEAPOLITAN PIZZA',
    'bg-red-600/20 text-red-300 border-red-500/30',
    '🍕',
    `${BASE_ITEM_URL}/cutting-board/thumbnail.webp`,
    `${BASE_ITEM_URL}/cutting-board/model.glb`,
    '#dc2626',
    0.50,
    ['realistic food', 'pizza', 'margherita', 'italian', 'restaurant', 'mozzarella', 'wood-fired', 'cheese']
  ),
  createRealAsset(
    'food-real-gourmet-burger',
    'Artisanal Brioche Wagyu Cheeseburger',
    'Realistic Food & Utensils',
    'Seared Wagyu beef patty layered with melted aged cheddar, crisp butter lettuce, heirloom tomato, and caramelized onions on brioche.',
    'GOURMET BURGER',
    'bg-amber-600/20 text-amber-300 border-amber-500/30',
    '🍔',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#d97706',
    0.45,
    ['realistic food', 'burger', 'cheeseburger', 'wagyu', 'restaurant', 'brioche', 'american', 'diner']
  ),
  createRealAsset(
    'food-real-ribeye-steak',
    'Seared Tomahawk Ribeye Steak with Rosemary & Butter',
    'Realistic Food & Utensils',
    'Prime aged bone-in ribeye steak seared with charcoal crosshatch grill marks, herb butter medallion, and roasted garlic bulb.',
    'CHARRED STEAK',
    'bg-red-800/20 text-red-300 border-red-600/30',
    '🥩',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#991b1b',
    0.48,
    ['realistic food', 'steak', 'ribeye', 'meat', 'beef', 'grill', 'firebrand', 'restaurant', 'dinner']
  ),
  createRealAsset(
    'food-real-sushi-platter',
    'Tokyo Omakase Nigiri Sushi & Sashimi Platter',
    'Realistic Food & Utensils',
    'Masterpiece assortment of Maguro tuna, Atlantic salmon, sweet ebi shrimp nigiri with fresh wasabi and pickled ginger.',
    'OMAKASE SUSHI',
    'bg-emerald-600/20 text-emerald-300 border-emerald-500/30',
    '🍣',
    `${BASE_ITEM_URL}/cutting-board/thumbnail.webp`,
    `${BASE_ITEM_URL}/cutting-board/model.glb`,
    '#059669',
    0.46,
    ['realistic food', 'sushi', 'nigiri', 'sashimi', 'japanese', 'tokyo', 'restaurant', 'seafood', 'asian']
  ),
  createRealAsset(
    'food-real-croissant-basket',
    'French Golden Butter Croissants in Linen Basket',
    'Realistic Food & Utensils',
    'Flaky multi-layered golden brown Viennoiserie butter croissants served in woven wicker basket with linen cloth.',
    'BUTTER CROISSANT',
    'bg-yellow-600/20 text-yellow-300 border-yellow-500/30',
    '🥐',
    `${BASE_ITEM_URL}/toaster/thumbnail.webp`,
    `${BASE_ITEM_URL}/toaster/model.glb`,
    '#ca8a04',
    0.40,
    ['realistic food', 'croissant', 'french', 'bakery', 'breakfast', 'pastry', 'butter', 'cafe']
  ),
  createRealAsset(
    'food-real-spaghetti-bolognese',
    'Classic Italian Spaghetti Bolognese Pasta',
    'Realistic Food & Utensils',
    'Al dente spaghetti twirled with rich slow-simmered beef ragù bolognese, shaved Parmigiano-Reggiano, and fresh oregano.',
    'SPAGHETTI RAGU',
    'bg-rose-700/20 text-rose-300 border-rose-500/30',
    '🍝',
    `${BASE_ITEM_URL}/cutting-board/thumbnail.webp`,
    `${BASE_ITEM_URL}/cutting-board/model.glb`,
    '#be123c',
    0.42,
    ['realistic food', 'pasta', 'spaghetti', 'bolognese', 'italian', 'restaurant', 'ragu', 'parmesan']
  ),
  createRealAsset(
    'food-real-mexican-tacos',
    'Street-Style Birria & Carne Asada Tacos',
    'Realistic Food & Utensils',
    'Duo of warm handmade yellow corn tortillas topped with shredded beef, diced white onion, cilantro, and lime wedges.',
    'MEXICAN TACOS',
    'bg-amber-600/20 text-amber-300 border-amber-500/30',
    '🌮',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#d97706',
    0.38,
    ['realistic food', 'tacos', 'mexican', 'street food', 'birria', 'lime', 'cilantro', 'tortilla']
  ),
  createRealAsset(
    'food-real-dimsum-steamer',
    'Bamboo Steamer Basket with Xiao Long Bao Dumplings',
    'Realistic Food & Utensils',
    'Traditional woven bamboo dim sum steamer containing delicate steamed soup dumplings with translucent wrappers.',
    'DIM SUM STEAMER',
    'bg-orange-600/20 text-orange-300 border-orange-500/30',
    '🥟',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#ea580c',
    0.40,
    ['realistic food', 'dim sum', 'dumpling', 'bamboo', 'steamer', 'chinese', 'asian', 'xiao long bao']
  ),
  createRealAsset(
    'food-real-sourdough-loaf',
    'Artisanal Country Sourdough Bread Boule',
    'Realistic Food & Utensils',
    'Rustic naturally leavened sourdough bread boule with flour-dusted scored blistered crust and chewy open crumb.',
    'SOURDOUGH BOULE',
    'bg-yellow-700/20 text-yellow-300 border-yellow-500/30',
    '🍞',
    `${BASE_ITEM_URL}/toaster/thumbnail.webp`,
    `${BASE_ITEM_URL}/toaster/model.glb`,
    '#a16207',
    0.42,
    ['realistic food', 'bread', 'sourdough', 'bakery', 'loaf', 'rustic', 'home', 'flour']
  ),
  createRealAsset(
    'food-real-seafood-paella',
    'Valencian Saffron Seafood Paella Pan',
    'Realistic Food & Utensils',
    'Traditional Spanish wide paella pan loaded with saffron Calasparra rice, jumbo prawns, blue mussels, calamari, and lemon.',
    'SEAFOOD PAELLA',
    'bg-amber-500/20 text-amber-300 border-amber-400/30',
    '🥘',
    `${BASE_ITEM_URL}/frying-pan/thumbnail.webp`,
    `${BASE_ITEM_URL}/frying-pan/model.glb`,
    '#f59e0b',
    0.48,
    ['realistic food', 'paella', 'spanish', 'seafood', 'saffron', 'shrimp', 'restaurant', 'pan', 'valencia']
  ),
  createRealAsset(
    'food-real-ramen-special',
    'Tonkotsu Pork Ramen with Chashu & Soft-Boiled Egg',
    'Realistic Food & Utensils',
    'Rich cloudy bone broth ramen topped with tender braised pork belly chashu, ramen noodles, bamboo shoots, and marinated ajitsuke egg.',
    'TONKOTSU RAMEN',
    'bg-red-600/20 text-red-300 border-red-500/30',
    '🍜',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#dc2626',
    0.44,
    ['realistic food', 'ramen', 'tonkotsu', 'noodles', 'japanese', 'restaurant', 'chashu', 'egg']
  ),
  createRealAsset(
    'food-real-french-baguette',
    'Crispy French Baguette Loaves in Paper Bag',
    'Realistic Food & Utensils',
    'Trio of slender golden Parisian baguettes with diagonal scoring and crisp crackling crust.',
    'PARIS BAGUETTE',
    'bg-amber-700/20 text-amber-300 border-amber-600/30',
    '🥖',
    `${BASE_ITEM_URL}/toaster/thumbnail.webp`,
    `${BASE_ITEM_URL}/toaster/model.glb`,
    '#b45309',
    0.45,
    ['realistic food', 'baguette', 'french', 'bread', 'paris', 'bakery', 'crispy']
  ),
  createRealAsset(
    'food-real-avocado-toast',
    'Cafe Sourdough Avocado Toast with Poached Egg',
    'Realistic Food & Utensils',
    'Thick-cut grilled multigrain sourdough topped with crushed Haas avocado, microgreens, chili flakes, and runny poached egg.',
    'AVOCADO TOAST',
    'bg-emerald-600/20 text-emerald-300 border-emerald-500/30',
    '🥑',
    `${BASE_ITEM_URL}/cutting-board/thumbnail.webp`,
    `${BASE_ITEM_URL}/cutting-board/model.glb`,
    '#059669',
    0.38,
    ['realistic food', 'avocado', 'toast', 'cafe', 'breakfast', 'brunch', 'healthy', 'egg']
  ),
  createRealAsset(
    'food-real-chocolate-layer-cake',
    'Decadent Triple Dark Chocolate Fudge Cake',
    'Realistic Food & Utensils',
    'Multi-tier dark Belgian chocolate gateau filled with silky ganache, chocolate curl shavings, and fresh red raspberries.',
    'CHOCOLATE CAKE',
    'bg-amber-950/20 text-amber-300 border-amber-800/30',
    '🎂',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#451a03',
    0.46,
    ['realistic food', 'cake', 'chocolate', 'dessert', 'fudge', 'bakery', 'patisserie', 'sweet']
  ),
  createRealAsset(
    'food-real-indian-butter-chicken',
    'Murgh Makhani Butter Chicken with Garlic Naan',
    'Realistic Food & Utensils',
    'Aromatic Indian curry with tender tandoori chicken simmered in rich tomato cream sauce, garnished with coriander and warm garlic naan.',
    'BUTTER CHICKEN',
    'bg-orange-600/20 text-orange-300 border-orange-500/30',
    '🍛',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#ea580c',
    0.44,
    ['realistic food', 'curry', 'indian', 'butter chicken', 'naan', 'tandoori', 'spices', 'restaurant']
  ),
  createRealAsset(
    'food-real-roasted-turkey',
    'Golden Herb-Roasted Holiday Turkey Platter',
    'Realistic Food & Utensils',
    'Whole oven-roasted turkey with mahogany herb-basted skin, rosemary stuffing, roasted root vegetables, and cranberry sauce bowl.',
    'ROASTED TURKEY',
    'bg-amber-800/20 text-amber-300 border-amber-600/30',
    '🦃',
    `${BASE_ITEM_URL}/cutting-board/thumbnail.webp`,
    `${BASE_ITEM_URL}/cutting-board/model.glb`,
    '#92400e',
    0.55,
    ['realistic food', 'turkey', 'roast', 'holiday', 'thanksgiving', 'dinner', 'platter', 'poultry']
  ),
  createRealAsset(
    'food-real-belgian-waffles',
    'Brussels Belgian Waffles with Maple Syrup & Berries',
    'Realistic Food & Utensils',
    'Deep-pocket crisp Belgian golden waffles dusted with confectioner powder sugar, whipped butter, and fresh blueberries.',
    'BELGIAN WAFFLE',
    'bg-yellow-600/20 text-yellow-300 border-yellow-500/30',
    '🧇',
    `${BASE_ITEM_URL}/cutting-board/thumbnail.webp`,
    `${BASE_ITEM_URL}/cutting-board/model.glb`,
    '#ca8a04',
    0.40,
    ['realistic food', 'waffle', 'breakfast', 'maple syrup', 'berries', 'brunch', 'dessert', 'sweet']
  )
];

// ============================================================================
// 2. CARTOON & STYLIZED FOOD, BEVERAGES, UTENSILS, BOTTLES & CANS (36+ items)
// ============================================================================
export const CARTOON_FOOD_UTENSILS_ASSETS: Real3DAsset[] = [
  // --- CARTOON CANS & BOTTLES ---
  createRealAsset(
    'food-toon-soda-can',
    'Toon Bubbly Soda Can with Pop Tab',
    'Cartoon Food & Treats',
    'Vibrant cartoon red soda can with white wave swirl, pop-tab lid, and bubbly fizz graphic particles.',
    'TOON SODA CAN',
    'bg-red-500/20 text-red-300 border-red-400/30',
    '🥫',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#ef4444',
    0.30,
    ['cartoon food', 'toon', 'soda', 'can', 'fizzy', 'drink', 'beverage', 'pop', 'stylized']
  ),
  createRealAsset(
    'food-toon-boba-cup',
    'Toon Sweet Strawberry Boba Milk Tea',
    'Cartoon Food & Treats',
    'Cute pastel pink bubble tea cup with dome lid, oversized fat purple straw, and smiling black tapioca pearls.',
    'TOON BOBA TEA',
    'bg-pink-500/20 text-pink-300 border-pink-400/30',
    '🧋',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#ec4899',
    0.34,
    ['cartoon food', 'toon', 'boba', 'bubble tea', 'tapioca', 'drink', 'cute', 'sweet', 'stylized']
  ),
  createRealAsset(
    'food-toon-strawberry-milk-carton',
    'Toon Kawaii Strawberry Milk Carton',
    'Cartoon Food & Treats',
    'Pastel pink geometric mini milk carton with cute cow illustration, Japanese katakana lettering, and straw hole.',
    'TOON MILK CARTON',
    'bg-rose-400/20 text-rose-200 border-rose-300/30',
    '🥛',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#f43f5e',
    0.28,
    ['cartoon food', 'toon', 'milk', 'strawberry', 'kawaii', 'carton', 'cute', 'beverage', 'stylized']
  ),
  createRealAsset(
    'food-toon-energy-drink-can',
    'Toon Hyper Neon Energy Drink Can',
    'Cartoon Food & Treats',
    'Electric lime-green cartoon beverage can with lightning bolt graphic and neon glow highlights.',
    'ENERGY DRINK',
    'bg-lime-500/20 text-lime-300 border-lime-400/30',
    '⚡',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#84cc16',
    0.30,
    ['cartoon food', 'toon', 'energy drink', 'can', 'neon', 'lightning', 'gamer', 'stylized']
  ),
  createRealAsset(
    'food-toon-ketchup-mustard-squirt',
    'Toon Squeeze Ketchup & Mustard Bottles Pair',
    'Cartoon Food & Treats',
    'Classic red and yellow diner condiment squeeze bottles with pointed cone nozzles and comical chubby proportions.',
    'TOON SQUEEZE BOTTLES',
    'bg-yellow-500/20 text-yellow-300 border-yellow-400/30',
    '🧴',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#eab308',
    0.32,
    ['cartoon food', 'toon', 'ketchup', 'mustard', 'bottle', 'condiment', 'diner', 'sauce', 'stylized']
  ),
  createRealAsset(
    'food-toon-hot-sauce-flame',
    'Toon Inferno Hot Sauce Bottle with Flame Cap',
    'Cartoon Food & Treats',
    'Chubby cartoon glass sauce bottle with fiery sculpted flame stopper and warning chili skull label.',
    'TOON HOT SAUCE',
    'bg-orange-600/20 text-orange-300 border-orange-500/30',
    '🔥',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#ea580c',
    0.32,
    ['cartoon food', 'toon', 'hot sauce', 'flame', 'spicy', 'bottle', 'chili', 'stylized']
  ),
  createRealAsset(
    'food-toon-honey-pot-jar',
    'Toon Sweet Honey Pot Jar & Dripping Honey Dipper',
    'Cartoon Food & Treats',
    'Earthen round ceramic honey pot with golden dripping honey, bumblebee sticker, and wooden ribbed honey wand.',
    'HONEY POT',
    'bg-amber-500/20 text-amber-300 border-amber-400/30',
    '🍯',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#f59e0b',
    0.34,
    ['cartoon food', 'toon', 'honey', 'pot', 'jar', 'bee', 'sweet', 'cozy', 'stylized']
  ),
  createRealAsset(
    'food-toon-juice-box',
    'Toon Apple Juice Box with Bendy Straw',
    'Cartoon Food & Treats',
    'Bright green juice box with smiling red apple graphic and flexible plastic bendy straw poking out.',
    'JUICE BOX',
    'bg-emerald-500/20 text-emerald-300 border-emerald-400/30',
    '🧃',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#10b981',
    0.28,
    ['cartoon food', 'toon', 'juice', 'box', 'straw', 'lunch', 'kid', 'apple', 'stylized']
  ),
  createRealAsset(
    'food-toon-magic-potion',
    'Toon Bubbling Mana Potion Elixir Bottle',
    'Cartoon Food & Treats',
    'Round glass alchemy flask filled with glowing starry cyan potion liquid, cork stopper, and leather strap.',
    'MANA POTION',
    'bg-cyan-500/20 text-cyan-300 border-cyan-400/30',
    '🧪',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#06b6d4',
    0.32,
    ['cartoon food', 'toon', 'potion', 'magic', 'mana', 'bottle', 'flask', 'glowing', 'fantasy', 'stylized']
  ),

  // --- CARTOON UTENSILS & COOKWARE ---
  createRealAsset(
    'food-toon-chef-cleaver',
    'Toon Oversized Giant Meat Cleaver',
    'Cartoon Food & Treats',
    'Exaggerated wide stainless butcher cleaver with shiny blade glint and chunky dark wood handle.',
    'TOON CLEAVER',
    'bg-slate-600/20 text-slate-300 border-slate-500/30',
    '🔪',
    `${BASE_ITEM_URL}/kitchen-utensils/thumbnail.webp`,
    `${BASE_ITEM_URL}/kitchen-utensils/model.glb`,
    '#475569',
    0.38,
    ['cartoon food', 'toon', 'utensil', 'cleaver', 'knife', 'chef', 'blade', 'butcher', 'stylized']
  ),
  createRealAsset(
    'food-toon-egg-frying-pan',
    'Toon Frying Pan with Sunny-Side-Up Egg',
    'Cartoon Food & Treats',
    'Matte black cartoon skillet with a cheerful cartoon fried egg featuring bouncy yellow yolk and crisp edges.',
    'TOON SKILLET EGG',
    'bg-yellow-500/20 text-yellow-300 border-yellow-400/30',
    '🍳',
    `${BASE_ITEM_URL}/frying-pan/thumbnail.webp`,
    `${BASE_ITEM_URL}/frying-pan/model.glb`,
    '#eab308',
    0.40,
    ['cartoon food', 'toon', 'utensil', 'pan', 'egg', 'breakfast', 'skillet', 'sunny side up', 'stylized']
  ),
  createRealAsset(
    'food-toon-wooden-rolling-pin',
    'Toon Baker Wooden Rolling Pin',
    'Cartoon Food & Treats',
    'Smooth blonde wooden pastry rolling pin with comfortable curved red painted handles.',
    'ROLLING PIN',
    'bg-amber-600/20 text-amber-300 border-amber-500/30',
    '🥖',
    `${BASE_ITEM_URL}/toaster/thumbnail.webp`,
    `${BASE_ITEM_URL}/toaster/model.glb`,
    '#d97706',
    0.36,
    ['cartoon food', 'toon', 'utensil', 'rolling pin', 'baking', 'wood', 'pastry', 'chef', 'stylized']
  ),
  createRealAsset(
    'food-toon-giant-fork-spoon',
    'Toon Giant Cutlery Fork & Spoon Duo',
    'Cartoon Food & Treats',
    'Comically oversized polished silver dinner fork and deep soup spoon with rounded cartoon proportions.',
    'TOON CUTLERY',
    'bg-sky-500/20 text-sky-300 border-sky-400/30',
    '🍴',
    `${BASE_ITEM_URL}/kitchen-utensils/thumbnail.webp`,
    `${BASE_ITEM_URL}/kitchen-utensils/model.glb`,
    '#0ea5e9',
    0.35,
    ['cartoon food', 'toon', 'utensil', 'fork', 'spoon', 'cutlery', 'dining', 'tableware', 'stylized']
  ),
  createRealAsset(
    'food-toon-salt-pepper-shakers',
    'Toon Smiling Salt & Pepper Shakers',
    'Cartoon Food & Treats',
    "Chubby porcelain salt and pepper shakers with friendly painted face expressions and 'S' and 'P' hole patterns.",
    'SALT & PEPPER',
    'bg-stone-500/20 text-stone-300 border-stone-400/30',
    '🧂',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#78716c',
    0.30,
    ['cartoon food', 'toon', 'utensil', 'salt', 'pepper', 'shaker', 'spices', 'seasoning', 'stylized']
  ),
  createRealAsset(
    'food-toon-tea-party-teapot',
    'Toon Whimsical Fairy Tea Party Teapot',
    'Cartoon Food & Treats',
    'Plump pastel blue porcelain teapot with gold polka dots, rosebud lid handle, and curly pouring spout.',
    'TOON TEAPOT',
    'bg-indigo-500/20 text-indigo-300 border-indigo-400/30',
    '🫖',
    `${BASE_ITEM_URL}/kettle/thumbnail.webp`,
    `${BASE_ITEM_URL}/kettle/model.glb`,
    '#6366f1',
    0.38,
    ['cartoon food', 'toon', 'utensil', 'teapot', 'tea', 'tea party', 'fairy', 'cozy', 'stylized']
  ),
  createRealAsset(
    'food-toon-bento-lunchbox',
    'Toon Japanese Kawaii Bento Box Container',
    'Cartoon Food & Treats',
    'Two-tier lacquered red bento box with panda rice balls, octopus sausages, rolled tamagoyaki egg, and edamame.',
    'TOON BENTO BOX',
    'bg-red-600/20 text-red-300 border-red-400/30',
    '🍱',
    `${BASE_ITEM_URL}/cutting-board/thumbnail.webp`,
    `${BASE_ITEM_URL}/cutting-board/model.glb`,
    '#dc2626',
    0.42,
    ['cartoon food', 'toon', 'bento', 'lunchbox', 'japanese', 'kawaii', 'onigiri', 'panda', 'stylized']
  ),
  createRealAsset(
    'food-toon-blender-smoothie',
    'Toon Countertop Blender with Tropical Smoothie',
    'Cartoon Food & Treats',
    'Cute retro countertop blender with clear glass jug whipping up bright coral tropical smoothie with fruit slices.',
    'TOON BLENDER',
    'bg-teal-500/20 text-teal-300 border-teal-400/30',
    '🍹',
    `${BASE_ITEM_URL}/kettle/thumbnail.webp`,
    `${BASE_ITEM_URL}/kettle/model.glb`,
    '#14b8a6',
    0.42,
    ['cartoon food', 'toon', 'utensil', 'blender', 'smoothie', 'kitchen', 'appliance', 'tropical', 'stylized']
  ),

  // --- CARTOON DISHES, SNACKS & SWEETS ---
  createRealAsset(
    'food-toon-giant-pizza-slice',
    'Toon Giant Cheesy Pepperoni Pizza Slice',
    'Cartoon Food & Treats',
    'Oversized cartoon pizza wedge with super stretchy gooey yellow cheese pull and glistening circular pepperoni cups.',
    'TOON PIZZA SLICE',
    'bg-amber-500/20 text-amber-300 border-amber-400/30',
    '🍕',
    `${BASE_ITEM_URL}/cutting-board/thumbnail.webp`,
    `${BASE_ITEM_URL}/cutting-board/model.glb`,
    '#f59e0b',
    0.48,
    ['cartoon food', 'toon', 'pizza', 'cheese', 'pepperoni', 'slice', 'diner', 'party', 'stylized']
  ),
  createRealAsset(
    'food-toon-stacked-cheeseburger',
    'Toon Stacked Triple Deluxe Cheeseburger',
    'Cartoon Food & Treats',
    'Chunky cartoon burger piled high with sesame seed bun, thick patty, wavy melted cheese drips, and crisp lettuce ruffle.',
    'TOON BURGER',
    'bg-orange-500/20 text-orange-300 border-orange-400/30',
    '🍔',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#f97316',
    0.44,
    ['cartoon food', 'toon', 'burger', 'cheeseburger', 'fast food', 'patty', 'sesame', 'stylized']
  ),
  createRealAsset(
    'food-toon-crinkle-french-fries',
    'Toon Red Carton Crinkle-Cut French Fries',
    'Cartoon Food & Treats',
    'Bright red takeaway carton bursting with golden crinkle-cut crispy cartoon french fries and ketchup dab.',
    'TOON FRIES',
    'bg-yellow-500/20 text-yellow-300 border-yellow-400/30',
    '🍟',
    `${BASE_ITEM_URL}/toaster/thumbnail.webp`,
    `${BASE_ITEM_URL}/toaster/model.glb`,
    '#eab308',
    0.38,
    ['cartoon food', 'toon', 'fries', 'french fries', 'fast food', 'potatoes', 'carton', 'stylized']
  ),
  createRealAsset(
    'food-toon-anime-ramen',
    'Toon Anime Noodle Bowl with Narutomaki Fishcake',
    'Cartoon Food & Treats',
    'Stylized steaming noodle bowl with iconic pink swirl narutomaki, floating egg halves, and chopsticks resting on rim.',
    'ANIME RAMEN',
    'bg-red-500/20 text-red-300 border-red-400/30',
    '🍜',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#ef4444',
    0.42,
    ['cartoon food', 'toon', 'ramen', 'noodles', 'anime', 'naruto', 'japan', 'steaming', 'stylized']
  ),
  createRealAsset(
    'food-toon-pink-frosted-donut',
    'Toon Strawberry Glazed Donut with Rainbow Sprinkles',
    'Cartoon Food & Treats',
    'Chubby cartoon ring donut smothered in glossy pink strawberry icing and colorful rainbow sugar jimmies.',
    'TOON DONUT',
    'bg-pink-500/20 text-pink-300 border-pink-400/30',
    '🍩',
    `${BASE_ITEM_URL}/toaster/thumbnail.webp`,
    `${BASE_ITEM_URL}/toaster/model.glb`,
    '#ec4899',
    0.34,
    ['cartoon food', 'toon', 'donut', 'doughnut', 'sprinkles', 'pink', 'strawberry', 'sweet', 'stylized']
  ),
  createRealAsset(
    'food-toon-ice-cream-sundae-cone',
    'Toon Triple Scoop Waffle Cone Sundae',
    'Cartoon Food & Treats',
    'Crispy waffle cone piled with mint chip, strawberry, and chocolate ice cream scoops topped with a glossy red cherry.',
    'TOON ICE CREAM',
    'bg-cyan-500/20 text-cyan-300 border-cyan-400/30',
    '🍦',
    `${BASE_ITEM_URL}/toaster/thumbnail.webp`,
    `${BASE_ITEM_URL}/toaster/model.glb`,
    '#06b6d4',
    0.38,
    ['cartoon food', 'toon', 'ice cream', 'sundae', 'cone', 'waffle', 'cherry', 'summer', 'sweet', 'stylized']
  ),
  createRealAsset(
    'food-toon-crunchy-taco',
    'Toon Smiling Golden Crunchy Hard-Shell Taco',
    'Cartoon Food & Treats',
    'Golden U-shaped crunchy taco shell loaded with spiced ground filling, shredded cheddar ribbons, and lettuce curls.',
    'TOON TACO',
    'bg-amber-500/20 text-amber-300 border-amber-400/30',
    '🌮',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#f59e0b',
    0.36,
    ['cartoon food', 'toon', 'taco', 'mexican', 'fiesta', 'cheese', 'crunchy', 'fast food', 'stylized']
  ),
  createRealAsset(
    'food-toon-hot-dog-mustard',
    'Toon Ballpark Hot Dog with Mustard Swirl',
    'Cartoon Food & Treats',
    'Plump frankfurter sausage nestled in a soft bun with a dynamic zigzag yellow mustard drizzle.',
    'TOON HOT DOG',
    'bg-orange-600/20 text-orange-300 border-orange-400/30',
    '🌭',
    `${BASE_ITEM_URL}/toaster/thumbnail.webp`,
    `${BASE_ITEM_URL}/toaster/model.glb`,
    '#ea580c',
    0.36,
    ['cartoon food', 'toon', 'hot dog', 'mustard', 'sausage', 'baseball', 'diner', 'snack', 'stylized']
  ),
  createRealAsset(
    'food-toon-sushi-maki-roll',
    'Toon Happy Salmon Sushi Maki Roll Set',
    'Cartoon Food & Treats',
    'Cute cylindrical sushi maki rolls wrapped in dark nori seaweed with coral salmon center and smiling face.',
    'TOON SUSHI MAKI',
    'bg-emerald-600/20 text-emerald-300 border-emerald-400/30',
    '🍣',
    `${BASE_ITEM_URL}/cutting-board/thumbnail.webp`,
    `${BASE_ITEM_URL}/cutting-board/model.glb`,
    '#059669',
    0.35,
    ['cartoon food', 'toon', 'sushi', 'maki', 'nori', 'salmon', 'japanese', 'kawaii', 'stylized']
  ),
  createRealAsset(
    'food-toon-pancake-stack',
    'Toon Fluffy Pancake Tower with Melting Butter',
    'Cartoon Food & Treats',
    'High stack of golden fluffy cartoon pancakes with a melting square butter cube and dripping amber maple syrup.',
    'TOON PANCAKES',
    'bg-yellow-600/20 text-yellow-300 border-yellow-500/30',
    '🥞',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#ca8a04',
    0.42,
    ['cartoon food', 'toon', 'pancakes', 'breakfast', 'syrup', 'butter', 'stack', 'sweet', 'stylized']
  ),
  createRealAsset(
    'food-toon-birthday-cake-candle',
    'Toon Birthday Cake with Glowing Candle',
    'Cartoon Food & Treats',
    'Festive pastel birthday sponge cake with blue frosting swirls, piped rosettes, and a flickering golden candle flame.',
    'BIRTHDAY CAKE',
    'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-400/30',
    '🎂',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#d946ef',
    0.44,
    ['cartoon food', 'toon', 'cake', 'birthday', 'candle', 'celebration', 'party', 'frosting', 'stylized']
  ),
  createRealAsset(
    'food-toon-onigiri-rice-ball',
    'Toon Japanese Onigiri Rice Triangle with Nori',
    'Cartoon Food & Treats',
    'Cute rounded triangular white rice ball with crisp dark nori seaweed wrapper and cheerful blushing cheeks.',
    'TOON ONIGIRI',
    'bg-stone-500/20 text-stone-300 border-stone-400/30',
    '🍙',
    `${BASE_ITEM_URL}/cutting-board/thumbnail.webp`,
    `${BASE_ITEM_URL}/cutting-board/model.glb`,
    '#78716c',
    0.32,
    ['cartoon food', 'toon', 'onigiri', 'rice', 'japanese', 'nori', 'kawaii', 'snack', 'stylized']
  ),
  createRealAsset(
    'food-toon-giant-choc-chip-cookie',
    'Toon Giant Chocolate Chip Cookie',
    'Cartoon Food & Treats',
    'Chewy golden brown cartoon cookie studded with melting dark chocolate morsel chunks.',
    'TOON COOKIE',
    'bg-amber-700/20 text-amber-300 border-amber-600/30',
    '🍪',
    `${BASE_ITEM_URL}/toaster/thumbnail.webp`,
    `${BASE_ITEM_URL}/toaster/model.glb`,
    '#b45309',
    0.32,
    ['cartoon food', 'toon', 'cookie', 'chocolate chip', 'biscuit', 'bakery', 'snack', 'sweet', 'stylized']
  ),
  createRealAsset(
    'food-toon-turkey-drumstick',
    'Toon Medieval Cartoon Roast Turkey Drumstick',
    'Cartoon Food & Treats',
    'Iconic cartoon roast meat drumstick with shiny glazed mahogany skin and clean white bone handle.',
    'ROAST DRUMSTICK',
    'bg-amber-800/20 text-amber-300 border-amber-600/30',
    '🍗',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#92400e',
    0.38,
    ['cartoon food', 'toon', 'drumstick', 'meat', 'turkey', 'chicken', 'roast', 'medieval', 'stylized']
  ),
  createRealAsset(
    'food-toon-swiss-cheese-wedge',
    'Toon Swiss Cheese Triangle Wedge',
    'Cartoon Food & Treats',
    'Bright yellow triangular cheese wedge with comical rounded mouse holes and rind texture.',
    'TOON CHEESE WEDGE',
    'bg-yellow-500/20 text-yellow-300 border-yellow-400/30',
    '🧀',
    `${BASE_ITEM_URL}/toaster/thumbnail.webp`,
    `${BASE_ITEM_URL}/toaster/model.glb`,
    '#eab308',
    0.34,
    ['cartoon food', 'toon', 'cheese', 'swiss', 'wedge', 'yellow', 'dairy', 'snack', 'stylized']
  ),
  createRealAsset(
    'food-toon-movie-popcorn-bucket',
    'Toon Striped Movie Popcorn Bucket',
    'Cartoon Food & Treats',
    'Red-and-white striped cinema tub overflowing with fluffy buttery popped corn kernels.',
    'TOON POPCORN',
    'bg-red-500/20 text-red-300 border-red-400/30',
    '🍿',
    `${BASE_ITEM_URL}/fruits/thumbnail.webp`,
    `${BASE_ITEM_URL}/fruits/model.glb`,
    '#ef4444',
    0.40,
    ['cartoon food', 'toon', 'popcorn', 'movie', 'cinema', 'butter', 'snack', 'bucket', 'stylized']
  ),
  createRealAsset(
    'food-toon-spiral-lollipop',
    'Toon Giant Rainbow Swirl Candy Lollipop',
    'Cartoon Food & Treats',
    'Big colorful swirled rainbow hard candy disc mounted on a white candy stick with a satin bow.',
    'TOON LOLLIPOP',
    'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-400/30',
    '🍭',
    `${BASE_ITEM_URL}/toaster/thumbnail.webp`,
    `${BASE_ITEM_URL}/toaster/model.glb`,
    '#d946ef',
    0.36,
    ['cartoon food', 'toon', 'lollipop', 'candy', 'rainbow', 'sweet', 'sugar', 'treat', 'stylized']
  ),
  createRealAsset(
    'food-toon-soft-pretzel',
    'Toon Golden Baked Bavarian Soft Pretzel',
    'Cartoon Food & Treats',
    'Twisted deep brown bakery soft pretzel sprinkled with chunky white rock salt crystals.',
    'TOON PRETZEL',
    'bg-amber-700/20 text-amber-300 border-amber-600/30',
    '🥨',
    `${BASE_ITEM_URL}/toaster/thumbnail.webp`,
    `${BASE_ITEM_URL}/toaster/model.glb`,
    '#b45309',
    0.36,
    ['cartoon food', 'toon', 'pretzel', 'bavarian', 'bakery', 'salt', 'bread', 'snack', 'stylized']
  )
];

// ============================================================================
// 3. COMBINED FOOD & UTENSIL ASSETS COLLECTION
// ============================================================================
export const FOOD_UTENSIL_ASSETS: Real3DAsset[] = [
  ...REALISTIC_FOOD_UTENSILS_ASSETS,
  ...CARTOON_FOOD_UTENSILS_ASSETS
];
