import { Real3DAsset, createRealAsset, BASE_ITEM_URL, BASE_KHRONOS_URL } from './types';

export const FURNITURE_ASSETS: Real3DAsset[] = [
  createRealAsset(
    'furn-chair-office',
    'Executive Mesh Ergonomic Chair',
    'Furniture',
    'High-back ergonomic lumbar task chair with 4D adjustable armrests and mesh backing.',
    'TASK CHAIR',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🪑',
    `${BASE_ITEM_URL}/office-chair/thumbnail.webp`,
    `${BASE_ITEM_URL}/office-chair/model.glb`,
    '#2563eb',
    0.45,
    ['chair', 'office', 'ergonomic', 'furniture', 'workstation']
  ),
  createRealAsset(
    'furn-chair-leather',
    'Mid-Century Leather Armchair',
    'Furniture',
    'Caramel full-grain leather accent lounge chair with solid walnut timber frame.',
    'LEATHER CHAIR',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🛋️',
    `${BASE_ITEM_URL}/livingroom-chair/thumbnail.webp`,
    `${BASE_ITEM_URL}/livingroom-chair/model.glb`,
    '#d97706',
    0.50,
    ['chair', 'leather', 'lounge', 'accent', 'mid-century']
  ),
  createRealAsset(
    'furn-chair-plastic',
    'Molded Polypropylene Side Chair',
    'Furniture',
    'Contemporary molded shell dining chair on natural beechwood Eiffel legs.',
    'SIDE CHAIR',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🪑',
    `${BASE_ITEM_URL}/dining-chair/thumbnail.webp`,
    `${BASE_ITEM_URL}/dining-chair/model.glb`,
    '#10b981',
    0.38,
    ['chair', 'dining', 'modern', 'polypropylene']
  ),
  createRealAsset(
    'furn-armchair',
    'Scandinavian Fabric Armchair',
    'Furniture',
    'Textured woven wool upholstered armchair with curved ergonomic armrests.',
    'ARMCHAIR',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🛋️',
    `${BASE_ITEM_URL}/livingroom-chair/thumbnail.webp`,
    `${BASE_ITEM_URL}/livingroom-chair/model.glb`,
    '#4f46e5',
    0.52,
    ['armchair', 'lounge', 'fabric', 'scandinavian']
  ),
  createRealAsset(
    'furn-chair-stool',
    'Industrial Swivel Bar Stool',
    'Furniture',
    'Counter-height industrial steel frame swivel bar stool with round solid oak seat.',
    'BAR STOOL',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🪑',
    `${BASE_ITEM_URL}/stool/thumbnail.webp`,
    `${BASE_ITEM_URL}/stool/model.glb`,
    '#475569',
    0.35,
    ['stool', 'bar stool', 'kitchen', 'counter', 'industrial']
  ),
  createRealAsset(
    'furn-chair-lounge',
    'Modernist Reclining Lounge Chair',
    'Furniture',
    'Architectural low-profile contour lounge chair with ottoman footstool.',
    'LOUNGE CHAIR',
    'bg-purple-500/20 text-purple-300 border-purple-500/30',
    '🛋️',
    `${BASE_ITEM_URL}/lounge-chair/thumbnail.webp`,
    `${BASE_ITEM_URL}/lounge-chair/model.glb`,
    '#9333ea',
    0.60,
    ['lounge', 'chair', 'ottoman', 'living room', 'recliner']
  ),
  createRealAsset(
    'furn-couch-corner',
    'Modular L-Shape Sectional Sofa',
    'Furniture',
    'Deep-seated architectural 5-seater corner sectional sofa with plush cushions.',
    'CORNER SOFA',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🛋️',
    `${BASE_ITEM_URL}/couch-medium/thumbnail.webp`,
    `${BASE_ITEM_URL}/couch-medium/model.glb`,
    '#3730a3',
    0.95,
    ['sofa', 'sectional', 'couch', 'living room', 'modular']
  ),
  createRealAsset(
    'furn-couch-small',
    '2-Seater Velvet Loveseat',
    'Furniture',
    'Compact luxury jewel-toned velvet upholstered 2-seater apartment sofa.',
    'LOVESEAT',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🛋️',
    `${BASE_ITEM_URL}/couch-small/thumbnail.webp`,
    `${BASE_ITEM_URL}/couch-small/model.glb`,
    '#4338ca',
    0.68,
    ['couch', 'loveseat', 'compact', 'furniture']
  ),
  createRealAsset(
    'furn-bean-bag',
    'Plush Lounging Bean Bag',
    'Furniture',
    'Oversized ergonomic foam-filled plush lounging bean bag chair.',
    'BEAN BAG',
    'bg-purple-500/20 text-purple-300 border-purple-500/30',
    '🛋️',
    `${BASE_ITEM_URL}/bean-bag/thumbnail.webp`,
    `${BASE_ITEM_URL}/bean-bag/model.glb`,
    '#7e22ce',
    0.55,
    ['bean bag', 'lounge', 'chair', 'plush', 'casual']
  ),
  createRealAsset(
    'furn-sunbed',
    'Poolside Resort Lounger Sunbed',
    'Furniture',
    'Weatherproof teak wood reclining sunbed with padded water-resistant cushion.',
    'SUNBED',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🏖️',
    `${BASE_ITEM_URL}/sunbed/thumbnail.webp`,
    `${BASE_ITEM_URL}/sunbed/model.glb`,
    '#d97706',
    0.85,
    ['sunbed', 'lounger', 'pool', 'resort', 'patio']
  ),
  createRealAsset(
    'furn-coffee-table',
    'Minimalist Glass Coffee Table',
    'Furniture',
    'Architectural coffee table with tempered glass surface and dark walnut structural frame.',
    'COFFEE TABLE',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '🛋️',
    `${BASE_ITEM_URL}/coffee-table/thumbnail.webp`,
    `${BASE_ITEM_URL}/coffee-table/model.glb`,
    '#0284c7',
    0.48,
    ['table', 'coffee', 'living room', 'glass', 'minimal']
  ),
  createRealAsset(
    'furn-dining-table',
    'Solid Timber Dining Table',
    'Furniture',
    'Solid architectural timber dining table for residential dining and hospitality.',
    'DINING TABLE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🍽️',
    `${BASE_ITEM_URL}/dining-table/thumbnail.webp`,
    `${BASE_ITEM_URL}/dining-table/model.glb`,
    '#b45309',
    0.90,
    ['table', 'dining', 'wood', 'gathering']
  ),
  createRealAsset(
    'furn-desk',
    'Executive Studio Desk',
    'Furniture',
    'Solid natural oak desktop on matte black powder-coated steel trestle base.',
    'STUDIO DESK',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '💻',
    `${BASE_ITEM_URL}/desk/thumbnail.webp`,
    `${BASE_ITEM_URL}/desk/model.glb`,
    '#b45309',
    0.75,
    ['desk', 'office', 'wood', 'studio', 'workstation']
  ),
  createRealAsset(
    'furn-office-table',
    'Conference Meeting Table',
    'Furniture',
    'Long-span architectural executive boardroom conference meeting table.',
    'BOARD TABLE',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '📊',
    `${BASE_ITEM_URL}/office-table/thumbnail.webp`,
    `${BASE_ITEM_URL}/office-table/model.glb`,
    '#059669',
    0.88,
    ['table', 'conference', 'meeting', 'office']
  ),
  createRealAsset(
    'furn-table',
    'Round Pedestal Bistro Table',
    'Furniture',
    'Architectural round cafe pedestal bistro table with cast aluminum base.',
    'BISTRO TABLE',
    'bg-teal-500/20 text-teal-300 border-teal-500/30',
    '☕',
    `${BASE_ITEM_URL}/table/thumbnail.webp`,
    `${BASE_ITEM_URL}/table/model.glb`,
    '#0d9488',
    0.50,
    ['table', 'round', 'bistro', 'cafe']
  ),
  createRealAsset(
    'furn-bedside-table',
    'Floating Nightstand Bedside Table',
    'Furniture',
    'Compact Scandinavian bedside table with push-to-open drawer.',
    'NIGHTSTAND',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🛏️',
    `${BASE_ITEM_URL}/bedside-table/thumbnail.webp`,
    `${BASE_ITEM_URL}/bedside-table/model.glb`,
    '#d97706',
    0.35,
    ['table', 'bedside', 'nightstand', 'bedroom']
  ),
  createRealAsset(
    'furn-double-bed',
    'Platform Double Bed Suite',
    'Furniture',
    'King-size upholstered architectural platform double bed with integrated headboard.',
    'DOUBLE BED',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🛏️',
    `${BASE_ITEM_URL}/double-bed/thumbnail.webp`,
    `${BASE_ITEM_URL}/double-bed/model.glb`,
    '#4f46e5',
    1.00,
    ['bed', 'double bed', 'bedroom', 'mattress', 'sleeping']
  ),
  createRealAsset(
    'furn-single-bed',
    'Modern Single Studio Bed',
    'Furniture',
    'Clean minimalist single bed frame with orthopedic mattress foundation.',
    'SINGLE BED',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🛏️',
    `${BASE_ITEM_URL}/single-bed/thumbnail.webp`,
    `${BASE_ITEM_URL}/single-bed/model.glb`,
    '#4338ca',
    0.65,
    ['bed', 'single bed', 'studio', 'bedroom']
  ),
  createRealAsset(
    'furn-bunkbed',
    'Twin Architectural Bunk Bed',
    'Furniture',
    'Solid wood twin bunk bed unit with integrated access ladder and safety rails.',
    'BUNK BED',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🛏️',
    `${BASE_ITEM_URL}/bunkbed/thumbnail.webp`,
    `${BASE_ITEM_URL}/bunkbed/model.glb`,
    '#3730a3',
    0.85,
    ['bunkbed', 'bed', 'kids', 'bedroom', 'ladder']
  ),
  createRealAsset(
    'furn-bookshelf',
    'Nordic Modular Bookshelf',
    'Furniture',
    'Multi-tier open architectural shelving unit for product display or gallery presentation.',
    'BOOKSHELF',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '📚',
    `${BASE_ITEM_URL}/bookshelf/thumbnail.webp`,
    `${BASE_ITEM_URL}/bookshelf/model.glb`,
    '#10b981',
    0.70,
    ['bookshelf', 'storage', 'library', 'display']
  ),
  createRealAsset(
    'furn-shelf',
    'Floating Wall Shelf Unit',
    'Furniture',
    'Minimalist architectural floating wall shelf with concealed bracket hardware.',
    'WALL SHELF',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '📦',
    `${BASE_ITEM_URL}/shelf/thumbnail.webp`,
    `${BASE_ITEM_URL}/shelf/model.glb`,
    '#059669',
    0.45,
    ['shelf', 'wall', 'storage', 'floating']
  ),
  createRealAsset(
    'furn-closet',
    'Full-Height Wardrobe Closet',
    'Furniture',
    'Architectural full-height double-door wardrobe with interior hanging rail.',
    'WARDROBE',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🚪',
    `${BASE_ITEM_URL}/closet/thumbnail.webp`,
    `${BASE_ITEM_URL}/closet/model.glb`,
    '#52525b',
    0.85,
    ['closet', 'wardrobe', 'storage', 'bedroom', 'clothing']
  ),
  createRealAsset(
    'furn-khronos-sheen-chair',
    'Glam Velvet Sheen Accent Chair',
    'Furniture',
    'PBR sheen-textured velvet designer accent chair with brass tapered legs.',
    'SHEEN CHAIR',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '🪑',
    `${BASE_KHRONOS_URL}/SheenChair/glTF-Binary/SheenChair.glb`,
    `${BASE_KHRONOS_URL}/SheenChair/glTF-Binary/SheenChair.glb`,
    '#f43f5e',
    0.48,
    ['chair', 'velvet', 'luxury', 'accent', 'living room']
  ),
  createRealAsset(
    'furn-glam-velvet-sofa',
    'Curved Hollywood Velvet Sofa',
    'Furniture',
    'Architectural sculptural curved velvet sofa with gold plinth base.',
    'CURVED SOFA',
    'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-500/30',
    '🛋️',
    `${BASE_KHRONOS_URL}/GlamVelvetSofa/glTF-Binary/GlamVelvetSofa.glb`,
    `${BASE_KHRONOS_URL}/GlamVelvetSofa/glTF-Binary/GlamVelvetSofa.glb`,
    '#d946ef',
    0.85,
    ['sofa', 'velvet', 'glam', 'luxury', 'lounge']
  ),
  createRealAsset(
    'furn-standing-desk-electric',
    'Dual-Motor Height Adjustable Standing Desk',
    'Furniture',
    'Modern bamboo top electric motorized height adjustable sit-to-stand desk.',
    'STANDING DESK',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '⚡',
    `${BASE_ITEM_URL}/desk/thumbnail.webp`,
    `${BASE_ITEM_URL}/desk/model.glb`,
    '#d97706',
    0.75,
    ['desk', 'standing desk', 'ergonomic', 'office', 'electric']
  ),
  createRealAsset(
    'furn-tv-credenza',
    'Mid-Century Low TV Media Credenza',
    'Furniture',
    'Slatted walnut sliding-door media entertainment console with cable management.',
    'MEDIA CONSOLE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '📺',
    `${BASE_ITEM_URL}/coffee-table/thumbnail.webp`,
    `${BASE_ITEM_URL}/coffee-table/model.glb`,
    '#78350f',
    0.70,
    ['credenza', 'tv stand', 'media', 'console', 'living room']
  ),
  createRealAsset(
    'furn-entryway-bench',
    'Upholstered Bouclé Entryway Bench',
    'Furniture',
    'Pill-shaped textured cream bouclé bench with blackened steel frame.',
    'ENTRY BENCH',
    'bg-stone-500/20 text-stone-300 border-stone-500/30',
    '🪑',
    `${BASE_ITEM_URL}/couch-small/thumbnail.webp`,
    `${BASE_ITEM_URL}/couch-small/model.glb`,
    '#78716c',
    0.55,
    ['bench', 'entryway', 'boucle', 'seating', 'hallway']
  ),
  createRealAsset(
    'furn-console-table',
    'Fluted Travertine Console Table',
    'Furniture',
    'Architectural honed natural travertine stone console table with fluted pedestal legs.',
    'TRAVERTINE TABLE',
    'bg-stone-500/20 text-stone-300 border-stone-500/30',
    '🏛️',
    `${BASE_ITEM_URL}/office-table/thumbnail.webp`,
    `${BASE_ITEM_URL}/office-table/model.glb`,
    '#a8a29e',
    0.65,
    ['console', 'travertine', 'stone', 'entryway', 'luxury']
  ),
  createRealAsset(
    'furn-bar-cart',
    'Art Deco 2-Tier Brass Bar Cart',
    'Furniture',
    'Round wheeled entertaining beverage trolley with mirrored glass tiers and bottle guard.',
    'BAR CART',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🍸',
    `${BASE_ITEM_URL}/bedside-table/thumbnail.webp`,
    `${BASE_ITEM_URL}/bedside-table/model.glb`,
    '#eab308',
    0.45,
    ['bar cart', 'trolley', 'cocktail', 'entertaining', 'brass']
  ),
  createRealAsset(
    'furn-pouf-ottoman',
    'Braided Jute Round Pouf',
    'Furniture',
    'Natural woven organic jute floor ottoman pouf for relaxed bohemian styling.',
    'JUTE POUF',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🧶',
    `${BASE_ITEM_URL}/bean-bag/thumbnail.webp`,
    `${BASE_ITEM_URL}/bean-bag/model.glb`,
    '#ca8a04',
    0.35,
    ['pouf', 'ottoman', 'jute', 'footrest', 'decor']
  ),
  createRealAsset(
    'furn-room-divider',
    '3-Panel Rattan Folding Screen',
    'Furniture',
    'Natural woven French cane and ash wood 3-panel folding room privacy screen.',
    'RATTAN SCREEN',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🚪',
    `${BASE_ITEM_URL}/closet/thumbnail.webp`,
    `${BASE_ITEM_URL}/closet/model.glb`,
    '#b45309',
    0.70,
    ['divider', 'screen', 'rattan', 'privacy', 'partition']
  ),
  createRealAsset(
    'furn-shoe-rack',
    'Tiered Slatted Shoe Bench',
    'Furniture',
    'Natural bamboo 3-tier entryway footwear storage organizer bench.',
    'SHOE RACK',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '👞',
    `${BASE_ITEM_URL}/shelf/thumbnail.webp`,
    `${BASE_ITEM_URL}/shelf/model.glb`,
    '#92400e',
    0.50,
    ['shoe rack', 'storage', 'entryway', 'bamboo', 'organizer']
  )
];
