import { Real3DAsset, createRealAsset, BASE_ITEM_URL, BASE_KHRONOS_URL } from './types';

export const HOUSEHOLD_ASSETS: Real3DAsset[] = [
  createRealAsset(
    'hh-kitchen-sink',
    'Stainless Steel Kitchen Sink',
    'Household',
    'Under-mount dual bowl stainless steel kitchen sink with gooseneck spray faucet.',
    'KITCHEN SINK',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🚰',
    `${BASE_ITEM_URL}/wall-sink/thumbnail.webp`,
    `${BASE_ITEM_URL}/wall-sink/model.glb`,
    '#475569',
    0.50,
    ['sink', 'kitchen', 'faucet', 'plumbing', 'household']
  ),
  createRealAsset(
    'hh-bathroom-sink',
    'Modern Ceramic Bathroom Vanity',
    'Household',
    'Seamless rectangular white ceramic bathroom vanity vessel sink with chrome tap.',
    'BATH VANITY',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '🚿',
    `${BASE_ITEM_URL}/bathroom-sink/thumbnail.webp`,
    `${BASE_ITEM_URL}/bathroom-sink/model.glb`,
    '#0284c7',
    0.45,
    ['sink', 'bathroom', 'basin', 'vanity', 'plumbing']
  ),
  createRealAsset(
    'hh-bathtub',
    'Freestanding Soaking Bathtub',
    'Household',
    'Contemporary oval freestanding acrylic soaking bathtub with floor-mount filler.',
    'BATHTUB',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🛁',
    `${BASE_ITEM_URL}/bathtub/thumbnail.webp`,
    `${BASE_ITEM_URL}/bathtub/model.glb`,
    '#06b6d4',
    0.85,
    ['bathtub', 'bath', 'bathroom', 'spa', 'tub']
  ),
  createRealAsset(
    'hh-toilet',
    'Dual-Flush Ceramic Toilet',
    'Household',
    'Sleek skirted one-piece ceramic toilet with soft-close seat and dual-flush actuator.',
    'TOILET',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🚽',
    `${BASE_ITEM_URL}/toilet/thumbnail.webp`,
    `${BASE_ITEM_URL}/toilet/model.glb`,
    '#64748b',
    0.42,
    ['toilet', 'bathroom', 'sanitary', 'commode', 'plumbing']
  ),
  createRealAsset(
    'hh-shower-head',
    'Rainfall Shower Head Fixture',
    'Household',
    'Architectural ceiling-mounted stainless steel luxury rainfall shower head.',
    'RAIN SHOWER',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🚿',
    `${BASE_ITEM_URL}/shower/thumbnail.webp`,
    `${BASE_ITEM_URL}/shower/model.glb`,
    '#3b82f6',
    0.35,
    ['shower', 'bathroom', 'rainfall', 'plumbing', 'water']
  ),
  createRealAsset(
    'hh-towel-rail',
    'Heated Towel Ladder Warmer',
    'Household',
    'Multi-bar polished chrome electric heated towel rail rack for spa bathrooms.',
    'TOWEL RAIL',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🧖',
    `${BASE_ITEM_URL}/drying-rack/thumbnail.webp`,
    `${BASE_ITEM_URL}/drying-rack/model.glb`,
    '#71717a',
    0.40,
    ['towel rail', 'bathroom', 'heater', 'rack', 'towel']
  ),
  createRealAsset(
    'hh-washing-machine',
    'Front-Load Smart Washer',
    'Household',
    'High-efficiency front-loading automatic steam washing machine with digital dial.',
    'SMART WASHER',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🧺',
    `${BASE_ITEM_URL}/washing-machine/thumbnail.webp`,
    `${BASE_ITEM_URL}/washing-machine/model.glb`,
    '#6366f1',
    0.60,
    ['washing machine', 'laundry', 'washer', 'appliance', 'cleaning']
  ),
  createRealAsset(
    'hh-dryer',
    'Heat Pump Laundry Dryer',
    'Household',
    'Energy-efficient sensor-controlled condenser heat pump clothes dryer.',
    'DRYER',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '♨️',
    `${BASE_ITEM_URL}/washing-machine/thumbnail.webp`,
    `${BASE_ITEM_URL}/washing-machine/model.glb`,
    '#4f46e5',
    0.60,
    ['dryer', 'laundry', 'appliance', 'clothes', 'heat pump']
  ),
  createRealAsset(
    'hh-refrigerator',
    'French Door Smart Refrigerator',
    'Household',
    'Stainless steel counter-depth 4-door French refrigerator with external water dispenser.',
    'SMART FRIDGE',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '🧊',
    `${BASE_ITEM_URL}/fridge/thumbnail.webp`,
    `${BASE_ITEM_URL}/fridge/model.glb`,
    '#0ea5e9',
    0.90,
    ['refrigerator', 'fridge', 'kitchen', 'appliance', 'cooling']
  ),
  createRealAsset(
    'hh-refrigerator-large',
    'Side-by-Side Chef Fridge',
    'Household',
    'Extra-capacity commercial style side-by-side kitchen freezer refrigerator.',
    'CHEF FRIDGE',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '❄️',
    `${BASE_ITEM_URL}/kitchen-fridge/thumbnail.webp`,
    `${BASE_ITEM_URL}/kitchen-fridge/model.glb`,
    '#2563eb',
    0.95,
    ['refrigerator', 'large fridge', 'kitchen', 'freezer', 'storage']
  ),
  createRealAsset(
    'hh-gas-cooker',
    '5-Burner Pro Gas Range & Oven',
    'Household',
    'Professional stainless steel 5-burner gas cooktop with convection oven.',
    'GAS RANGE',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '🔥',
    `${BASE_ITEM_URL}/stove/thumbnail.webp`,
    `${BASE_ITEM_URL}/stove/model.glb`,
    '#ea580c',
    0.75,
    ['cooker', 'gas', 'stove', 'oven', 'kitchen', 'appliance']
  ),
  createRealAsset(
    'hh-stove',
    'Ceramic Induction Cooktop',
    'Household',
    'Flush black ceramic glass induction cooktop with touch sliders and boost zones.',
    'INDUCTION STOVE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🍳',
    `${BASE_ITEM_URL}/stove/thumbnail.webp`,
    `${BASE_ITEM_URL}/stove/model.glb`,
    '#d97706',
    0.50,
    ['stove', 'cooktop', 'induction', 'kitchen', 'cooking']
  ),
  createRealAsset(
    'hh-hood',
    'Island Range Extractor Hood',
    'Household',
    'Suspended stainless steel glass perimeter canopy kitchen ventilation extractor hood.',
    'RANGE HOOD',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '💨',
    `${BASE_ITEM_URL}/hood/thumbnail.webp`,
    `${BASE_ITEM_URL}/hood/model.glb`,
    '#52525b',
    0.60,
    ['hood', 'extractor', 'ventilation', 'kitchen', 'range']
  ),
  createRealAsset(
    'hh-microwave',
    'Countertop Convection Microwave',
    'Household',
    'Smart digital sensor microwave oven with mirrored glass door and rotary selector.',
    'MICROWAVE',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '📻',
    `${BASE_ITEM_URL}/microwave/thumbnail.webp`,
    `${BASE_ITEM_URL}/microwave/model.glb`,
    '#334155',
    0.40,
    ['microwave', 'kitchen', 'appliance', 'cooking', 'heating']
  ),
  createRealAsset(
    'hh-air-conditioner',
    'Inverter Split Air Conditioner',
    'Household',
    'Wall-mounted ultra-quiet inverter air conditioning indoor blower unit.',
    'AIR CONDITIONER',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '❄️',
    `${BASE_ITEM_URL}/air-conditioner/thumbnail.webp`,
    `${BASE_ITEM_URL}/air-conditioner/model.glb`,
    '#06b6d4',
    0.55,
    ['ac', 'air conditioner', 'climate', 'cooling', 'hvac']
  ),
  createRealAsset(
    'hh-water-heater',
    'Tankless Smart Water Heater',
    'Household',
    'On-demand wall-hung digital tankless gas hot water heater unit.',
    'WATER HEATER',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '♨️',
    `${BASE_ITEM_URL}/ac-block/thumbnail.webp`,
    `${BASE_ITEM_URL}/ac-block/model.glb`,
    '#059669',
    0.45,
    ['water heater', 'boiler', 'plumbing', 'heating', 'utility']
  ),
  createRealAsset(
    'hh-radiator',
    'Architectural Column Radiator',
    'Household',
    'Cast iron multi-column hydronic central heating room radiator.',
    'ROOM RADIATOR',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🪟',
    `${BASE_ITEM_URL}/air-conditioner/thumbnail.webp`,
    `${BASE_ITEM_URL}/air-conditioner/model.glb`,
    '#475569',
    0.50,
    ['radiator', 'heating', 'hvac', 'room', 'hydronic']
  ),
  createRealAsset(
    'hh-mirror-oval',
    'LED Backlit Oval Bathroom Mirror',
    'Household',
    'Frameless illuminated oval wall mirror with warm ambient perimeter backlighting.',
    'OVAL MIRROR',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🪞',
    `${BASE_ITEM_URL}/round-mirror/thumbnail.webp`,
    `${BASE_ITEM_URL}/round-mirror/model.glb`,
    '#ca8a04',
    0.48,
    ['mirror', 'bathroom', 'led', 'oval', 'decor']
  ),
  createRealAsset(
    'hh-mirror-rectangular',
    'Black Metal Framed Mirror',
    'Household',
    'Full-height architectural industrial black metal frame vanity mirror.',
    'VANITY MIRROR',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🪞',
    `${BASE_ITEM_URL}/rectangular-mirror/thumbnail.webp`,
    `${BASE_ITEM_URL}/rectangular-mirror/model.glb`,
    '#27272a',
    0.60,
    ['mirror', 'rectangular', 'vanity', 'decor', 'wall']
  ),
  createRealAsset(
    'hh-trashcan',
    'Hands-Free Motion Sensor Trash Can',
    'Household',
    'Brushed fingerprint-proof stainless steel rectangular kitchen trash can with soft-close lid.',
    'TRASH CAN',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🗑️',
    `${BASE_ITEM_URL}/trash-bin/thumbnail.webp`,
    `${BASE_ITEM_URL}/trash-bin/model.glb`,
    '#52525b',
    0.35,
    ['trash can', 'bin', 'waste', 'kitchen', 'garbage']
  ),
  createRealAsset(
    'hh-dustbin',
    'Recycling Sorting Pedal Bin',
    'Household',
    'Dual-compartment step pedal waste and recycling separation station.',
    'RECYCLING BIN',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '♻️',
    `${BASE_ITEM_URL}/trash-bin/thumbnail.webp`,
    `${BASE_ITEM_URL}/trash-bin/model.glb`,
    '#10b981',
    0.32,
    ['dustbin', 'bin', 'recycling', 'waste', 'eco']
  ),
  createRealAsset(
    'hh-avocado',
    'Organic Hass Avocado',
    'Household',
    'Photorealistic textured halved ripe organic Hass avocado with visible seed pit.',
    'HASS AVOCADO',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🥑',
    `${BASE_KHRONOS_URL}/Avocado/glTF-Binary/Avocado.glb`,
    `${BASE_KHRONOS_URL}/Avocado/glTF-Binary/Avocado.glb`,
    '#059669',
    0.15,
    ['avocado', 'food', 'fruit', 'kitchen', 'nutrition']
  ),
  createRealAsset(
    'hh-khronos-duck',
    'Classic Yellow Rubber Duck',
    'Household',
    'Glossy yellow bath rubber duck toy with orange beak.',
    'RUBBER DUCK',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🐤',
    `${BASE_KHRONOS_URL}/Duck/glTF-Binary/Duck.glb`,
    `${BASE_KHRONOS_URL}/Duck/glTF-Binary/Duck.glb`,
    '#eab308',
    0.18,
    ['duck', 'toy', 'bath', 'rubber duck', 'yellow']
  ),
  createRealAsset(
    'hh-khronos-shoe',
    'Designer E-Commerce Running Sneaker',
    'Household',
    'High-top athletic lifestyle sneaker with textured knit fabric and cushioned sole.',
    'LIFESTYLE SHOE',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '👟',
    `${BASE_KHRONOS_URL}/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb`,
    `${BASE_KHRONOS_URL}/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb`,
    '#e11d48',
    0.30,
    ['shoe', 'sneaker', 'fashion', 'footwear', 'retail', 'e-commerce']
  ),
  createRealAsset(
    'hh-corset',
    'Vintage Silk Corset Garment',
    'Household',
    'Textured historical silk brocade corset with lace details.',
    'SILK CORSET',
    'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-500/30',
    '👗',
    `${BASE_KHRONOS_URL}/Corset/glTF-Binary/Corset.glb`,
    `${BASE_KHRONOS_URL}/Corset/glTF-Binary/Corset.glb`,
    '#c026d3',
    0.35,
    ['corset', 'fashion', 'garment', 'apparel', 'textile']
  ),
  createRealAsset(
    'hh-coffee-machine-pro',
    'Espresso Barista Machine',
    'Household',
    'Italian manual portafilter espresso coffee machine with steam wand and pressure gauge.',
    'ESPRESSO BAR',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '☕',
    `${BASE_ITEM_URL}/computer/thumbnail.webp`,
    `${BASE_ITEM_URL}/computer/model.glb`,
    '#78350f',
    0.35,
    ['coffee', 'espresso', 'barista', 'kitchen', 'cafe', 'appliance']
  ),
  createRealAsset(
    'hh-blender-pro',
    'High-Speed Countertop Blender',
    'Household',
    'Commercial grade vortex smoothie blender with tritan pitcher and pulse dial.',
    'VORTEX BLENDER',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🍹',
    `${BASE_ITEM_URL}/trash-bin/thumbnail.webp`,
    `${BASE_ITEM_URL}/trash-bin/model.glb`,
    '#ef4444',
    0.30,
    ['blender', 'smoothie', 'kitchen', 'appliance', 'food']
  ),
  createRealAsset(
    'hh-toaster-retro',
    'Artisan 4-Slice Toaster',
    'Household',
    'Vintage curved chrome and mint green 4-slice bagel toaster with dual browning levers.',
    'RETRO TOASTER',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🍞',
    `${BASE_ITEM_URL}/microwave/thumbnail.webp`,
    `${BASE_ITEM_URL}/microwave/model.glb`,
    '#059669',
    0.26,
    ['toaster', 'breakfast', 'bread', 'kitchen', 'retro']
  ),
  createRealAsset(
    'hh-electric-kettle',
    'Gooseneck Pour-Over Kettle',
    'Household',
    'Matte black precision temperature control pour-over gooseneck electric kettle.',
    'POUR-OVER KETTLE',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🫖',
    `${BASE_ITEM_URL}/ac-block/thumbnail.webp`,
    `${BASE_ITEM_URL}/ac-block/model.glb`,
    '#3f3f46',
    0.25,
    ['kettle', 'tea', 'coffee', 'kitchen', 'water']
  ),
  createRealAsset(
    'hh-vacuum-robot',
    'AI LiDAR Robot Vacuum & Mop',
    'Household',
    'Autonomous circular robotic floor vacuum with auto-empty docking base.',
    'ROBOT VACUUM',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🤖',
    `${BASE_ITEM_URL}/smoke-detector/thumbnail.webp`,
    `${BASE_ITEM_URL}/smoke-detector/model.glb`,
    '#2563eb',
    0.35,
    ['vacuum', 'robot', 'cleaning', 'smart home', 'automation']
  ),
  createRealAsset(
    'hh-kitchen-island',
    'Waterfall Marble Kitchen Island',
    'Household',
    'Grand waterfall Calacatta marble countertop kitchen island with under-cabinet storage.',
    'KITCHEN ISLAND',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🍳',
    `${BASE_ITEM_URL}/bathroom-sink/thumbnail.webp`,
    `${BASE_ITEM_URL}/bathroom-sink/model.glb`,
    '#334155',
    0.95,
    ['island', 'kitchen', 'marble', 'counter', 'cabinet']
  ),
  createRealAsset(
    'hh-wine-cooler',
    'Dual-Zone Built-in Wine Cellar',
    'Household',
    'Under-counter dual-zone glass door wine refrigerator with wooden pull-out racks.',
    'WINE COOLER',
    'bg-purple-500/20 text-purple-300 border-purple-500/30',
    '🍷',
    `${BASE_ITEM_URL}/fridge/thumbnail.webp`,
    `${BASE_ITEM_URL}/fridge/model.glb`,
    '#7e22ce',
    0.60,
    ['wine', 'cooler', 'fridge', 'cellar', 'beverage', 'kitchen']
  ),
  createRealAsset(
    'hh-ironing-station',
    'Steam Ironing Care Station',
    'Household',
    'Ergonomic padded folding ironing board with integrated high-pressure steam iron.',
    'IRONING BOARD',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '👔',
    `${BASE_ITEM_URL}/drying-rack/thumbnail.webp`,
    `${BASE_ITEM_URL}/drying-rack/model.glb`,
    '#0891b2',
    0.55,
    ['iron', 'laundry', 'ironing board', 'clothes', 'care']
  ),
  createRealAsset(
    'hh-air-purifier',
    'HEPA UV Smart Air Purifier',
    'Household',
    'Cylindrical 360-degree True HEPA carbon air filtration purifier tower with air quality light ring.',
    'AIR PURIFIER',
    'bg-teal-500/20 text-teal-300 border-teal-500/30',
    '🍃',
    `${BASE_ITEM_URL}/trash-bin/thumbnail.webp`,
    `${BASE_ITEM_URL}/trash-bin/model.glb`,
    '#0d9488',
    0.40,
    ['air purifier', 'hepa', 'clean air', 'smart home', 'health']
  ),
  createRealAsset(
    'hh-cutlery-set',
    'Stainless Steel Cutlery Set',
    'Household',
    'Mirror-polished 24-piece cutlery set with chef knife, forks, and dessert spoons.',
    'CUTLERY SET',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🍴',
    `${BASE_ITEM_URL}/wall-sink/thumbnail.webp`,
    `${BASE_ITEM_URL}/wall-sink/model.glb`,
    '#64748b',
    0.28,
    ['cutlery', 'silverware', 'dining', 'kitchen', 'utensils']
  )
];
