import { Real3DAsset, createRealAsset, BASE_ITEM_URL, BASE_KHRONOS_URL, BASE_MODELVIEWER_URL } from './types';

export const MACHINES_ASSETS: Real3DAsset[] = [
  createRealAsset(
    'mach-fire-extinguisher',
    'Dry Chemical Fire Extinguisher',
    'Machines & Industrial',
    'Pressurized ABC multipurpose dry chemical fire extinguisher cylinder with pressure gauge.',
    'EXTINGUISHER',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🧯',
    `${BASE_ITEM_URL}/fire-extinguisher/thumbnail.webp`,
    `${BASE_ITEM_URL}/fire-extinguisher/model.glb`,
    '#ef4444',
    0.35,
    ['fire extinguisher', 'safety', 'emergency', 'industrial', 'hazard']
  ),
  createRealAsset(
    'mach-hydrant',
    'Municipal Fire Hydrant Station',
    'Machines & Industrial',
    'Cast iron municipal high-pressure water supply hydrant valve.',
    'FIRE HYDRANT',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🚒',
    `${BASE_ITEM_URL}/hydrant/thumbnail.webp`,
    `${BASE_ITEM_URL}/hydrant/model.glb`,
    '#eab308',
    0.45,
    ['hydrant', 'water', 'municipal', 'safety', 'fire']
  ),
  createRealAsset(
    'mach-sprinkler',
    'Ceiling Fire Suppression Sprinkler',
    'Machines & Industrial',
    'Pendant thermal glass bulb fire suppression water sprinkler head.',
    'SPRINKLER',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '💧',
    `${BASE_ITEM_URL}/sprinkler/thumbnail.webp`,
    `${BASE_ITEM_URL}/sprinkler/model.glb`,
    '#d97706',
    0.15,
    ['sprinkler', 'fire', 'safety', 'ceiling', 'water']
  ),
  createRealAsset(
    'mach-treadmill',
    'Commercial Motorized Treadmill',
    'Machines & Industrial',
    'Heavy-duty electric running treadmill with interactive telemetry console.',
    'TREADMILL',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🏃',
    `${BASE_ITEM_URL}/threadmill/thumbnail.webp`,
    `${BASE_ITEM_URL}/threadmill/model.glb`,
    '#2563eb',
    0.75,
    ['treadmill', 'fitness', 'exercise', 'machine', 'gym', 'health']
  ),
  createRealAsset(
    'mach-exercise-bike',
    'Magnetic Resistance Exercise Bike',
    'Machines & Industrial',
    'Indoor studio stationary fitness cycle with flywheel and tablet mount.',
    'FITNESS BIKE',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🚴',
    `${BASE_ITEM_URL}/exercise-bike/thumbnail.webp`,
    `${BASE_ITEM_URL}/exercise-bike/model.glb`,
    '#4f46e5',
    0.65,
    ['exercise bike', 'cycle', 'fitness', 'gym', 'cardio']
  ),
  createRealAsset(
    'mach-barbell-stand',
    'Olympic Barbell Weight Rack',
    'Machines & Industrial',
    'Heavy steel squat rack station loaded with Olympic cast iron weight plates.',
    'SQUAT RACK',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🏋️',
    `${BASE_ITEM_URL}/barbell-stand/thumbnail.webp`,
    `${BASE_ITEM_URL}/barbell-stand/model.glb`,
    '#334155',
    0.80,
    ['barbell', 'weights', 'gym', 'fitness', 'rack']
  ),
  createRealAsset(
    'mach-barbell',
    'Olympic Free Barbell Set',
    'Machines & Industrial',
    'Solid steel Olympic barbell with knurled grip and competition bumpers.',
    'BARBELL',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🏋️',
    `${BASE_ITEM_URL}/barbell/thumbnail.webp`,
    `${BASE_ITEM_URL}/barbell/model.glb`,
    '#27272a',
    0.50,
    ['barbell', 'weights', 'olympic', 'lifting', 'gym']
  ),
  createRealAsset(
    'mach-water-bottle',
    'Insulated Titanium Vacuum Bottle',
    'Machines & Industrial',
    'PBR metallic double-wall vacuum insulated thermal bottle with sports cap.',
    'WATER BOTTLE',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🍶',
    `${BASE_KHRONOS_URL}/WaterBottle/glTF-Binary/WaterBottle.glb`,
    `${BASE_KHRONOS_URL}/WaterBottle/glTF-Binary/WaterBottle.glb`,
    '#0891b2',
    0.20,
    ['bottle', 'water', 'vacuum', 'metal', 'hydration']
  ),
  createRealAsset(
    'mach-pool-table',
    'Championship Billiard Table',
    'Machines & Industrial',
    'Slate-bed regulation 8-foot billiard pool table with felt and ball return.',
    'POOL TABLE',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🎱',
    `${BASE_ITEM_URL}/pool-table/thumbnail.webp`,
    `${BASE_ITEM_URL}/pool-table/model.glb`,
    '#047857',
    0.90,
    ['pool table', 'billiards', 'game', 'leisure', 'sports']
  ),
  createRealAsset(
    'mach-basket-hoop',
    'Spring-Action Basketball Hoop',
    'Machines & Industrial',
    'Wall-mounted acrylic basketball backboard with breakaway steel rim.',
    'BASKETBALL HOOP',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🏀',
    `${BASE_ITEM_URL}/basket-hoop/thumbnail.webp`,
    `${BASE_ITEM_URL}/basket-hoop/model.glb`,
    '#d97706',
    0.60,
    ['basketball', 'hoop', 'sports', 'game', 'court']
  ),
  createRealAsset(
    'mach-ball',
    'Competition Match Ball',
    'Machines & Industrial',
    'Textured leather regulation multi-sport athletic game ball.',
    'MATCH BALL',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '⚽',
    `${BASE_ITEM_URL}/ball/thumbnail.webp`,
    `${BASE_ITEM_URL}/ball/model.glb`,
    '#ea580c',
    0.22,
    ['ball', 'sports', 'game', 'soccer', 'athletic']
  ),
  createRealAsset(
    'mach-suspended-fireplace',
    'Suspended Orbital Fireplace',
    'Machines & Industrial',
    'Ceiling-suspended architectural 360-degree rotating steel hearth fireplace.',
    'FIREPLACE',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '🔥',
    `${BASE_ITEM_URL}/suspended-fireplace/thumbnail.webp`,
    `${BASE_ITEM_URL}/suspended-fireplace/model.glb`,
    '#c2410c',
    0.65,
    ['fireplace', 'hearth', 'heating', 'fire', 'architecture']
  ),
  createRealAsset(
    'mach-easel',
    'Artist Studio Display Easel',
    'Machines & Industrial',
    'Solid beechwood A-frame artist studio tripod easel with crank mast.',
    'ART EASEL',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🎨',
    `${BASE_ITEM_URL}/easel/thumbnail.webp`,
    `${BASE_ITEM_URL}/easel/model.glb`,
    '#b45309',
    0.60,
    ['easel', 'art', 'studio', 'canvas', 'painting']
  ),
  createRealAsset(
    'mach-reciprocating-saw',
    'Industrial Reciprocating Saw',
    'Machines & Industrial',
    'Cordless heavy-duty brushless reciprocating demolition power saw.',
    'POWER SAW',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🪚',
    `${BASE_KHRONOS_URL}/ReciprocatingSaw/glTF-Binary/ReciprocatingSaw.glb`,
    `${BASE_KHRONOS_URL}/ReciprocatingSaw/glTF-Binary/ReciprocatingSaw.glb`,
    '#d97706',
    0.35,
    ['saw', 'tool', 'industrial', 'power tool', 'construction']
  ),
  createRealAsset(
    'mach-gearbox-assembly',
    'Planetary Reduction Gearbox Assembly',
    'Machines & Industrial',
    'Engineered mechanical reduction gearbox with visible spur gears and bearings.',
    'GEARBOX',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '⚙️',
    `${BASE_KHRONOS_URL}/GearboxAssy/glTF-Binary/GearboxAssy.glb`,
    `${BASE_KHRONOS_URL}/GearboxAssy/glTF-Binary/GearboxAssy.glb`,
    '#475569',
    0.40,
    ['gearbox', 'gears', 'machine', 'engineering', 'mechanics']
  ),
  createRealAsset(
    'mach-robot-expressive',
    'Autonomous Articulated Android',
    'Machines & Industrial',
    'Multi-axis programmable industrial robotic android with dynamic expressions.',
    'ROBOT ANDROID',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🤖',
    'https://threejs.org/examples/models/gltf/RobotExpressive/RobotExpressive.glb',
    'https://threejs.org/examples/models/gltf/RobotExpressive/RobotExpressive.glb',
    '#6366f1',
    0.60,
    ['robot', 'android', 'automation', 'ai', 'cyber']
  ),
  createRealAsset(
    'mach-astronaut',
    'NASA Extravehicular Mobility Unit',
    'Machines & Industrial',
    'High-fidelity Apollo astronaut EVA space exploration suit.',
    'EVA ASTRONAUT',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '👨‍🚀',
    `${BASE_MODELVIEWER_URL}/Astronaut.glb`,
    `${BASE_MODELVIEWER_URL}/Astronaut.glb`,
    '#0284c7',
    0.70,
    ['astronaut', 'space', 'nasa', 'suit', 'science']
  ),
  createRealAsset(
    'mach-conveyor-system',
    'Automated Roller Conveyor',
    'Machines & Industrial',
    'Motorized industrial roller conveyor assembly line for factory distribution.',
    'CONVEYOR',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🏭',
    `${BASE_ITEM_URL}/barbell-stand/thumbnail.webp`,
    `${BASE_ITEM_URL}/barbell-stand/model.glb`,
    '#334155',
    0.85,
    ['conveyor', 'logistics', 'warehouse', 'factory', 'industrial']
  ),
  createRealAsset(
    'mach-cnc-lathe',
    'Precision CNC Machining Center',
    'Machines & Industrial',
    'Automated multi-axis CNC metal lathe milling station with enclosure.',
    'CNC LATHE',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🎛️',
    `${BASE_ITEM_URL}/electric-panel/thumbnail.webp`,
    `${BASE_ITEM_URL}/electric-panel/model.glb`,
    '#52525b',
    0.80,
    ['cnc', 'lathe', 'machining', 'manufacturing', 'tools']
  ),
  createRealAsset(
    'mach-air-compressor',
    'Rotary Screw Air Compressor',
    'Machines & Industrial',
    'Stationary twin-tank pressurized pneumatic workshop air compressor.',
    'COMPRESSOR',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '💨',
    `${BASE_ITEM_URL}/ac-block/thumbnail.webp`,
    `${BASE_ITEM_URL}/ac-block/model.glb`,
    '#2563eb',
    0.60,
    ['compressor', 'pneumatic', 'tools', 'workshop', 'industrial']
  ),
  createRealAsset(
    'mach-diesel-generator',
    'Soundproof Diesel Backup Generator',
    'Machines & Industrial',
    'Heavy-duty acoustic canopy emergency prime diesel electric power generator.',
    'GENERATOR',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '⚡',
    `${BASE_ITEM_URL}/fridge/thumbnail.webp`,
    `${BASE_ITEM_URL}/fridge/model.glb`,
    '#b45309',
    0.75,
    ['generator', 'diesel', 'power', 'emergency', 'electricity']
  ),
  createRealAsset(
    'mach-hydraulic-press',
    'Hydraulic Metal Stamping Press',
    'Machines & Industrial',
    '50-ton heavy industrial H-frame hydraulic forging and pressing machine.',
    'HYDRAULIC PRESS',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🏗️',
    `${BASE_ITEM_URL}/barbell-stand/thumbnail.webp`,
    `${BASE_ITEM_URL}/barbell-stand/model.glb`,
    '#dc2626',
    0.80,
    ['press', 'hydraulic', 'metalwork', 'industrial', 'manufacturing']
  ),
  createRealAsset(
    'mach-welding-station',
    'TIG/MIG Multi-Process Welder Cart',
    'Machines & Industrial',
    'Inverter welding power source cart with shielding gas argon cylinder and torch.',
    'WELDER CART',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '👨‍🏭',
    `${BASE_ITEM_URL}/trash-bin/thumbnail.webp`,
    `${BASE_ITEM_URL}/trash-bin/model.glb`,
    '#ea580c',
    0.55,
    ['welder', 'welding', 'mig', 'tig', 'metalwork', 'workshop']
  ),
  createRealAsset(
    'mach-solar-inverter',
    'Commercial Solar PV Inverter',
    'Machines & Industrial',
    'High-efficiency grid-tied solar string inverter with cooling fin enclosure.',
    'SOLAR INVERTER',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '☀️',
    `${BASE_ITEM_URL}/electric-panel/thumbnail.webp`,
    `${BASE_ITEM_URL}/electric-panel/model.glb`,
    '#059669',
    0.50,
    ['solar', 'inverter', 'green energy', 'renewable', 'clean tech']
  ),
  createRealAsset(
    'mach-wind-turbine-scale',
    'Micro Wind Turbine Generator',
    'Machines & Industrial',
    'Aerodynamic horizontal-axis carbon composite wind power generator turbine.',
    'WIND TURBINE',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🌬️',
    `${BASE_ITEM_URL}/ceiling-fan/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-fan/model.glb`,
    '#06b6d4',
    0.85,
    ['wind turbine', 'energy', 'renewable', 'clean tech', 'generator']
  ),
  createRealAsset(
    'mach-3d-printer-pro',
    'Industrial CoreXY 3D Printer',
    'Machines & Industrial',
    'Fully enclosed heated chamber high-speed dual-extrusion additive manufacturing 3D printer.',
    '3D PRINTER',
    'bg-purple-500/20 text-purple-300 border-purple-500/30',
    '🖨️',
    `${BASE_ITEM_URL}/microwave/thumbnail.webp`,
    `${BASE_ITEM_URL}/microwave/model.glb`,
    '#9333ea',
    0.45,
    ['3d printer', 'additive', 'rapid prototyping', 'manufacturing', 'maker']
  ),
  createRealAsset(
    'mach-laser-cutter',
    'Desktop Fiber Laser Engraver',
    'Machines & Industrial',
    'High-precision optical galvo laser engraving and cutting workstation.',
    'LASER ENGRAVER',
    'bg-violet-500/20 text-violet-300 border-violet-500/30',
    '⚡',
    `${BASE_ITEM_URL}/computer/thumbnail.webp`,
    `${BASE_ITEM_URL}/computer/model.glb`,
    '#7c3aed',
    0.40,
    ['laser', 'engraver', 'cutting', 'prototyping', 'manufacturing']
  ),
  createRealAsset(
    'mach-drone-dock',
    'Automated Drone Charging Dock',
    'Machines & Industrial',
    'Weatherproof outdoor automated roof-opening drone landing and wireless recharge bay.',
    'DRONE DOCK',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '🛰️',
    `${BASE_ITEM_URL}/coffee-table/thumbnail.webp`,
    `${BASE_ITEM_URL}/coffee-table/model.glb`,
    '#0284c7',
    0.65,
    ['drone', 'uav', 'dock', 'charging', 'robotics', 'autonomous']
  ),
  createRealAsset(
    'mach-water-filtration',
    'Reverse Osmosis Water Purification System',
    'Machines & Industrial',
    'Multi-stage commercial membrane reverse osmosis water demineralization filter rack.',
    'RO FILTER',
    'bg-teal-500/20 text-teal-300 border-teal-500/30',
    '💧',
    `${BASE_ITEM_URL}/ac-block/thumbnail.webp`,
    `${BASE_ITEM_URL}/ac-block/model.glb`,
    '#0d9488',
    0.50,
    ['water', 'filtration', 'reverse osmosis', 'purifier', 'industrial']
  ),
  createRealAsset(
    'mach-autoclave',
    'Medical Sterilization Autoclave',
    'Machines & Industrial',
    'Digital vacuum pressurized steam laboratory autoclave chamber.',
    'AUTOCLAVE',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🧪',
    `${BASE_ITEM_URL}/microwave/thumbnail.webp`,
    `${BASE_ITEM_URL}/microwave/model.glb`,
    '#475569',
    0.42,
    ['autoclave', 'medical', 'sterilizer', 'lab', 'science']
  ),
  createRealAsset(
    'mach-centrifuge',
    'Refrigerated High-Speed Centrifuge',
    'Machines & Industrial',
    'Biomedical laboratory micro-centrifuge with brushless induction rotor.',
    'CENTRIFUGE',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🧬',
    `${BASE_ITEM_URL}/washing-machine/thumbnail.webp`,
    `${BASE_ITEM_URL}/washing-machine/model.glb`,
    '#1d4ed8',
    0.40,
    ['centrifuge', 'lab', 'biomedical', 'science', 'chemistry']
  ),
  createRealAsset(
    'mach-spectrometer',
    'Optical Emission Spectrometer',
    'Machines & Industrial',
    'High-resolution analytical grating spectrometer for material elemental assay.',
    'SPECTROMETER',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🔬',
    `${BASE_ITEM_URL}/computer/thumbnail.webp`,
    `${BASE_ITEM_URL}/computer/model.glb`,
    '#4338ca',
    0.45,
    ['spectrometer', 'optics', 'analytical', 'science', 'laser']
  ),
  createRealAsset(
    'mach-oscilloscope',
    '4-Channel Digital Storage Oscilloscope',
    'Machines & Industrial',
    '1GHz real-time sampling mixed-signal electronic test bench oscilloscope.',
    'OSCILLOSCOPE',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '📊',
    `${BASE_ITEM_URL}/flat-screen-tv/thumbnail.webp`,
    `${BASE_ITEM_URL}/flat-screen-tv/model.glb`,
    '#0891b2',
    0.35,
    ['oscilloscope', 'electronics', 'test', 'waveform', 'engineering']
  ),
  createRealAsset(
    'mach-power-supply',
    'Programmable DC Benchtop Power Supply',
    'Machines & Industrial',
    'Triple-output precision linear regulated benchtop DC power laboratory supply.',
    'DC BENCH SUPPLY',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🔋',
    `${BASE_ITEM_URL}/stereo-speaker/thumbnail.webp`,
    `${BASE_ITEM_URL}/stereo-speaker/model.glb`,
    '#d97706',
    0.32,
    ['power supply', 'benchtop', 'electronics', 'voltage', 'lab']
  ),
  createRealAsset(
    'mach-battery-storage',
    'Commercial LiFePO4 Energy Storage Cabinet',
    'Machines & Industrial',
    'Rack-mounted high-density lithium iron phosphate utility energy storage rack.',
    'ENERGY STORAGE',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🔋',
    `${BASE_ITEM_URL}/closet/thumbnail.webp`,
    `${BASE_ITEM_URL}/closet/model.glb`,
    '#10b981',
    0.85,
    ['battery', 'bess', 'storage', 'energy', 'grid', 'clean energy']
  )
];
