import { Real3DAsset, createRealAsset, BASE_ITEM_URL, BASE_KHRONOS_URL } from './types';

export const NATURE_ASSETS: Real3DAsset[] = [
  createRealAsset(
    'nat-potted-plant',
    'Fiddle Leaf Fig in Ceramic Pot',
    'Nature & Outdoor',
    'Lush broad-leaf indoor Ficus Lyrata potted plant in matte white ceramic cylinder pot.',
    'POTTED PLANT',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🪴',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#059669',
    0.45,
    ['plant', 'potted', 'indoor', 'greenery', 'decor', 'botanical']
  ),
  createRealAsset(
    'nat-potted-plant-tall',
    'Monstera Deliciosa Floor Plant',
    'Nature & Outdoor',
    'Large architectural Swiss Cheese Monstera plant with perforated fenestrated leaves.',
    'MONSTERA',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🌿',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#047857',
    0.55,
    ['plant', 'monstera', 'tropical', 'indoor', 'foliage']
  ),
  createRealAsset(
    'nat-bush',
    'Manicured Foliage Shrub',
    'Nature & Outdoor',
    'Dense rounded evergreen landscape shrub bush for garden borders.',
    'GARDEN SHRUB',
    'bg-green-500/20 text-green-300 border-green-500/30',
    '🌿',
    `${BASE_ITEM_URL}/bush/thumbnail.webp`,
    `${BASE_ITEM_URL}/bush/model.glb`,
    '#15803d',
    0.45,
    ['bush', 'shrub', 'garden', 'greenery', 'landscape']
  ),
  createRealAsset(
    'nat-hedge',
    'Boxwood Privacy Hedge Wall',
    'Nature & Outdoor',
    'Neatly trimmed rectangular living boxwood hedge boundary partition.',
    'HEDGE WALL',
    'bg-green-500/20 text-green-300 border-green-500/30',
    '🌳',
    `${BASE_ITEM_URL}/hedge/thumbnail.webp`,
    `${BASE_ITEM_URL}/hedge/model.glb`,
    '#166534',
    0.65,
    ['hedge', 'greenery', 'garden', 'wall', 'boundary']
  ),
  createRealAsset(
    'nat-patio-umbrella',
    'Cantilever Patio Sun Umbrella',
    'Nature & Outdoor',
    'Large octagonal cantilevered outdoor sunshade parasol umbrella with granite base.',
    'PATIO UMBRELLA',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '⛱️',
    `${BASE_ITEM_URL}/patio-umbrella/thumbnail.webp`,
    `${BASE_ITEM_URL}/patio-umbrella/model.glb`,
    '#d97706',
    0.80,
    ['umbrella', 'patio', 'sunshade', 'parasol', 'outdoor']
  ),
  createRealAsset(
    'nat-outdoor-playhouse',
    'Timber Backyard Playhouse',
    'Nature & Outdoor',
    'Modular timber backyard children’s playhouse cabin with pitched roof.',
    'PLAYHOUSE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🏡',
    `${BASE_ITEM_URL}/outdoor-playhouse/thumbnail.webp`,
    `${BASE_ITEM_URL}/outdoor-playhouse/model.glb`,
    '#b45309',
    0.88,
    ['playhouse', 'cabin', 'outdoor', 'timber', 'kids']
  ),
  createRealAsset(
    'nat-fence',
    'Horizontal Slat Perimeter Fence',
    'Nature & Outdoor',
    'Modern horizontal timber slat garden perimeter fence section.',
    'SLAT FENCE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🪵',
    `${BASE_ITEM_URL}/fence/thumbnail.webp`,
    `${BASE_ITEM_URL}/fence/model.glb`,
    '#92400e',
    0.60,
    ['fence', 'perimeter', 'wood', 'barrier', 'garden']
  ),
  createRealAsset(
    'nat-low-fence',
    'Decorative Low Boundary Fence',
    'Nature & Outdoor',
    'Architectural low-profile timber boundary fence for pathways and flowerbeds.',
    'LOW FENCE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🪵',
    `${BASE_ITEM_URL}/low-fence/thumbnail.webp`,
    `${BASE_ITEM_URL}/low-fence/model.glb`,
    '#78350f',
    0.40,
    ['fence', 'low fence', 'boundary', 'garden', 'path']
  ),
  createRealAsset(
    'nat-high-fence',
    'Full-Height Security Privacy Fence',
    'Nature & Outdoor',
    'Tall vertical privacy fence panel for residential security.',
    'HIGH FENCE',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🪵',
    `${BASE_ITEM_URL}/high-fence/thumbnail.webp`,
    `${BASE_ITEM_URL}/high-fence/model.glb`,
    '#3f3f46',
    0.75,
    ['fence', 'high fence', 'privacy', 'security', 'yard']
  ),
  createRealAsset(
    'nat-fox-animated',
    'Low-Poly Forest Fox',
    'Nature & Outdoor',
    'Animated woodland red fox character with idle and walking animations.',
    'ANIMATED FOX',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '🦊',
    `${BASE_KHRONOS_URL}/Fox/glTF-Binary/Fox.glb`,
    `${BASE_KHRONOS_URL}/Fox/glTF-Binary/Fox.glb`,
    '#ea580c',
    0.40,
    ['fox', 'animal', 'animated', 'wildlife', 'forest']
  ),
  createRealAsset(
    'nat-barramundi-fish',
    'Ocean Barramundi Trophy Fish',
    'Nature & Outdoor',
    'Realistic iridescent scaled ocean Barramundi marine trophy fish.',
    'BARRAMUNDI',
    'bg-teal-500/20 text-teal-300 border-teal-500/30',
    '🐟',
    `${BASE_KHRONOS_URL}/BarramundiFish/glTF-Binary/BarramundiFish.glb`,
    `${BASE_KHRONOS_URL}/BarramundiFish/glTF-Binary/BarramundiFish.glb`,
    '#0d9488',
    0.35,
    ['fish', 'marine', 'ocean', 'wildlife', 'nature']
  ),
  createRealAsset(
    'nat-horse-galloping',
    'Wild Stallion Horse',
    'Nature & Outdoor',
    'Muscular galloping wild stallion horse with fluid morph target animation.',
    'WILD HORSE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🐎',
    'https://threejs.org/examples/models/gltf/Horse.glb',
    'https://threejs.org/examples/models/gltf/Horse.glb',
    '#b45309',
    0.75,
    ['horse', 'stallion', 'animal', 'wildlife', 'animated']
  ),
  createRealAsset(
    'nat-flamingo',
    'Tropical Pink Flamingo',
    'Nature & Outdoor',
    'Exotic animated pink flamingo wading bird with flapping flight cycle.',
    'FLAMINGO',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '🦩',
    'https://threejs.org/examples/models/gltf/Flamingo.glb',
    'https://threejs.org/examples/models/gltf/Flamingo.glb',
    '#f43f5e',
    0.60,
    ['flamingo', 'bird', 'tropical', 'animal', 'animated']
  ),
  createRealAsset(
    'nat-parrot',
    'Exotic Rainforest Parrot',
    'Nature & Outdoor',
    'Vibrant multicolored tropical macaw parrot with animated wing glide.',
    'TROPICAL PARROT',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🦜',
    'https://threejs.org/examples/models/gltf/Parrot.glb',
    'https://threejs.org/examples/models/gltf/Parrot.glb',
    '#10b981',
    0.45,
    ['parrot', 'bird', 'tropical', 'rainforest', 'animated']
  ),
  createRealAsset(
    'nat-snake-plant',
    'Sansevieria Snake Plant',
    'Nature & Outdoor',
    'Upright yellow-bordered sword-shaped Sansevieria snake plant in terracotta planter.',
    'SNAKE PLANT',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🪴',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#059669',
    0.42,
    ['plant', 'sansevieria', 'succulent', 'indoor', 'greenery']
  ),
  createRealAsset(
    'nat-succulent-bowl',
    'Assorted Echeveria Succulent Bowl',
    'Nature & Outdoor',
    'Low shallow concrete bowl filled with rosette echeveria and sedum succulents.',
    'SUCCULENTS',
    'bg-teal-500/20 text-teal-300 border-teal-500/30',
    '🌵',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#0d9488',
    0.30,
    ['succulent', 'cactus', 'bowl', 'desk plant', 'botanical']
  ),
  createRealAsset(
    'nat-bonsai-tree',
    'Japanese Juniper Bonsai Tree',
    'Nature & Outdoor',
    'Traditional aged Japanese cascade juniper bonsai in glazed ceramic shallow tray.',
    'JUNIPER BONSAI',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🎋',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#047857',
    0.38,
    ['bonsai', 'zen', 'tree', 'japanese', 'botanical']
  ),
  createRealAsset(
    'nat-palm-tree-pot',
    'Areca Parlor Palm Tree',
    'Nature & Outdoor',
    'Feathery arching fronds of an Areca indoor palm in a woven seagrass basket.',
    'ARECA PALM',
    'bg-green-500/20 text-green-300 border-green-500/30',
    '🌴',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#16a34a',
    0.65,
    ['palm', 'areca', 'tropical', 'indoor', 'basket']
  ),
  createRealAsset(
    'nat-olive-tree-pot',
    'Mediterranean Potted Olive Tree',
    'Nature & Outdoor',
    'Slender Mediterranean olive tree with silvery-green foliage in an aged clay amphora.',
    'OLIVE TREE',
    'bg-lime-500/20 text-lime-300 border-lime-500/30',
    '🫒',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#65a30d',
    0.60,
    ['olive tree', 'mediterranean', 'botanical', 'rustic', 'pot']
  ),
  createRealAsset(
    'nat-hanging-ivy',
    'Cascading English Ivy Planter',
    'Nature & Outdoor',
    'Trailing variegated English ivy cascading from a suspended macrame rope hanger.',
    'TRAILING IVY',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🌿',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#059669',
    0.40,
    ['ivy', 'hanging plant', 'macrame', 'greenery', 'foliage']
  ),
  createRealAsset(
    'nat-bird-of-paradise',
    'Strelitzia Bird of Paradise',
    'Nature & Outdoor',
    'Regal upright tropical Strelitzia plant with dramatic paddle leaves.',
    'BIRD OF PARADISE',
    'bg-teal-500/20 text-teal-300 border-teal-500/30',
    '🌺',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#0f766e',
    0.60,
    ['strelitzia', 'tropical', 'exotic', 'indoor', 'botanical']
  ),
  createRealAsset(
    'nat-cactus-saguaro',
    'Desert Saguaro Cactus',
    'Nature & Outdoor',
    'Iconic multi-armed branched desert saguaro cactus with ribbed spines.',
    'SAGUARO CACTUS',
    'bg-green-500/20 text-green-300 border-green-500/30',
    '🌵',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#15803d',
    0.65,
    ['cactus', 'desert', 'saguaro', 'succulent', 'western']
  ),
  createRealAsset(
    'nat-flower-vase-roses',
    'Glass Vase with Fresh Roses',
    'Nature & Outdoor',
    'Cylindrical glass vase filled with fresh water and blooming crimson roses.',
    'ROSE BOUQUET',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '🌹',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#e11d48',
    0.35,
    ['roses', 'flowers', 'vase', 'bouquet', 'romantic']
  ),
  createRealAsset(
    'nat-sunflower-arrangement',
    'Vibrant Sunflower Floral Display',
    'Nature & Outdoor',
    'Rustic ceramic jug brimming with radiant golden sunflowers and eucalyptus.',
    'SUNFLOWERS',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🌻',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#eab308',
    0.38,
    ['sunflower', 'flowers', 'rustic', 'summer', 'floral']
  ),
  createRealAsset(
    'nat-bamboo-grove',
    'Clumping Bamboo Screen Grove',
    'Nature & Outdoor',
    'Tall graceful green bamboo culms forming a natural zen privacy screen.',
    'BAMBOO GROVE',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🎋',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#059669',
    0.75,
    ['bamboo', 'zen', 'privacy', 'garden', 'asian']
  ),
  createRealAsset(
    'nat-fern-boston',
    'Lush Boston Fern Pedestal',
    'Nature & Outdoor',
    'Cascading feathery Boston fern fronds displayed on a tall fluted stand.',
    'BOSTON FERN',
    'bg-green-500/20 text-green-300 border-green-500/30',
    '🌿',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#16a34a',
    0.45,
    ['fern', 'foliage', 'greenery', 'indoor', 'pedestal']
  ),
  createRealAsset(
    'nat-zen-rock-garden',
    'Zen Meditation Stone Set',
    'Nature & Outdoor',
    'Arrangement of smooth river stones and raked white quartz sand.',
    'ZEN STONES',
    'bg-stone-500/20 text-stone-300 border-stone-500/30',
    '🪨',
    `${BASE_ITEM_URL}/indoor-plant/thumbnail.webp`,
    `${BASE_ITEM_URL}/indoor-plant/model.glb`,
    '#78716c',
    0.40,
    ['zen', 'stones', 'meditation', 'rocks', 'peace']
  ),
  createRealAsset(
    'nat-outdoor-firepit',
    'Cast Iron Garden Fire Bowl',
    'Nature & Outdoor',
    'Heavy round cast iron outdoor wood-burning patio firepit bowl.',
    'FIRE PIT',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '🔥',
    `${BASE_ITEM_URL}/suspended-fireplace/thumbnail.webp`,
    `${BASE_ITEM_URL}/suspended-fireplace/model.glb`,
    '#ea580c',
    0.60,
    ['firepit', 'outdoor', 'patio', 'campfire', 'garden']
  ),
  createRealAsset(
    'nat-birdbath-fountain',
    'Tiered Stone Birdbath Fountain',
    'Nature & Outdoor',
    'Classical 2-tier carved limestone garden water fountain and birdbath.',
    'STONE FOUNTAIN',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '⛲',
    `${BASE_ITEM_URL}/bathroom-sink/thumbnail.webp`,
    `${BASE_ITEM_URL}/bathroom-sink/model.glb`,
    '#0891b2',
    0.65,
    ['fountain', 'birdbath', 'garden', 'water', 'stone']
  ),
  createRealAsset(
    'nat-garden-pergola',
    'Timber Shade Pergola Arbor',
    'Nature & Outdoor',
    'Architectural cedar wood open-beam garden patio shade pergola.',
    'CEDAR PERGOLA',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🏛️',
    `${BASE_ITEM_URL}/fence/thumbnail.webp`,
    `${BASE_ITEM_URL}/fence/model.glb`,
    '#b45309',
    0.95,
    ['pergola', 'arbor', 'patio', 'garden', 'timber']
  )
];
