import { Real3DAsset, createRealAsset, BASE_ITEM_URL, BASE_KHRONOS_URL } from './types';

// ============================================================================
// 1. EMERGENCY, MEDICAL, SURGICAL & RESCUE VEHICLES (20+ items)
// ============================================================================
export const EMERGENCY_VEHICLES: Real3DAsset[] = [
  createRealAsset(
    'veh-emerg-ambulance-als',
    'Advanced Life Support (ALS) Paramedic Ambulance',
    'Vehicles',
    'High-roof paramedic emergency medical response vehicle equipped with defibrillator, oxygen supply, and strobe lightbars.',
    'EMERGENCY ALS',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🚑',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#dc2626',
    0.92,
    ['emergency', 'medical', 'surgery', 'ambulance', 'paramedic', 'rescue', 'hospital', 'als']
  ),
  createRealAsset(
    'veh-emerg-surgical-trailer',
    'Mobile Surgical Hospital Operations Unit',
    'Vehicles',
    'Deployable field hospital surgical unit with sterile operating room container, laminar airflow, and surgical lighting.',
    'SURGERY UNIT',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🏥',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#059669',
    0.95,
    ['surgery', 'hospital', 'surgical', 'medical', 'clinic', 'emergency', 'operating room', 'trailer']
  ),
  createRealAsset(
    'veh-emerg-paramedic-suv',
    'First Responder Rapid Medical SUV',
    'Vehicles',
    'All-wheel-drive emergency doctor and rapid paramedic triage command crossover with trauma kit compartments.',
    'RAPID TRIAGE',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🚙',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#2563eb',
    0.88,
    ['paramedic', 'medical', 'doctor', 'triage', 'suv', 'first responder', 'emergency']
  ),
  createRealAsset(
    'veh-emerg-fire-pumper',
    'Municipal Fire Rescue Pumper Engine',
    'Vehicles',
    'Heavy-duty municipal fire engine with high-pressure 1500 GPM water pump, rescue hose reels, and emergency siren.',
    'FIRE ENGINE',
    'bg-red-600/20 text-red-300 border-red-500/30',
    '🚒',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#b91c1c',
    0.95,
    ['fire', 'fire truck', 'pumper', 'rescue', 'emergency', 'municipal', 'engine']
  ),
  createRealAsset(
    'veh-emerg-aerial-ladder',
    'Aerial Heavy Ladder Rescue Truck',
    'Vehicles',
    '100-foot telescopic turntable aerial ladder platform with high-rise rescue cage and integrated water master stream.',
    'LADDER RESCUE',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '🚒',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#e11d48',
    0.98,
    ['ladder', 'fire', 'aerial', 'rescue', 'high-rise', 'emergency', 'truck']
  ),
  createRealAsset(
    'veh-emerg-air-ambulance',
    'Critical Care Aeromedical Air Ambulance Helicopter',
    'Vehicles',
    'Twin-turbine aeromedical evacuation helicopter configured with patient stretcher, flight paramedic station, and life support.',
    'AIR AMBULANCE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🚁',
    `${BASE_KHRONOS_URL}/DamagedHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#d97706',
    0.90,
    ['helicopter', 'air ambulance', 'aeromedical', 'medical', 'surgery', 'evacuation', 'flight']
  ),
  createRealAsset(
    'veh-emerg-search-buggy',
    'Search & Rescue Wilderness All-Terrain Buggy',
    'Vehicles',
    'Heavy roll cage 4x4 buggy with high-intensity LED searchlights, winch, and mountain rescue stretcher rack.',
    'SAR BUGGY',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '🚙',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#ea580c',
    0.70,
    ['sar', 'search and rescue', 'buggy', 'wilderness', 'offroad', 'mountain', 'rescue']
  ),
  createRealAsset(
    'veh-emerg-swat-bearcat',
    'SWAT Tactical Armored Rescue Unit',
    'Vehicles',
    'Ballistic-grade armored emergency rescue carrier with run-flat tires and reinforced tactical ramming bumper.',
    'TACTICAL RESCUE',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🛡️',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#334155',
    0.92,
    ['swat', 'armored', 'tactical', 'rescue', 'police', 'security', 'vehicle']
  ),
  createRealAsset(
    'veh-emerg-blood-courier-ev',
    'Hospital Blood & Organ Transport EV',
    'Vehicles',
    'Priority high-speed electric courier with temperature-controlled cryogenic organ and blood transfusion storage.',
    'ORGAN COURIER',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🚗',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#0891b2',
    0.85,
    ['organ', 'blood', 'courier', 'hospital', 'surgery', 'medical', 'electric', 'ev']
  ),
  createRealAsset(
    'veh-emerg-coast-guard-boat',
    'Coast Guard Coastal Rescue Jet Boat',
    'Vehicles',
    'Self-righting all-weather coastal search and rescue watercraft with twin waterjet propulsion and marine radar.',
    'COAST RESCUE',
    'bg-blue-600/20 text-blue-300 border-blue-500/30',
    '🚤',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#1d4ed8',
    0.88,
    ['boat', 'coast guard', 'watercraft', 'rescue', 'marine', 'emergency', 'sea']
  ),
  createRealAsset(
    'veh-emerg-hazmat-command',
    'HAZMAT Toxic Containment Command Truck',
    'Vehicles',
    'Specialized chemical, biological, and radiological decontamination vehicle with positive-pressure air filtration.',
    'HAZMAT COMMAND',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '☣️',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#ca8a04',
    0.94,
    ['hazmat', 'chemical', 'decontamination', 'toxic', 'emergency', 'truck']
  ),
  createRealAsset(
    'veh-emerg-micu-unit',
    'Mobile Intensive Care Unit (MICU)',
    'Vehicles',
    'Specialized critical care transport vehicle with integrated ventilators, ECG telemetry, and infusion pumps.',
    'MICU TRANSPORT',
    'bg-teal-500/20 text-teal-300 border-teal-500/30',
    '🏥',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#0d9488',
    0.93,
    ['micu', 'intensive care', 'icu', 'medical', 'surgery', 'hospital', 'transport']
  ),
  createRealAsset(
    'veh-emerg-disaster-support',
    'Disaster Emergency Relief Response Truck',
    'Vehicles',
    'Off-grid disaster relief command vehicle with satellite communications dish, emergency power generators, and supplies.',
    'DISASTER RELIEF',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🚚',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#4338ca',
    0.95,
    ['disaster', 'relief', 'emergency', 'support', 'humanitarian', 'truck']
  ),
  createRealAsset(
    'veh-emerg-med-drone',
    'Autonomous Medical Supply Delivery Drone',
    'Vehicles',
    'Long-range autonomous multi-rotor medical drone for delivering antivenom, defibrillators, and vaccines to remote areas.',
    'MED DRONE',
    'bg-purple-500/20 text-purple-300 border-purple-500/30',
    '🛸',
    `${BASE_ITEM_URL}/ceiling-fan/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-fan/model.glb`,
    '#9333ea',
    0.45,
    ['drone', 'medical', 'delivery', 'autonomous', 'surgery', 'vaccine', 'uav']
  ),
  createRealAsset(
    'veh-emerg-airport-crash-tender',
    'Airport Crash Rescue Rapid Tender',
    'Vehicles',
    'Heavy 6x6 airfield crash tender equipped with high-volume roof aqueous film-forming foam (AFFF) cannon.',
    'CRASH TENDER',
    'bg-lime-500/20 text-lime-300 border-lime-500/30',
    '🚒',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#65a30d',
    0.96,
    ['airport', 'crash tender', 'fire', 'rescue', 'aircraft', 'aviation', 'emergency']
  ),
  createRealAsset(
    'veh-emerg-neonatal-van',
    'Neonatal Intensive Care Transport Van',
    'Vehicles',
    'Vibration-damped neonatal transport vehicle with infant incubators, nitric oxide delivery, and pediatric monitoring.',
    'NEONATAL CARE',
    'bg-pink-500/20 text-pink-300 border-pink-500/30',
    '🚐',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#db2777',
    0.90,
    ['neonatal', 'pediatric', 'incubator', 'infant', 'medical', 'hospital', 'ambulance']
  ),
  createRealAsset(
    'veh-emerg-snowmobile-rescue',
    'Alpine Mountain Rescue Snowmobile',
    'Vehicles',
    'Tracked winter mountain rescue vehicle with avalanche rescue beacon transceiver, heated handles, and emergency tow sled.',
    'SNOW RESCUE',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '🛷',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#0284c7',
    0.55,
    ['snowmobile', 'alpine', 'mountain', 'rescue', 'snow', 'winter', 'avalanche']
  ),
  createRealAsset(
    'veh-emerg-fire-chief-suv',
    'Incident Command Fire Chief SUV',
    'Vehicles',
    'Emergency scene command crossover vehicle featuring multi-band digital tactical radio matrix and incident board.',
    'FIRE COMMAND',
    'bg-red-700/20 text-red-300 border-red-600/30',
    '🚨',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#991b1b',
    0.88,
    ['chief', 'command', 'fire', 'incident', 'emergency', 'suv', 'first responder']
  ),
  createRealAsset(
    'veh-emerg-zodiac-boat',
    'Flood & Swiftwater Rescue Inflatable Zodiac',
    'Vehicles',
    'Reinforced heavy hypalon hull inflatable rescue boat designed for swiftwater flood evacuations and shallow river rescue.',
    'SWIFTWATER BOAT',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🛶',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#3b82f6',
    0.60,
    ['flood', 'water', 'rescue', 'inflatable', 'boat', 'swiftwater', 'zodiac']
  ),
  createRealAsset(
    'veh-emerg-mobile-clinic',
    'Mobile Field Health Clinic & Triage Van',
    'Vehicles',
    'Community outreach health vehicle equipped with vaccination fridges, examination couch, and diagnostic ultrasound.',
    'FIELD CLINIC',
    'bg-emerald-600/20 text-emerald-300 border-emerald-500/30',
    '🚐',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#047857',
    0.91,
    ['clinic', 'mobile health', 'triage', 'medical', 'surgery', 'outreach', 'van']
  )
];

// ============================================================================
// 2. CARTOON, STYLIZED & LOW-POLY VEHICLES (20+ items)
// ============================================================================
export const CARTOON_VEHICLES: Real3DAsset[] = [
  createRealAsset(
    'veh-toon-city-taxi',
    'Toon Yellow City Taxi',
    'Vehicles',
    'Playful stylized yellow urban cab with oversized cartoon roof checker sign and curved bouncy fenders.',
    'CARTOON TAXI',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🚕',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#eab308',
    0.65,
    ['cartoon', 'taxi', 'cab', 'toon', 'stylized', 'low-poly', 'car']
  ),
  createRealAsset(
    'veh-toon-hatchback',
    'Low-Poly Pop Hatchback',
    'Vehicles',
    'Minimalist geometric low-poly 3-door city hatchback with vibrant pastel finish and bold stylized wheels.',
    'LOW-POLY CAR',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🚗',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#10b981',
    0.60,
    ['cartoon', 'low-poly', 'hatchback', 'stylized', 'compact', 'toon', 'car']
  ),
  createRealAsset(
    'veh-toon-ice-cream-truck',
    'Toon Pastel Ice Cream Van',
    'Vehicles',
    'Charming retro ice cream truck with giant soft-serve cone rooftop prop and cheerful serving window awning.',
    'ICE CREAM VAN',
    'bg-pink-500/20 text-pink-300 border-pink-500/30',
    '🍦',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#ec4899',
    0.75,
    ['cartoon', 'ice cream', 'truck', 'van', 'food truck', 'toon', 'sweet']
  ),
  createRealAsset(
    'veh-toon-muscle-roadster',
    'Stylized Retro Muscle Roadster',
    'Vehicles',
    'Exaggerated cartoon muscle car with oversized chrome supercharger blower scoop and dual side exhausts.',
    'TOON MUSCLE',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🏎️',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#ef4444',
    0.68,
    ['cartoon', 'muscle car', 'roadster', 'hot rod', 'toon', 'racing', 'car']
  ),
  createRealAsset(
    'veh-toon-police-cruiser',
    'Cartoon Police Patrol Cruiser',
    'Vehicles',
    'Chunky low-poly police car with blue and red rooftop beacon bubble lights and stylized push-bar bumper.',
    'TOON POLICE',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🚓',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#3b82f6',
    0.65,
    ['cartoon', 'police', 'cop', 'cruiser', 'patrol', 'toon', 'law']
  ),
  createRealAsset(
    'veh-toon-delivery-van',
    'Low-Poly Express Delivery Van',
    'Vehicles',
    'Clean isometric low-poly boxy parcel courier van with cartoon proportions and smooth rounded edges.',
    'LOW-POLY VAN',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '📦',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#f59e0b',
    0.72,
    ['cartoon', 'delivery', 'van', 'parcel', 'courier', 'low-poly', 'logistics']
  ),
  createRealAsset(
    'veh-toon-monster-truck',
    'Toon Big-Wheel Monster Truck',
    'Vehicles',
    'Massive cartoon monster truck with exaggerated 66-inch balloon tires and neon shock absorber suspension springs.',
    'MONSTER TRUCK',
    'bg-purple-500/20 text-purple-300 border-purple-500/30',
    '🛻',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#a855f7',
    0.78,
    ['monster truck', 'cartoon', 'big wheel', 'offroad', 'toon', 'truck']
  ),
  createRealAsset(
    'veh-toon-speedster',
    'Stylized Open-Top Speedster',
    'Vehicles',
    'Classic 1950s inspired cartoon open-cockpit racing speedster with curved windscreen and white roundel number decal.',
    'VINTAGE SPEEDSTER',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '🏁',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#f43f5e',
    0.62,
    ['speedster', 'vintage', 'cartoon', 'racecar', 'retro', 'speed', 'toon']
  ),
  createRealAsset(
    'veh-toon-dune-buggy',
    'Cartoon Sand Dune Buggy',
    'Vehicles',
    'Vibrant beach buggy with visible low-poly tubular roll cage, wide sand-paddle tires, and colorful surf flag.',
    'BEACH BUGGY',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '🏖️',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#f97316',
    0.65,
    ['buggy', 'dune', 'beach', 'cartoon', 'sand', 'offroad', 'fun']
  ),
  createRealAsset(
    'veh-toon-city-bus',
    'Low-Poly Modern City Bus',
    'Vehicles',
    'Stylized clean transit bus with panoramic cartoon windows, passenger doors, and rooftop battery pack.',
    'LOW-POLY BUS',
    'bg-teal-500/20 text-teal-300 border-teal-500/30',
    '🚌',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#14b8a6',
    0.80,
    ['bus', 'city bus', 'transit', 'cartoon', 'low-poly', 'commute']
  ),
  createRealAsset(
    'veh-toon-tractor',
    'Toon Farm Utility Tractor',
    'Vehicles',
    'Cute red agricultural farm tractor with giant ribbed rear tractor wheels and vertical puffing exhaust pipe.',
    'FARM TRACTOR',
    'bg-red-600/20 text-red-300 border-red-500/30',
    '🚜',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#dc2626',
    0.68,
    ['tractor', 'farm', 'agriculture', 'cartoon', 'toon', 'rural']
  ),
  createRealAsset(
    'veh-toon-grand-prix',
    'Stylized Grand Prix F1 Racecar',
    'Vehicles',
    'Aerodynamic cartoon Formula open-wheel racecar with oversized front wing spoiler and bold racing livery.',
    'GP RACER',
    'bg-blue-600/20 text-blue-300 border-blue-500/30',
    '🏎️',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#2563eb',
    0.65,
    ['f1', 'formula', 'racecar', 'grand prix', 'cartoon', 'racing', 'speed']
  ),
  createRealAsset(
    'veh-toon-camper-rv',
    'Cartoon Adventure Camper RV Van',
    'Vehicles',
    'Cozy stylized campervan with surfboard roof rack, pop-up tent roof, and retro two-tone turquoise paintwork.',
    'CAMPER VAN',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🚐',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#06b6d4',
    0.74,
    ['camper', 'rv', 'vanlife', 'adventure', 'cartoon', 'camping', 'surf']
  ),
  createRealAsset(
    'veh-toon-compact-micro',
    'Low-Poly Compact Micro Car',
    'Vehicles',
    'Super-mini eco city car with bubble silhouette, large circular cartoon headlights, and tight turning radius.',
    'MICRO CAR',
    'bg-lime-500/20 text-lime-300 border-lime-500/30',
    '🚙',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#84cc16',
    0.55,
    ['micro', 'compact', 'city car', 'low-poly', 'cartoon', 'eco', 'mini']
  ),
  createRealAsset(
    'veh-toon-steam-train',
    'Toon Steam Locomotive Train',
    'Vehicles',
    'Classic storybook steam train engine with brass chimney funnel, cowcatcher grill, and red tender wagon.',
    'STEAM TRAIN',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🚂',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyTrain/glTF-Binary/ToyTrain.glb`,
    '#b91c1c',
    0.70,
    ['train', 'locomotive', 'steam', 'railway', 'cartoon', 'toy', 'transport']
  ),
  createRealAsset(
    'veh-toon-garbage-truck',
    'Stylized Recycling & Garbage Truck',
    'Vehicles',
    'Bright green cartoon municipal sanitation truck with mechanical rear waste compactor bin.',
    'RECYCLING TRUCK',
    'bg-emerald-600/20 text-emerald-300 border-emerald-500/30',
    '♻️',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#059669',
    0.76,
    ['garbage', 'recycling', 'sanitation', 'truck', 'cartoon', 'municipal']
  ),
  createRealAsset(
    'veh-toon-bulldozer',
    'Cartoon Construction Bulldozer',
    'Vehicles',
    'Chunky yellow construction bulldozer with heavy-duty front dozer blade and thick rubber caterpillar tracks.',
    'BULLDOZER',
    'bg-amber-600/20 text-amber-300 border-amber-500/30',
    '🚜',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#d97706',
    0.72,
    ['bulldozer', 'construction', 'dozer', 'heavy machine', 'cartoon', 'earthmoving']
  ),
  createRealAsset(
    'veh-toon-food-truck',
    'Low-Poly Street Food Taco Truck',
    'Vehicles',
    'Charming mobile street food truck with fold-out menu board, colorful canopy awning, and glowing counter lights.',
    'FOOD TRUCK',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '🌮',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#ea580c',
    0.75,
    ['food truck', 'taco', 'street food', 'van', 'cartoon', 'culinary', 'low-poly']
  ),
  createRealAsset(
    'veh-toon-hot-rod',
    'Toon Vintage 1932 Hot Rod Coupe',
    'Vehicles',
    'Classic chopped-top vintage hot rod with flame paint graphics along the hood and exposed chrome V8 engine block.',
    'HOT ROD',
    'bg-purple-600/20 text-purple-300 border-purple-500/30',
    '🔥',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#7e22ce',
    0.66,
    ['hot rod', 'vintage', 'flames', 'custom', 'cartoon', 'coupe', 'classic']
  ),
  createRealAsset(
    'veh-toon-golf-buggy',
    'Stylized Resort & Golf Buggy',
    'Vehicles',
    'Open-sided compact electric resort buggy with striped sun canopy and twin golf bag club holders on the rear.',
    'GOLF BUGGY',
    'bg-green-500/20 text-green-300 border-green-500/30',
    '⛳',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#22c55e',
    0.58,
    ['golf cart', 'buggy', 'resort', 'cartoon', 'golf', 'electric']
  )
];

// ============================================================================
// 3. REALISTIC URBAN, ELECTRIC & PASSENGER CARS (20+ items)
// ============================================================================
export const REALISTIC_CARS: Real3DAsset[] = [
  createRealAsset(
    'veh-car-tesla-sedan',
    'High-Performance Electric Sports Sedan',
    'Vehicles',
    'Sleek aerodynamic all-electric luxury performance sedan featuring dual-motor AWD and flush automated door handles.',
    'ELECTRIC EV',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🚗',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#dc2626',
    0.95,
    ['tesla', 'ev', 'electric', 'sedan', 'car', 'luxury', 'sports']
  ),
  createRealAsset(
    'veh-car-luxury-suv',
    'Luxury AWD Family Crossover SUV',
    'Vehicles',
    'Full-size luxury crossover SUV featuring continuous panoramic glass roof, active air suspension, and 7-passenger seating.',
    'LUXURY SUV',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🚙',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#4f46e5',
    0.95,
    ['suv', 'crossover', 'luxury', 'family', 'awd', 'car', 'vehicle']
  ),
  createRealAsset(
    'veh-car-track-coupe',
    'Twin-Turbo Mid-Engine Carbon Coupe',
    'Vehicles',
    'Carbon fiber monocoque mid-engine supercar coupe with active rear wing diffuser and forged alloy wheels.',
    'SPORTS COUPE',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '🏎️',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#e11d48',
    0.90,
    ['coupe', 'supercar', 'sports car', 'turbo', 'racing', 'speed']
  ),
  createRealAsset(
    'veh-car-executive-limo',
    'Executive Long-Wheelbase Limousine',
    'Vehicles',
    'Chauffeur-driven luxury flagship limousine with privacy partition, reclining executive lounge seats, and quiet acoustic cabin.',
    'EXECUTIVE LIMO',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🚘',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#1e293b',
    0.98,
    ['limousine', 'executive', 'luxury', 'vip', 'sedan', 'chauffeur']
  ),
  createRealAsset(
    'veh-car-compact-ev',
    'Compact Zero-Emission Urban EV',
    'Vehicles',
    'Agile urban commuter electric hatchback with high-density lithium battery and rapid CCS fast-charging capability.',
    'URBAN EV',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '⚡',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#059669',
    0.80,
    ['ev', 'electric', 'urban', 'commute', 'hatchback', 'green', 'city']
  ),
  createRealAsset(
    'veh-car-hybrid-hypercar',
    'High-Speed Hybrid Track Hypercar',
    'Vehicles',
    '1200HP hybrid V8 hypercar with formula-derived kinetic energy recovery system (KERS) and active aero flaps.',
    'HYPERCAR',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🏁',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#d97706',
    0.92,
    ['hypercar', 'supercar', 'hybrid', 'racing', 'exotic', 'track']
  ),
  createRealAsset(
    'veh-car-convertible-gt',
    'Convertible Grand Tourer Roadster',
    'Vehicles',
    '2-door open-top luxury grand tourer roadster with motorized folding acoustic canvas roof and hand-stitched leather interior.',
    'CONVERTIBLE GT',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🏎️',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#0891b2',
    0.88,
    ['convertible', 'roadster', 'gt', 'grand tourer', 'open top', 'sports car']
  ),
  createRealAsset(
    'veh-car-muscle-v8',
    'Vintage 1968 Fastback V8 Muscle Car',
    'Vehicles',
    'Iconic American high-displacement V8 muscle car with rumbling dual exhaust pipes and classic chrome trim.',
    'V8 MUSCLE',
    'bg-red-700/20 text-red-300 border-red-600/30',
    '🔥',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#991b1b',
    0.90,
    ['muscle car', 'v8', 'vintage', 'classic', 'fastback', 'retro']
  ),
  createRealAsset(
    'veh-car-electric-wagon',
    'Aerodynamic Electric Station Wagon',
    'Vehicles',
    'Spacious family touring estate wagon with flush roof rails, large luggage tailgate, and low drag coefficient.',
    'TOURING WAGON',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🚙',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#2563eb',
    0.92,
    ['wagon', 'estate', 'touring', 'electric', 'family', 'ev', 'car']
  ),
  createRealAsset(
    'veh-car-robotaxi',
    'Autonomous Self-Driving Robo-Taxi',
    'Vehicles',
    'Level-5 autonomous driverless passenger pod equipped with rooftop solid-state LiDAR sensors and 360-degree cameras.',
    'ROBO-TAXI',
    'bg-violet-500/20 text-violet-300 border-violet-500/30',
    '🤖',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#7c3aed',
    0.85,
    ['autonomous', 'robotaxi', 'self-driving', 'lidar', 'ai', 'transit', 'pod']
  ),
  createRealAsset(
    'veh-car-4door-coupe',
    'Luxury 4-Door Sportback Coupe',
    'Vehicles',
    'Sleek sloping fastback roofline sedan with frameless door windows and dynamic matrix LED laser headlamps.',
    'SPORTBACK',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🚗',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#3f3f46',
    0.90,
    ['sportback', 'coupe', '4door', 'luxury', 'sedan', 'laser led']
  ),
  createRealAsset(
    'veh-car-city-crossover',
    'Compact AWD Urban Crossover',
    'Vehicles',
    'Elevated ride-height compact crossover with protective wheel arch cladding and efficient hybrid powertrain.',
    'AWD CROSSOVER',
    'bg-teal-500/20 text-teal-300 border-teal-500/30',
    '🚙',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#0d9488',
    0.86,
    ['crossover', 'compact', 'hybrid', 'awd', 'urban', 'car']
  ),
  createRealAsset(
    'veh-car-vintage-1930',
    'Classic 1930s Open Speedster Roadster',
    'Vehicles',
    'Heritage collectible roadster with external spare wheel mount, wire-spoke wheels, and gleaming chrome radiator grille.',
    '1930s SPEEDSTER',
    'bg-amber-600/20 text-amber-300 border-amber-500/30',
    '🏎️',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#b45309',
    0.75,
    ['vintage', 'classic', '1930s', 'roadster', 'heritage', 'antique']
  ),
  createRealAsset(
    'veh-car-perf-crossover',
    'High-Performance Electric Crossover',
    'Vehicles',
    'Dual-motor performance electric crossover with torque vectoring and carbon-ceramic brake calipers.',
    'PERF CROSSOVER',
    'bg-blue-600/20 text-blue-300 border-blue-500/30',
    '⚡',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#1d4ed8',
    0.92,
    ['crossover', 'performance', 'electric', 'ev', 'torque vectoring', 'suv']
  ),
  createRealAsset(
    'veh-car-armored-sedan',
    'Armored Executive Security Sedan',
    'Vehicles',
    'Discreet VR7 ballistic-protected executive transport sedan with reinforced floorboard and armored glass.',
    'ARMORED SEDAN',
    'bg-slate-600/20 text-slate-300 border-slate-500/30',
    '🛡️',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#475569',
    0.94,
    ['armored', 'security', 'vip', 'executive', 'bulletproof', 'sedan']
  ),
  createRealAsset(
    'veh-car-micro-city',
    'Micro Urban Commuter Smart Car',
    'Vehicles',
    'Ultra-compact 2-passenger urban electric runabout engineered for perpendicular street parking.',
    'SMART COMMUTER',
    'bg-lime-600/20 text-lime-300 border-lime-500/30',
    '🚙',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#65a30d',
    0.65,
    ['smart', 'micro', 'commuter', 'city car', 'parking', 'compact']
  ),
  createRealAsset(
    'veh-car-panoramic-sedan',
    'Panoramic Glass Touring Sedan',
    'Vehicles',
    'Luxury sedan with all-glass canopy, ambient fiber-optic cabin illumination, and semi-autonomous highway pilot.',
    'PANORAMIC SEDAN',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '🚗',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#0284c7',
    0.90,
    ['panoramic', 'sedan', 'touring', 'luxury', 'autopilot', 'car']
  ),
  createRealAsset(
    'veh-car-gt3-racer',
    'Lightweight GT3 Cup Competition Racer',
    'Vehicles',
    'Homologated FIA GT3 endurance racing car with swan-neck rear wing, lightweight Lexan windows, and FIA roll cage.',
    'GT3 RACER',
    'bg-orange-600/20 text-orange-300 border-orange-500/30',
    '🏁',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#c2410c',
    0.92,
    ['gt3', 'cup', 'racer', 'endurance', 'motorsport', 'fia', 'track']
  ),
  createRealAsset(
    'veh-car-solar-ev',
    'Solar-Assisted Electric Commuter',
    'Vehicles',
    'High-efficiency solar commuter vehicle with photovoltaic cell embedded roof panels generating up to 40km daily range.',
    'SOLAR EV',
    'bg-yellow-600/20 text-yellow-300 border-yellow-500/30',
    '☀️',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#ca8a04',
    0.85,
    ['solar', 'ev', 'photovoltaic', 'green', 'commuter', 'efficiency']
  ),
  createRealAsset(
    'veh-car-midengine-classic',
    'Classic Air-Cooled Mid-Engine Coupe',
    'Vehicles',
    'Iconic 1970s wedge-profile mid-engine sports coupe with pop-up headlights and gated manual transmission shifter.',
    'WEDGE COUPE',
    'bg-red-600/20 text-red-300 border-red-500/30',
    '🏎️',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#b91c1c',
    0.82,
    ['wedge', 'classic', 'mid-engine', 'pop-up', '1970s', 'sports car']
  )
];

// ============================================================================
// 4. COMMERCIAL, HEAVY DUTY & LOGISTICS VEHICLES (20+ items)
// ============================================================================
export const COMMERCIAL_VEHICLES: Real3DAsset[] = [
  createRealAsset(
    'veh-comm-liquid-tanker',
    'Commercial Transport Liquid / Milk Tanker Truck',
    'Vehicles',
    'Heavy-duty stainless steel sanitary liquid and dairy bulk distribution tanker truck with baffle compartments.',
    'BULK TANKER',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🚛',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#b45309',
    0.85,
    ['tanker', 'truck', 'liquid', 'commercial', 'logistics', 'dairy', 'freight']
  ),
  createRealAsset(
    'veh-comm-cargo-van',
    'High-Roof Express Freight Delivery Van',
    'Vehicles',
    'Extended high-roof commercial panel van configured for last-mile logistics distribution and pallet loading.',
    'CARGO VAN',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🚐',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#475569',
    0.90,
    ['van', 'cargo', 'delivery', 'logistics', 'freight', 'commercial']
  ),
  createRealAsset(
    'veh-comm-pickup-4x4',
    'Heavy-Duty Dual-Cab 4x4 Utility Pickup',
    'Vehicles',
    'Rugged dual-cab workhorse pickup truck with steel utility bed, towing package, and all-terrain mud tires.',
    '4X4 PICKUP',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🛻',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#3f3f46',
    0.92,
    ['pickup', 'truck', '4x4', 'utility', 'workhorse', 'towing']
  ),
  createRealAsset(
    'veh-comm-semi-trailer',
    'Intermodal Container Semi-Trailer Truck',
    'Vehicles',
    'Class-8 long-haul highway tractor with aerodynamic sleeper cab and 53-foot enclosed dry freight semi-trailer.',
    'SEMI TRACTOR',
    'bg-blue-600/20 text-blue-300 border-blue-500/30',
    '🚛',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#1d4ed8',
    0.98,
    ['semi', 'tractor', 'trailer', 'freight', 'long haul', 'class 8', 'logistics']
  ),
  createRealAsset(
    'veh-comm-dump-truck',
    'Heavy Construction Hydraulic Dump Truck',
    'Vehicles',
    'Tri-axle heavy civil construction dump truck with high-capacity steel rock body and twin hydraulic hoist rams.',
    'DUMP TRUCK',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🏗️',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#eab308',
    0.95,
    ['dump truck', 'construction', 'quarry', 'earthmoving', 'heavy', 'truck']
  ),
  createRealAsset(
    'veh-comm-concrete-mixer',
    'Ready-Mix Concrete Transit Mixer Truck',
    'Vehicles',
    'Continuous rotating spiral drum transit mixer truck for pouring building foundations and commercial infrastructure.',
    'CEMENT MIXER',
    'bg-stone-500/20 text-stone-300 border-stone-500/30',
    '🏢',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#78716c',
    0.94,
    ['concrete', 'cement', 'mixer', 'construction', 'building', 'truck']
  ),
  createRealAsset(
    'veh-comm-forklift',
    'Electric Counterbalance Warehouse Forklift',
    'Vehicles',
    'Industrial 3-stage mast electric pallet forklift truck with side-shift forks and digital load weight scale.',
    'FORKLIFT',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🚜',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#d97706',
    0.70,
    ['forklift', 'warehouse', 'pallet', 'logistics', 'industrial', 'material handling']
  ),
  createRealAsset(
    'veh-comm-excavator',
    'Heavy Hydraulic Tracked Excavator',
    'Vehicles',
    '30-ton tracked earthmoving excavator featuring heavy digging bucket, 360-degree swing cab, and hydraulic boom.',
    'EXCAVATOR',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '⛏️',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#ea580c',
    0.95,
    ['excavator', 'digger', 'construction', 'earthmoving', 'heavy machinery', 'mining']
  ),
  createRealAsset(
    'veh-comm-tow-truck',
    'Flatbed Roadside Recovery Tow Truck',
    'Vehicles',
    'Hydraulic slide-back flatbed recovery carrier with wheel-lift stinger and high-pull electric recovery winch.',
    'TOW TRUCK',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🛞',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#4338ca',
    0.92,
    ['tow truck', 'recovery', 'flatbed', 'roadside', 'transport', 'vehicle']
  ),
  createRealAsset(
    'veh-comm-transit-bus',
    'Articulated City Passenger Transit Bus',
    'Vehicles',
    '60-foot articulated low-floor passenger transit bus with central flexible bellows turntable and wheelchair ramps.',
    'TRANSIT BUS',
    'bg-cyan-600/20 text-cyan-300 border-cyan-500/30',
    '🚍',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#0891b2',
    0.96,
    ['bus', 'transit', 'articulated', 'passenger', 'city', 'public transport']
  ),
  createRealAsset(
    'veh-comm-airport-tug',
    'Airport Baggage & Cargo Tug Tractor',
    'Vehicles',
    'Heavy low-profile electric airport ground support tractor with multiple tow hitch couplers for baggage cart trains.',
    'BAGGAGE TUG',
    'bg-yellow-600/20 text-yellow-300 border-yellow-500/30',
    '🧳',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#ca8a04',
    0.65,
    ['airport', 'baggage', 'tug', 'ground support', 'cargo', 'aviation']
  ),
  createRealAsset(
    'veh-comm-mining-dump',
    'Heavy Open-Pit Mining Dump Hauler',
    'Vehicles',
    'Ultra-class 400-ton diesel-electric mining dump truck with giant 13-foot diameter tires and massive rock tub.',
    'MINING HAULER',
    'bg-amber-700/20 text-amber-300 border-amber-600/30',
    '⛰️',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#92400e',
    0.98,
    ['mining', 'hauler', 'quarry', 'dump truck', 'heavy equipment', 'earthmoving']
  ),
  createRealAsset(
    'veh-comm-reefer-truck',
    'Refrigerated Food Distribution Truck',
    'Vehicles',
    'Thermo-insulated cold chain distribution box truck with nose-mount refrigeration unit and hydraulic liftgate.',
    'REEFER TRUCK',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '❄️',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#0284c7',
    0.91,
    ['reefer', 'refrigerated', 'cold chain', 'food', 'produce', 'logistics']
  ),
  createRealAsset(
    'veh-comm-electric-stepvan',
    'Electric Last-Mile Parcel Delivery Stepvan',
    'Vehicles',
    'Custom zero-emission walk-in parcel delivery stepvan with sliding bulkhead door and low cargo step height.',
    'PARCEL STEPVAN',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '📦',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#10b981',
    0.88,
    ['stepvan', 'delivery', 'parcel', 'electric', 'ev', 'last-mile', 'courier']
  ),
  createRealAsset(
    'veh-comm-motor-grader',
    'Earthmoving Road Construction Motor Grader',
    'Vehicles',
    'Precision motor grader equipped with 14-foot adjustable moldboard blade and rear ripping scarifier shanks.',
    'MOTOR GRADER',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🚧',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#eab308',
    0.92,
    ['grader', 'roadwork', 'earthmoving', 'construction', 'leveling', 'heavy']
  ),
  createRealAsset(
    'veh-comm-mobile-crane',
    'Mobile Telescopic Heavy Boom Crane',
    'Vehicles',
    'All-terrain 5-axle mobile carrier crane with 60-meter multi-section hydraulic telescopic boom and outriggers.',
    'MOBILE CRANE',
    'bg-rose-600/20 text-rose-300 border-rose-500/30',
    '🏗️',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#e11d48',
    0.98,
    ['crane', 'telescopic', 'lifting', 'construction', 'rigging', 'heavy']
  ),
  createRealAsset(
    'veh-comm-freight-railcar',
    'Double-Stack Intermodal Freight Railcar',
    'Vehicles',
    'Heavy-duty railroad well car designed for transporting double-stacked 40-foot and 53-foot ocean shipping containers.',
    'RAIL FREIGHT',
    'bg-stone-600/20 text-stone-300 border-stone-500/30',
    '🚆',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyTrain/glTF-Binary/ToyTrain.glb`,
    '#57534e',
    0.90,
    ['rail', 'train', 'freight', 'intermodal', 'container', 'shipping']
  ),
  createRealAsset(
    'veh-comm-logging-truck',
    'Heavy Forestry Timber Logging Hauler',
    'Vehicles',
    'High-torque severe-duty logging truck equipped with steel headboard guard, log bolsters, and safety binder chains.',
    'LOGGING TRUCK',
    'bg-amber-800/20 text-amber-300 border-amber-700/30',
    '🌲',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#78350f',
    0.95,
    ['logging', 'timber', 'forestry', 'heavy', 'hauler', 'truck']
  ),
  createRealAsset(
    'veh-comm-street-sweeper',
    'Municipal High-Pressure Street Sweeper',
    'Vehicles',
    'Clean urban street cleaning vehicle with dual gutter rotary wire brooms, water spray dust suppression, and vacuum nozzle.',
    'STREET SWEEPER',
    'bg-teal-600/20 text-teal-300 border-teal-500/30',
    '🧹',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#0d9488',
    0.86,
    ['sweeper', 'sanitation', 'municipal', 'cleaning', 'city', 'maintenance']
  ),
  createRealAsset(
    'veh-comm-flatbed-cart',
    'Electric Industrial Flatbed Utility Transporter',
    'Vehicles',
    'Heavy factory electric flatbed cargo cart with textured aluminum deck and ergonomic front steering tiller.',
    'FLATBED CART',
    'bg-zinc-600/20 text-zinc-300 border-zinc-500/30',
    '⚙️',
    `${BASE_ITEM_URL}/skate/thumbnail.webp`,
    `${BASE_ITEM_URL}/skate/model.glb`,
    '#52525b',
    0.50,
    ['cart', 'flatbed', 'factory', 'industrial', 'electric', 'transporter']
  )
];

// ============================================================================
// 5. AVIATION, FLIGHT & AERIAL DRONE VEHICLES (20+ items)
// ============================================================================
export const AVIATION_VEHICLES: Real3DAsset[] = [
  createRealAsset(
    'veh-air-regional-jet',
    'Twin-Turbofan Regional Commercial Jetliner',
    'Vehicles',
    'Narrow-body passenger airliner with swept wings, winglet tips, and under-wing high-bypass turbofan engines.',
    'REGIONAL JET',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '✈️',
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#0ea5e9',
    0.95,
    ['airplane', 'jet', 'airliner', 'aviation', 'flight', 'passenger', 'transport']
  ),
  createRealAsset(
    'veh-air-transport-heli',
    'Multi-Mission Turbine Transport Helicopter',
    'Vehicles',
    'Twin-engine transport helicopter featuring 4-blade main rotor, anti-torque tail rotor, and sliding cargo cabin door.',
    'TRANSPORT HELI',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🚁',
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#2563eb',
    0.90,
    ['helicopter', 'aviation', 'rotor', 'flight', 'transport', 'heli']
  ),
  createRealAsset(
    'veh-air-med-heli',
    'Aeromedical Evacuation Air Helicopter',
    'Vehicles',
    'Specialized aeromedical flight helicopter equipped with hoist winch, searchlight, and intensive life support equipment.',
    'MED HELICOPTER',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🚁',
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#dc2626',
    0.90,
    ['medevac', 'helicopter', 'rescue', 'medical', 'surgery', 'hospital', 'flight']
  ),
  createRealAsset(
    'veh-air-survey-drone',
    'Commercial Aerial Survey Quadcopter Drone',
    'Vehicles',
    'Carbon fiber 4-rotor aerial mapping drone with 3-axis gyro-stabilized 8K camera gimbal and obstacle avoidance LiDAR.',
    'SURVEY DRONE',
    'bg-violet-500/20 text-violet-300 border-violet-500/30',
    '🛸',
    `${BASE_ITEM_URL}/ceiling-fan/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-fan/model.glb`,
    '#8b5cf6',
    0.42,
    ['drone', 'quadcopter', 'survey', 'aerial', 'mapping', 'uav', 'photography']
  ),
  createRealAsset(
    'veh-air-cargo-hexacopter',
    'Heavy-Lift Cargo Delivery Hexacopter',
    'Vehicles',
    'Industrial 6-arm heavy payload delivery drone with automated quick-release cargo locker mechanism.',
    'HEXACOPTER',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🛸',
    `${BASE_ITEM_URL}/ceiling-fan/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-fan/model.glb`,
    '#10b981',
    0.48,
    ['hexacopter', 'drone', 'cargo', 'delivery', 'heavy lift', 'logistics', 'uav']
  ),
  createRealAsset(
    'veh-air-jet-fighter',
    'Supersonic Air Superiority Tactical Fighter',
    'Vehicles',
    'Mach-2.2 capable supersonic delta-wing fighter aircraft with twin afterburning turbofans and internal weapons bays.',
    'JET FIGHTER',
    'bg-slate-600/20 text-slate-300 border-slate-500/30',
    '🛩️',
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#475569',
    0.95,
    ['fighter', 'jet', 'supersonic', 'military', 'tactical', 'aviation', 'stealth']
  ),
  createRealAsset(
    'veh-air-biplane-classic',
    'Vintage Aerobatic Timber Biplane',
    'Vehicles',
    'Heritage dual-wing aerobatic propeller aircraft with radial engine cowling, open tandem cockpit, and wire bracing.',
    'VINTAGE BIPLANE',
    'bg-amber-600/20 text-amber-300 border-amber-500/30',
    '✈️',
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#d97706',
    0.75,
    ['biplane', 'vintage', 'propeller', 'aerobatic', 'classic', 'aviation']
  ),
  createRealAsset(
    'veh-air-solar-uav',
    'High-Altitude Long-Endurance Solar UAV',
    'Vehicles',
    'Ultra-wide span solar-powered atmospheric satellite drone capable of perpetual stratospheric flight for telecommunications.',
    'SOLAR UAV',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '☀️',
    `${BASE_ITEM_URL}/ceiling-fan/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-fan/model.glb`,
    '#eab308',
    0.80,
    ['solar', 'uav', 'stratosphere', 'drone', 'high-altitude', 'aerospace']
  ),
  createRealAsset(
    'veh-air-evtol-taxi',
    'Autonomous eVTOL Urban Air Mobility Taxi',
    'Vehicles',
    'All-electric 4-passenger vertical takeoff and landing aircraft featuring 8 tilting distributed electric thruster pods.',
    'EVTOL AIR TAXI',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🚡',
    `${BASE_ITEM_URL}/ceiling-fan/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-fan/model.glb`,
    '#06b6d4',
    0.88,
    ['evtol', 'air taxi', 'urban air mobility', 'electric', 'vtol', 'future']
  ),
  createRealAsset(
    'veh-air-turboprop-plane',
    'Regional Twin-Turboprop Passenger Plane',
    'Vehicles',
    'Efficient short-runway regional commuter aircraft with high-wing configuration and dual 6-blade composite propellers.',
    'TURBOPROP',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🛩️',
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#4f46e5',
    0.92,
    ['turboprop', 'commuter', 'propeller', 'regional', 'plane', 'aviation']
  ),
  createRealAsset(
    'veh-air-floatplane',
    'Search & Rescue Amphibious Floatplane',
    'Vehicles',
    'High-wing bush plane fitted with heavy-duty twin pontoon floats and retractable landing gear wheels for land or water.',
    'FLOATPLANE',
    'bg-blue-600/20 text-blue-300 border-blue-500/30',
    '🌊',
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#2563eb',
    0.88,
    ['floatplane', 'seaplane', 'amphibious', 'bush plane', 'water', 'rescue']
  ),
  createRealAsset(
    'veh-air-agri-drone',
    'Precision Agriculture Crop Spraying Drone',
    'Vehicles',
    'High-capacity agricultural octocopter with 30-liter chemical spray tank, centrifugal atomizing nozzles, and terrain radar.',
    'AGRI DRONE',
    'bg-lime-500/20 text-lime-300 border-lime-500/30',
    '🌾',
    `${BASE_ITEM_URL}/ceiling-fan/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-fan/model.glb`,
    '#84cc16',
    0.46,
    ['agriculture', 'crop sprayer', 'farming', 'drone', 'precision', 'uav']
  ),
  createRealAsset(
    'veh-air-recon-quad',
    'Micro Tactical Reconnaissance Quadcopter',
    'Vehicles',
    'Palm-sized ultra-quiet tactical surveillance micro drone equipped with dual thermal infrared camera.',
    'MICRO RECON',
    'bg-zinc-600/20 text-zinc-300 border-zinc-500/30',
    '🔎',
    `${BASE_ITEM_URL}/ceiling-fan/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-fan/model.glb`,
    '#52525b',
    0.35,
    ['micro', 'recon', 'drone', 'surveillance', 'thermal', 'tactical']
  ),
  createRealAsset(
    'veh-air-stealth-wing',
    'Stealth Flying Wing Jet Aircraft',
    'Vehicles',
    'Tailless blended flying wing stealth bomber aircraft featuring radar-absorbent radar-deflecting faceted fuselage.',
    'STEALTH WING',
    'bg-neutral-800/20 text-neutral-300 border-neutral-700/30',
    '🛸',
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#262626',
    0.96,
    ['stealth', 'flying wing', 'bomber', 'radar', 'military', 'aerospace']
  ),
  createRealAsset(
    'veh-air-water-bomber',
    'Wildfire Aerial Water Bomber Tanker',
    'Vehicles',
    'Specialized amphibious aerial firefighting aircraft equipped with high-capacity 6,000-liter scoop hull water tanks.',
    'WATER BOMBER',
    'bg-red-600/20 text-red-300 border-red-500/30',
    '🧯',
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#dc2626',
    0.95,
    ['firefighting', 'water bomber', 'wildfire', 'aircraft', 'emergency', 'tanker']
  ),
  createRealAsset(
    'veh-air-tandem-heli',
    'Heavy-Lift Tandem Rotor Helicopter',
    'Vehicles',
    'Dual counter-rotating rotor heavy tactical transport helicopter configured with triple external cargo sling hooks.',
    'TANDEM ROTOR',
    'bg-stone-600/20 text-stone-300 border-stone-500/30',
    '🚁',
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#57534e',
    0.98,
    ['chinook', 'tandem', 'helicopter', 'heavy lift', 'cargo', 'transport']
  ),
  createRealAsset(
    'veh-air-aerobatic-monoplane',
    'Aerobatic Competition Sport Monoplane',
    'Vehicles',
    'Ultra-agile composite competition stunt plane with high roll-rate symmetrical wing profile and smoke injection system.',
    'STUNT PLANE',
    'bg-purple-600/20 text-purple-300 border-purple-500/30',
    '🛩️',
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#9333ea',
    0.72,
    ['stunt', 'aerobatic', 'monoplane', 'competition', 'air race', 'sport']
  ),
  createRealAsset(
    'veh-air-business-jet',
    'Long-Range Executive Business Jet',
    'Vehicles',
    'Intercontinental luxury private business jet with 6,500 nautical mile range, quiet VIP salon, and satellite internet.',
    'BUSINESS JET',
    'bg-sky-600/20 text-sky-300 border-sky-500/30',
    '✈️',
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#0284c7',
    0.94,
    ['private jet', 'business jet', 'vip', 'executive', 'aviation', 'luxury']
  ),
  createRealAsset(
    'veh-air-vtol-tiltrotor',
    'VTOL Autonomous Tilt-Rotor Courier Drone',
    'Vehicles',
    'Hybrid tilt-wing aircraft that takes off vertically like a helicopter and transitions to high-speed horizontal winged flight.',
    'TILT-ROTOR',
    'bg-teal-600/20 text-teal-300 border-teal-500/30',
    '🛩️',
    `${BASE_ITEM_URL}/ceiling-fan/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-fan/model.glb`,
    '#0d9488',
    0.78,
    ['tilt-rotor', 'vtol', 'drone', 'hybrid', 'express', 'autonomous']
  ),
  createRealAsset(
    'veh-air-glider-solar',
    'Stratospheric Solar Autonomous Glider',
    'Vehicles',
    'Carbon-honeycomb high aspect ratio thermal soaring research glider with distributed solar wing skin.',
    'SOLAR GLIDER',
    'bg-emerald-600/20 text-emerald-300 border-emerald-500/30',
    '🦅',
    `${BASE_KHRONOS_URL}/DamagedHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#059669',
    0.85,
    ['glider', 'soaring', 'solar', 'stratosphere', 'aerospace', 'research']
  )
];

// ============================================================================
// 6. MARITIME, WATERCRAFT & SUBMERSIBLES (20+ items)
// ============================================================================
export const MARITIME_VEHICLES: Real3DAsset[] = [
  createRealAsset(
    'veh-sea-speedboat',
    'Deep-V Stepped Hull Marine Speedboat',
    'Vehicles',
    'High-performance offshore marine powerboat with twin outboard motors, center console, and padded cockpit seating.',
    'SPEEDBOAT',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🚤',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#0891b2',
    0.90,
    ['boat', 'speedboat', 'marine', 'watercraft', 'nautical', 'sea']
  ),
  createRealAsset(
    'veh-sea-jetski',
    'Supercharged High-Performance Jet Ski',
    'Vehicles',
    '300HP personal watercraft (PWC) with ergonomic sport saddle, dynamic trim system, and jet pump propulsion.',
    'JET SKI',
    'bg-teal-500/20 text-teal-300 border-teal-500/30',
    '🌊',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#14b8a6',
    0.55,
    ['jetski', 'watercraft', 'pwc', 'marine', 'watersports', 'ocean']
  ),
  createRealAsset(
    'veh-sea-auv-sub',
    'Deep-Sea Oceanographic AUV Submarine Drone',
    'Vehicles',
    'Torpedo-shaped autonomous underwater vehicle with side-scan sonar, multibeam bathymetry, and 6,000m depth rating.',
    'AUV SUB',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🟡',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#eab308',
    0.60,
    ['auv', 'submarine', 'underwater', 'sonar', 'deep sea', 'ocean', 'robotics']
  ),
  createRealAsset(
    'veh-sea-patrol-interceptor',
    'Coastal Patrol High-Speed Interceptor',
    'Vehicles',
    'Maritime law enforcement interceptor boat with armor-plated cabin, FLIR thermal camera, and 55-knot top speed.',
    'PATROL BOAT',
    'bg-blue-600/20 text-blue-300 border-blue-500/30',
    '⚓',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#1d4ed8',
    0.92,
    ['patrol', 'interceptor', 'coast guard', 'police', 'marine', 'boat']
  ),
  createRealAsset(
    'veh-sea-luxury-yacht',
    'Twin-Engine Luxury Express Cruiser Yacht',
    'Vehicles',
    'Flybridge motor yacht featuring teak deck dining area, hydraulic swim platform, and luxurious owner stateroom.',
    'LUXURY YACHT',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🛳️',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#4f46e5',
    0.98,
    ['yacht', 'luxury', 'cruiser', 'marine', 'boat', 'nautical', 'ship']
  ),
  createRealAsset(
    'veh-sea-rhib-rescue',
    'Rigid Inflatable Rescue Lifeboat (RHIB)',
    'Vehicles',
    'Heavy-duty commercial fiberglass hull with inflatable multi-chamber collar tubes and twin commercial outboards.',
    'RESCUE RHIB',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '🛟',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#f97316',
    0.80,
    ['rhib', 'inflatable', 'rescue', 'lifeboat', 'marine', 'boat']
  ),
  createRealAsset(
    'veh-sea-container-ship',
    'Commercial Intermodal Container Cargo Ship',
    'Vehicles',
    'Ultra-large ocean container vessel with forward bridge superstructure and capacity for 20,000 TEU freight containers.',
    'CONTAINER SHIP',
    'bg-slate-600/20 text-slate-300 border-slate-500/30',
    '🚢',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#334155',
    0.98,
    ['cargo ship', 'container', 'shipping', 'freight', 'ocean', 'intermodal']
  ),
  createRealAsset(
    'veh-sea-solar-catamaran',
    'Solar-Electric Autonomous Catamaran',
    'Vehicles',
    'Dual-hull ocean monitoring vessel powered entirely by solar canopy array and zero-emission electric pod drives.',
    'SOLAR CATAMARAN',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '☀️',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#10b981',
    0.85,
    ['catamaran', 'solar', 'electric', 'autonomous', 'eco', 'marine', 'boat']
  ),
  createRealAsset(
    'veh-sea-fishing-trawler',
    'Commercial Deep-Sea Fishing Trawler',
    'Vehicles',
    'Sturdy steel-hull commercial stern trawler with aft net gantry, refrigerated fish holds, and fish-finding sonar.',
    'FISHING TRAWLER',
    'bg-amber-600/20 text-amber-300 border-amber-500/30',
    '🎣',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#d97706',
    0.92,
    ['trawler', 'fishing', 'commercial', 'marine', 'boat', 'seafood']
  ),
  createRealAsset(
    'veh-sea-hydrofoil-ferry',
    'High-Speed Passenger Hydrofoil Catamaran',
    'Vehicles',
    '45-knot foil-borne passenger ferry with submerged titanium wing foils that lift the hull out of the water.',
    'HYDROFOIL FERRY',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '⛴️',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#0284c7',
    0.95,
    ['hydrofoil', 'ferry', 'passenger', 'transit', 'marine', 'fast boat']
  ),
  createRealAsset(
    'veh-sea-manned-submersible',
    'Manned Deep Ocean Exploration Submersible',
    'Vehicles',
    '3-person deep submergence vehicle with spherical acrylic viewport sphere and dual articulated robotic manipulator arms.',
    'EXPLORER SUB',
    'bg-yellow-600/20 text-yellow-300 border-yellow-500/30',
    '🤿',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#ca8a04',
    0.75,
    ['submersible', 'deep sea', 'exploration', 'ocean', 'manned', 'robotics']
  ),
  createRealAsset(
    'veh-sea-offshore-tug',
    'Heavy-Duty Offshore Support Tugboat',
    'Vehicles',
    'High bollard-pull ocean tugboat equipped with 360-degree azimuthing thrusters and heavy towing winch.',
    'OCEAN TUG',
    'bg-red-600/20 text-red-300 border-red-500/30',
    '🚢',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#dc2626',
    0.90,
    ['tugboat', 'tug', 'towing', 'offshore', 'harbor', 'marine', 'ship']
  ),
  createRealAsset(
    'veh-sea-racing-sailboat',
    'High-Performance Ocean Racing Sailboat',
    'Vehicles',
    'Carbon fiber grand-prix racing monohull sailboat with towering mast, Kevlar mainsail, and canting keel.',
    'RACING SAILBOAT',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '⛵',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#f43f5e',
    0.92,
    ['sailboat', 'sailing', 'yacht', 'racing', 'wind', 'ocean', 'regatta']
  ),
  createRealAsset(
    'veh-sea-pilot-boat',
    'Harbor Pilot Fast Boarding Vessel',
    'Vehicles',
    'Heavy-fendered, self-righting pilot launch designed for boarding commercial supertankers in high seas.',
    'PILOT LAUNCH',
    'bg-orange-600/20 text-orange-300 border-orange-500/30',
    '⚓',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#ea580c',
    0.85,
    ['pilot boat', 'harbor', 'boarding', 'marine', 'navigation', 'boat']
  ),
  createRealAsset(
    'veh-sea-cargo-barge',
    'Inland River Heavy Cargo Flat Barge',
    'Vehicles',
    'Flat-deck river freight barge configured for bulk cargo, heavy construction equipment, and raw material transport.',
    'CARGO BARGE',
    'bg-stone-500/20 text-stone-300 border-stone-500/30',
    '⛴️',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#78716c',
    0.94,
    ['barge', 'river', 'cargo', 'freight', 'inland', 'flat deck']
  ),
  createRealAsset(
    'veh-sea-wave-piercer',
    'Wave-Piercing Police Patrol Boat',
    'Vehicles',
    'Stealth wave-piercing catamaran hull patrol boat with forward night vision turret and boarding ramp.',
    'WAVE PIERCER',
    'bg-blue-700/20 text-blue-300 border-blue-600/30',
    '🌊',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#1e40af',
    0.88,
    ['wave piercer', 'catamaran', 'police', 'patrol', 'stealth', 'marine']
  ),
  createRealAsset(
    'veh-sea-usv-drone',
    'Autonomous Ocean Surface Data Drone (USV)',
    'Vehicles',
    'Unmanned surface vessel (USV) equipped with rigid wing sail, solar battery charger, and ocean climate sensors.',
    'SURFACE DRONE',
    'bg-teal-600/20 text-teal-300 border-teal-500/30',
    '📡',
    `${BASE_ITEM_URL}/wine-bottle/thumbnail.webp`,
    `${BASE_ITEM_URL}/wine-bottle/model.glb`,
    '#0d9488',
    0.60,
    ['usv', 'drone', 'ocean', 'climate', 'sensors', 'autonomous', 'surface']
  ),
  createRealAsset(
    'veh-sea-pontoon-boat',
    'Luxury Pontoon Deck Party Boat',
    'Vehicles',
    'Triple-tube aluminum pontoon recreational boat with perimeter lounge sofas, bimini sun top, and swim ladder.',
    'PONTOON BOAT',
    'bg-cyan-600/20 text-cyan-300 border-cyan-500/30',
    '🏖️',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#0891b2',
    0.85,
    ['pontoon', 'party boat', 'lake', 'deck', 'recreation', 'cruiser']
  ),
  createRealAsset(
    'veh-sea-whitewater-jet',
    'Heavy River Whitewater Jet Boat',
    'Vehicles',
    'Heavy-gauge aluminum shallow-draft river boat equipped with high-thrust inboard jet drive for navigating rapids.',
    'JET BOAT',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🌊',
    `${BASE_ITEM_URL}/tesla/thumbnail.webp`,
    `${BASE_ITEM_URL}/tesla/model.glb`,
    '#ef4444',
    0.82,
    ['jet boat', 'whitewater', 'rapids', 'river', 'shallow draft', 'aluminum']
  ),
  createRealAsset(
    'veh-sea-efoil-surfboard',
    'Electric Hydrofoil Carbon Surfboard (eFoil)',
    'Vehicles',
    'Wireless Bluetooth remote-controlled electric hydrofoil surfboard that glides smoothly above ocean swells.',
    'EFOIL SURF',
    'bg-purple-500/20 text-purple-300 border-purple-500/30',
    '🏄',
    `${BASE_ITEM_URL}/skate/thumbnail.webp`,
    `${BASE_ITEM_URL}/skate/model.glb`,
    '#a855f7',
    0.40,
    ['efoil', 'hydrofoil', 'surfboard', 'electric', 'watersports', 'ocean']
  )
];

// ============================================================================
// 7. SPACE, PLANETARY & SCI-FI VEHICLES (20+ items)
// ============================================================================
export const SPACE_VEHICLES: Real3DAsset[] = [
  createRealAsset(
    'veh-space-crew-capsule',
    'Orbital Crew Exploration Space Capsule',
    'Vehicles',
    'Ablative heat-shielded conical crew capsule with 4-astronaut capacity, docking port adapter, and reaction control thrusters.',
    'CREW CAPSULE',
    'bg-zinc-500/20 text-zinc-300 border-zinc-500/30',
    '🚀',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#52525b',
    0.75,
    ['space', 'capsule', 'nasa', 'astronaut', 'orbit', 'spacecraft', 'crew']
  ),
  createRealAsset(
    'veh-space-lunar-rover',
    'Lunar Surface 6-Wheel Exploration Rover',
    'Vehicles',
    'Rocker-bogie all-terrain planetary rover with woven wire mesh wheels, high-gain parabolic antenna, and solar wings.',
    'LUNAR ROVER',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🌖',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#f59e0b',
    0.72,
    ['rover', 'moon', 'lunar', 'space', 'planetary', 'exploration', 'nasa']
  ),
  createRealAsset(
    'veh-space-planetary-lander',
    'Interplanetary Planetary Heavy Lander',
    'Vehicles',
    'Hexagonal descent stage spacecraft with 4 shock-absorbing crushable landing pads and hydrazine descent engines.',
    'PLANETARY LANDER',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '🛸',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#ea580c',
    0.85,
    ['lander', 'mars', 'moon', 'planetary', 'spacecraft', 'touchdown']
  ),
  createRealAsset(
    'veh-space-rocket-booster',
    'Reusable Vertical Landing Rocket Booster',
    'Vehicles',
    'Orbital-class methane-fueled rocket stage with aerodynamic titanium grid fins and deployable carbon landing legs.',
    'ROCKET BOOSTER',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🚀',
    `${BASE_KHRONOS_URL}/WaterBottle/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/WaterBottle/glTF-Binary/WaterBottle.glb`,
    '#3b82f6',
    0.95,
    ['rocket', 'booster', 'reusable', 'propulsion', 'orbit', 'space', 'launch']
  ),
  createRealAsset(
    'veh-space-science-probe',
    'Deep Space Scientific Flyby Probe',
    'Vehicles',
    'Outer solar system robotic exploration spacecraft with 3-meter parabolic radio dish, RTG power unit, and magnetometers.',
    'SPACE PROBE',
    'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    '🛰️',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#6366f1',
    0.65,
    ['probe', 'satellite', 'deep space', 'solar system', 'voyager', 'science']
  ),
  createRealAsset(
    'veh-space-mars-rover',
    'Mars Sample Return Autonomous Rover',
    'Vehicles',
    'Nuclear-powered Mars exploration rover equipped with robotic coring arm, spectrometer mast, and autonomous navigation.',
    'MARS ROVER',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🪐',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#ef4444',
    0.74,
    ['mars', 'rover', 'perseverance', 'curiosity', 'space', 'sample return']
  ),
  createRealAsset(
    'veh-space-orbital-tug',
    'Sci-Fi Orbital Cargo Shifter Tug',
    'Vehicles',
    'Modular space station utility tug with magnetic grapples, cold-gas maneuvering thrusters, and cargo container bay.',
    'ORBITAL TUG',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🛰️',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#06b6d4',
    0.80,
    ['tug', 'orbital', 'space station', 'cargo', 'sci-fi', 'docking']
  ),
  createRealAsset(
    'veh-space-mining-drone',
    'Deep-Space Asteroid Mining Drill Drone',
    'Vehicles',
    'Heavy autonomous mining spacecraft with twin diamond rotary core drills and laser spectroscopy ore analyzer.',
    'ASTEROID MINER',
    'bg-amber-600/20 text-amber-300 border-amber-500/30',
    '☄️',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#d97706',
    0.82,
    ['asteroid', 'mining', 'drone', 'space', 'sci-fi', 'drill', 'resources']
  ),
  createRealAsset(
    'veh-space-resupply-shuttle',
    'Space Station Resupply Cargo Shuttle',
    'Vehicles',
    'Pressurized automated resupply spacecraft with automated laser optical rendezvous sensors and CBM docking ring.',
    'CARGO SHUTTLE',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '🛸',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#0ea5e9',
    0.86,
    ['shuttle', 'resupply', 'iss', 'cargo', 'space station', 'orbit']
  ),
  createRealAsset(
    'veh-space-suborbital-plane',
    'Hypersonic Sub-Orbital Spaceplane',
    'Vehicles',
    'Commercial astronaut passenger spaceplane featuring feathering re-entry tail booms and hybrid rocket motor.',
    'SPACEPLANE',
    'bg-purple-500/20 text-purple-300 border-purple-500/30',
    '🌌',
    `${BASE_KHRONOS_URL}/DamagedHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
    '#a855f7',
    0.90,
    ['spaceplane', 'suborbital', 'tourism', 'aerospace', 'hypersonic', 'flight']
  ),
  createRealAsset(
    'veh-space-lunar-hopper',
    'Lunar Cargo Delivery Surface Hopper',
    'Vehicles',
    'Vertical takeoff and landing rocket hopper for point-to-point sub-orbital payload delivery between moon bases.',
    'LUNAR HOPPER',
    'bg-slate-500/20 text-slate-300 border-slate-500/30',
    '🌕',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#64748b',
    0.78,
    ['hopper', 'moon', 'lunar base', 'cargo', 'vtol', 'rocket']
  ),
  createRealAsset(
    'veh-space-repulsor-speeder',
    'Sci-Fi Planetary Repulsorlift Speeder',
    'Vehicles',
    'Twin-turbine anti-gravity ground skimming speeder bike with neon energy exhausts and aerodynamic front vanes.',
    'REPULSOR SPEEDER',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '⚡',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#f43f5e',
    0.60,
    ['speeder', 'repulsorlift', 'anti-gravity', 'hover', 'sci-fi', 'cyberpunk']
  ),
  createRealAsset(
    'veh-space-telescope-sat',
    'Deep Space Infrared Telescope Satellite',
    'Vehicles',
    'L2 Lagrange point astronomical observatory with deployable 5-layer Kapton sunshield and gold-coated mirror array.',
    'TELESCOPE SAT',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🔭',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#eab308',
    0.88,
    ['telescope', 'jwst', 'space', 'satellite', 'astronomy', 'infrared', 'cosmos']
  ),
  createRealAsset(
    'veh-space-hover-pod',
    'Sci-Fi Anti-Gravity Floating Pod',
    'Vehicles',
    'Enclosed spherical passenger commuter capsule that hovers effortlessly on magnetic levitation tracks.',
    'HOVER POD',
    'bg-teal-500/20 text-teal-300 border-teal-500/30',
    '⚪',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#14b8a6',
    0.70,
    ['hover', 'pod', 'maglev', 'sci-fi', 'futuristic', 'anti-gravity']
  ),
  createRealAsset(
    'veh-space-mars-copter',
    'Mars Atmospheric Rotorcraft Helicopter',
    'Vehicles',
    'Ultra-lightweight coaxial counter-rotating carbon fiber rotor drone engineered for thin 1% Martian atmospheric density.',
    'MARS COPTER',
    'bg-red-600/20 text-red-300 border-red-500/30',
    '🚁',
    `${BASE_ITEM_URL}/ceiling-fan/thumbnail.webp`,
    `${BASE_ITEM_URL}/ceiling-fan/model.glb`,
    '#dc2626',
    0.45,
    ['mars', 'helicopter', 'ingenuity', 'rotorcraft', 'nasa', 'atmosphere']
  ),
  createRealAsset(
    'veh-space-solar-explorer',
    'Solar Radiation Research Satellite',
    'Vehicles',
    'Perihelion solar research probe with carbon-composite thermal heat shield designed to withstand 1,400°C temperatures.',
    'SOLAR PROBE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '☀️',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#f59e0b',
    0.76,
    ['solar probe', 'parker', 'sun', 'radiation', 'heat shield', 'space']
  ),
  createRealAsset(
    'veh-space-surface-habitat',
    'Planetary Extreme Terrain Surface Habitat Transporter',
    'Vehicles',
    'Pressurized 12-wheel mobile planetary habitat laboratory with airlock chamber and life-support regenerators.',
    'HABITAT HAULER',
    'bg-blue-600/20 text-blue-300 border-blue-500/30',
    '🚐',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#2563eb',
    0.95,
    ['habitat', 'mars base', 'rover', 'pressurized', 'life support', 'space']
  ),
  createRealAsset(
    'veh-space-fuel-depot',
    'Orbital Fuel Storage & Depot Tanker',
    'Vehicles',
    'Cryogenic orbital propellant depot equipped with sunshades, boil-off zero-loss reliquefaction, and quick-disconnect valves.',
    'FUEL DEPOT',
    'bg-emerald-600/20 text-emerald-300 border-emerald-500/30',
    '⛽',
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/screenshot/screenshot.gif`,
    `${BASE_KHRONOS_URL}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
    '#059669',
    0.92,
    ['fuel depot', 'orbital', 'refueling', 'cryogenic', 'propellant', 'tanker']
  ),
  createRealAsset(
    'veh-space-interceptor',
    'Sci-Fi Deep-Space Interceptor Starfighter',
    'Vehicles',
    'Single-pilot combat starfighter with quad plasma cannons, S-foil heat radiators, and ion sub-light drives.',
    'STARFIGHTER',
    'bg-violet-600/20 text-violet-300 border-violet-500/30',
    '🚀',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#7c3aed',
    0.88,
    ['starfighter', 'interceptor', 'sci-fi', 'plasma', 'spacecraft', 'fighter']
  ),
  createRealAsset(
    'veh-space-ion-probe',
    'Ion-Propulsion Interstellar Science Probe',
    'Vehicles',
    'Continuous low-thrust xenon ion propulsion spacecraft on a parabolic trajectory towards interstellar space.',
    'ION PROBE',
    'bg-cyan-600/20 text-cyan-300 border-cyan-500/30',
    '🌌',
    `${BASE_KHRONOS_URL}/SciFiHelmet/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/SciFiHelmet/glTF-Binary/SciFiHelmet.glb`,
    '#0891b2',
    0.70,
    ['ion drive', 'xenon', 'interstellar', 'deep space', 'propulsion', 'probe']
  )
];

// ============================================================================
// 8. MICROMOBILITY, MOTORCYCLES & BIKES (20+ items)
// ============================================================================
export const MICROMOBILITY_VEHICLES: Real3DAsset[] = [
  createRealAsset(
    'veh-micro-e-scooter',
    'Urban Electric Dual-Motor Kick Scooter',
    'Vehicles',
    'Foldable lightweight dual-motor electric urban commute scooter with regenerative braking and front headlight.',
    'E-SCOOTER',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '🛴',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#10b981',
    0.45,
    ['scooter', 'electric', 'urban', 'commute', 'mobility', 'kick scooter']
  ),
  createRealAsset(
    'veh-micro-skateboard',
    '7-Ply Canadian Maple Street Skateboard',
    'Vehicles',
    '7-ply Canadian maple skateboard deck with polyurethane wheels, precision ABEC-9 bearings, and grip tape.',
    'SKATEBOARD',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🛹',
    `${BASE_ITEM_URL}/skate/thumbnail.webp`,
    `${BASE_ITEM_URL}/skate/model.glb`,
    '#d97706',
    0.32,
    ['skateboard', 'skate', 'street', 'board', 'sports', 'deck']
  ),
  createRealAsset(
    'veh-micro-superbike',
    '1000cc Inline-4 Supersport Superbike',
    'Vehicles',
    '200HP aerodynamic racing superbike with inverted front forks, Brembo disc brakes, and titanium exhaust.',
    'SUPERBIKE',
    'bg-red-500/20 text-red-300 border-red-500/30',
    '🏍️',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#ef4444',
    0.55,
    ['motorcycle', 'superbike', 'moto', 'racing', 'sportbike', '1000cc']
  ),
  createRealAsset(
    'veh-micro-smart-ebike',
    'Step-Through Aluminum City Smart E-Bike',
    'Vehicles',
    'Step-through aluminum frame electric city bicycle with integrated downtube battery and torque-sensor pedal assist.',
    'SMART E-BIKE',
    'bg-teal-500/20 text-teal-300 border-teal-500/30',
    '🚲',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#0d9488',
    0.50,
    ['bicycle', 'ebike', 'commute', 'cycling', 'green mobility', 'city bike']
  ),
  createRealAsset(
    'veh-micro-enduro-mtb',
    'Full-Suspension Carbon Enduro Trail MTB',
    'Vehicles',
    'Downhill enduro mountain bike with 160mm air suspension fork, hydraulic disc brakes, and 29-inch tubeless tires.',
    'TRAIL MTB',
    'bg-emerald-600/20 text-emerald-300 border-emerald-500/30',
    '🚵',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#059669',
    0.52,
    ['mtb', 'mountain bike', 'cycling', 'trail', 'enduro', 'outdoors']
  ),
  createRealAsset(
    'veh-micro-hoverboard',
    'Self-Balancing Gyroscopic Smart Hoverboard',
    'Vehicles',
    'Dual-wheel gyroscopic self-balancing electric transporter with LED wheel fender arches and Bluetooth speaker.',
    'HOVERBOARD',
    'bg-purple-500/20 text-purple-300 border-purple-500/30',
    '🛹',
    `${BASE_ITEM_URL}/skate/thumbnail.webp`,
    `${BASE_ITEM_URL}/skate/model.glb`,
    '#a855f7',
    0.35,
    ['hoverboard', 'self-balancing', 'electric', 'mobility', 'tech', 'gyroscopic']
  ),
  createRealAsset(
    'veh-micro-unicycle',
    'High-Speed 18-Inch Electric Unicycle (EUC)',
    'Vehicles',
    'Single 18-inch all-terrain tire electric self-balancing monocycle vehicle with retractable trolley handle.',
    'E-UNICYCLE',
    'bg-amber-500/20 text-amber-300 border-amber-500/30',
    '🔘',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#f59e0b',
    0.38,
    ['euc', 'unicycle', 'electric', 'mobility', 'commute', 'monocycle']
  ),
  createRealAsset(
    'veh-micro-golf-cart',
    '4-Passenger Open Resort Electric Golf Buggy',
    'Vehicles',
    'Zero-emission 4-seat open-sided electric resort vehicle with roof sun canopy and rear-facing passenger bench.',
    'RESORT CART',
    'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    '⛳',
    `${BASE_KHRONOS_URL}/ToyCar/screenshot/screenshot.jpg`,
    `${BASE_KHRONOS_URL}/ToyCar/glTF-Binary/ToyCar.glb`,
    '#10b981',
    0.75,
    ['golf cart', 'buggy', 'resort', 'electric', 'vehicle', 'mobility']
  ),
  createRealAsset(
    'veh-micro-cargo-trike',
    'Electric Front-Loading Cargo Trike',
    'Vehicles',
    'Commercial 3-wheel electric cargo bicycle with 200kg capacity wooden front cargo box and rain canopy.',
    'CARGO TRIKE',
    'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    '🚲',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#eab308',
    0.58,
    ['cargo bike', 'trike', 'delivery', 'ebike', 'green logistics', 'bakfiets']
  ),
  createRealAsset(
    'veh-micro-cruiser-moto',
    'Heavy Touring V-Twin Cruiser Motorcycle',
    'Vehicles',
    'Low-slung classic American cruiser with 1800cc V-twin engine, swept handlebars, and leather saddlebags.',
    'V-TWIN CRUISER',
    'bg-slate-600/20 text-slate-300 border-slate-500/30',
    '🏍️',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#475569',
    0.62,
    ['cruiser', 'motorcycle', 'v-twin', 'touring', 'chopper', 'highway']
  ),
  createRealAsset(
    'veh-micro-cafe-racer',
    'Retro Cafe Racer 750cc Motorcycle',
    'Vehicles',
    'Vintage stripped-down custom cafe racer with clip-on handlebars, single hump seat, and wrapped header exhaust.',
    'CAFE RACER',
    'bg-zinc-600/20 text-zinc-300 border-zinc-500/30',
    '🏍️',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#52525b',
    0.54,
    ['cafe racer', 'custom', 'vintage', 'motorcycle', 'retro', 'classic']
  ),
  createRealAsset(
    'veh-micro-dirt-bike',
    'Competition Motocross Dirt Bike',
    'Vehicles',
    'High-clearance 450cc 4-stroke motocross bike with knobby off-road tires, long-travel monoshock, and roost guard.',
    'DIRT BIKE',
    'bg-orange-500/20 text-orange-300 border-orange-500/30',
    '🏁',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#f97316',
    0.56,
    ['dirt bike', 'motocross', 'offroad', 'enduro', 'motorcycle', 'jump']
  ),
  createRealAsset(
    'veh-micro-road-bike',
    'Lightweight Carbon Road Racing Bicycle',
    'Vehicles',
    'Aero carbon fiber frame road racing bicycle with drop handlebars, electronic shifting, and 50mm deep-section wheels.',
    'ROAD RACER',
    'bg-rose-500/20 text-rose-300 border-rose-500/30',
    '🚴',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#f43f5e',
    0.48,
    ['road bike', 'cycling', 'racing', 'carbon', 'bicycle', 'tour de france']
  ),
  createRealAsset(
    'veh-micro-foldable-scooter',
    'Ultra-Compact Foldable Electric Commuter',
    'Vehicles',
    'Ultra-light 9kg magnesium alloy folding electric scooter engineered to slide into trains, buses, and office desks.',
    'FOLD SCOOTER',
    'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    '🛴',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#06b6d4',
    0.42,
    ['folding', 'scooter', 'commuter', 'compact', 'transit', 'electric']
  ),
  createRealAsset(
    'veh-micro-quad-atv',
    'Heavy-Duty All-Terrain 4x4 Quad ATV',
    'Vehicles',
    'Rugged four-wheel-drive all-terrain quad vehicle with front and rear utility cargo racks and independent suspension.',
    '4X4 QUAD ATV',
    'bg-stone-600/20 text-stone-300 border-stone-500/30',
    '🚜',
    `${BASE_KHRONOS_URL}/Buggy/screenshot/screenshot.png`,
    `${BASE_KHRONOS_URL}/Buggy/glTF-Binary/Buggy.glb`,
    '#57534e',
    0.68,
    ['quad', 'atv', '4x4', 'all-terrain', 'offroad', 'utility', 'mud']
  ),
  createRealAsset(
    'veh-micro-drift-trike',
    'High-Power Electric Drift Trike',
    'Vehicles',
    'Front-wheel motor electric drift trike with hard PVC rear drift wheel sleeves for controlled power slides.',
    'DRIFT TRIKE',
    'bg-red-600/20 text-red-300 border-red-500/30',
    '⚡',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#dc2626',
    0.46,
    ['drift', 'trike', 'electric', 'slide', 'stunt', 'fun', 'wheels']
  ),
  createRealAsset(
    'veh-micro-electric-longboard',
    'Dual-Belt Electric Longboard Skateboard',
    'Vehicles',
    'Bamboo-fiberglass flexible drop-through deck electric longboard with handheld wireless throttle remote control.',
    'E-LONGBOARD',
    'bg-amber-600/20 text-amber-300 border-amber-500/30',
    '🛹',
    `${BASE_ITEM_URL}/skate/thumbnail.webp`,
    `${BASE_ITEM_URL}/skate/model.glb`,
    '#d97706',
    0.36,
    ['longboard', 'electric skateboard', 'esk8', 'skate', 'commute', 'speed']
  ),
  createRealAsset(
    'veh-micro-dutch-bike',
    'Classic European Step-Through Town Bike',
    'Vehicles',
    'Traditional upright city town bicycle with front wicker basket, rear luggage carrier, and full chain guard.',
    'DUTCH TOWN BIKE',
    'bg-blue-500/20 text-blue-300 border-blue-500/30',
    '🚲',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#3b82f6',
    0.49,
    ['dutch bike', 'city', 'town bike', 'basket', 'classic', 'cycling']
  ),
  createRealAsset(
    'veh-micro-snowmobile',
    'High-Performance Winter Snowmobile Sled',
    'Vehicles',
    '850cc 2-stroke trail sport snowmobile with deep-lug powder track, heated windshield, and dual front ski runners.',
    'TRAIL SNOWMOBILE',
    'bg-sky-500/20 text-sky-300 border-sky-500/30',
    '🛷',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#0ea5e9',
    0.65,
    ['snowmobile', 'sled', 'snow', 'winter', 'trail', 'mountain', 'ski']
  ),
  createRealAsset(
    'veh-micro-segway',
    'Gyroscopic Personal Urban Segway Transporter',
    'Vehicles',
    'Self-balancing stand-up two-wheel personal transporter with handlebar steering and dynamic lean control.',
    'SEGWAY',
    'bg-violet-500/20 text-violet-300 border-violet-500/30',
    '🛴',
    `${BASE_ITEM_URL}/scooter/thumbnail.webp`,
    `${BASE_ITEM_URL}/scooter/model.glb`,
    '#8b5cf6',
    0.44,
    ['segway', 'transporter', 'gyroscopic', 'self-balancing', 'urban', 'commute']
  )
];

// ============================================================================
// MASTER VEHICLES AGGREGATION (Over 160+ unique assets, 20+ per purpose category)
// ============================================================================
export const VEHICLES_ASSETS: Real3DAsset[] = [
  ...EMERGENCY_VEHICLES,
  ...CARTOON_VEHICLES,
  ...REALISTIC_CARS,
  ...COMMERCIAL_VEHICLES,
  ...AVIATION_VEHICLES,
  ...MARITIME_VEHICLES,
  ...SPACE_VEHICLES,
  ...MICROMOBILITY_VEHICLES
];
